# Speaker Verification using ResNet

This notebook implements a text-independent speaker verification system using:

- LibriSpeech train-clean-100
- 50,000 balanced speaker pairs
- 3-second random crop or padding
- Log-Mel Spectrogram (80 mel bins)
- ResNet backbone

---

## 1. Dataset Setup

In [1]:
import os
import pandas as pd
import numpy as np

# Dataset root
DATASET_ROOT = "/kaggle/input/datasets/tahmidulislamomi/ml-project-openslr-dataset"

# Inner audio folder (second train-clean-100)
BASE_AUDIO_DIR = os.path.join(DATASET_ROOT, "train-clean-100", "train-clean-100")

# CSV path
CSV_PATH = os.path.join(DATASET_ROOT, "train_pairs.csv")

print("BASE_AUDIO_DIR:", BASE_AUDIO_DIR)
print("CSV_PATH:", CSV_PATH)

BASE_AUDIO_DIR: /kaggle/input/datasets/tahmidulislamomi/ml-project-openslr-dataset/train-clean-100/train-clean-100
CSV_PATH: /kaggle/input/datasets/tahmidulislamomi/ml-project-openslr-dataset/train_pairs.csv

## 2. Load and Inspect Training Data

Load the training CSV file and display the first few rows along with the label distribution to confirm the dataset is balanced.

In [2]:
df = pd.read_csv(CSV_PATH)

print("First 5 rows:")
display(df.head())

print("Total rows:", len(df))
print("Label distribution:")
print(df["label"].value_counts())

First 5 rows:

,audio_path_1,audio_path_2,label
0,train-clean-100/311/124404/311-124404-0059.flac,train-clean-100/311/124404/311-124404-0009.flac,1
1,train-clean-100/1455/134435/1455-134435-0051.flac,train-clean-100/1455/134435/1455-134435-0058.flac,1
2,train-clean-100/4397/15668/4397-15668-0028.flac,train-clean-100/4397/15678/4397-15678-0002.flac,1
3,train-clean-100/2514/149482/2514-149482-0028.flac,train-clean-100/2514/149482/2514-149482-0038.flac,1
4,train-clean-100/669/129074/669-129074-0021.flac,train-clean-100/669/129061/669-129061-0026.flac,1

Total rows: 50000
Label distribution:
label
1    25000
0    25000
Name: count, dtype: int64

## 3. Resolve Absolute Audio Paths

The CSV contains relative paths prefixed with `train-clean-100/`. `to_absolute_path()` strips that prefix and joins with the true Kaggle dataset root so that `soundfile` can locate each `.flac` file.

In [3]:
def to_absolute_path(rel_path):
    # Remove first occurrence of train-clean-100/
    cleaned = rel_path.replace("train-clean-100/", "", 1)
    return os.path.join(BASE_AUDIO_DIR, cleaned)

df["path1_abs"] = df["audio_path_1"].apply(to_absolute_path)
df["path2_abs"] = df["audio_path_2"].apply(to_absolute_path)

display(df[["path1_abs", "path2_abs", "label"]].head())

,path1_abs,path2_abs,label
0,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,1
1,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,1
2,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,1
3,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,1
4,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,/kaggle/input/datasets/tahmidulislamomi/ml-pro...,1

In [4]:
missing_1 = (~df["path1_abs"].apply(os.path.exists)).sum()
missing_2 = (~df["path2_abs"].apply(os.path.exists)).sum()

print("Missing path1 files:", missing_1)
print("Missing path2 files:", missing_2)

Missing path1 files: 0
Missing path2 files: 0

## 4. Audio Sample Verification

Read one audio pair from disk to confirm that the resolved paths are valid and that the sample rates match the expected 16 kHz.

In [5]:
import soundfile as sf

sample_row = df.iloc[0]

audio1, sr1 = sf.read(sample_row["path1_abs"])
audio2, sr2 = sf.read(sample_row["path2_abs"])

print("Audio1 shape:", audio1.shape, "Sample rate:", sr1)
print("Audio2 shape:", audio2.shape, "Sample rate:", sr2)

Audio1 shape: (228160,) Sample rate: 16000
Audio2 shape: (174560,) Sample rate: 16000

In [6]:
import numpy as np

## Standardize Audio Length (3 Seconds)

- Target sample rate: 16 kHz  
- Target duration: 3 seconds (48,000 samples)

Function `crop_or_pad()`:
- If audio is longer → random crop to 3 seconds  
- If audio is shorter → zero pad to 3 seconds  
- Ensures fixed-length input for neural network training

In [7]:
TARGET_SR = 16000
TARGET_DURATION = 3  # seconds
TARGET_LENGTH = TARGET_SR * TARGET_DURATION  # 48000


def crop_or_pad(audio):
    """
    Ensures audio is exactly 3 seconds (48000 samples).
    - If longer → random crop
    - If shorter → zero pad
    """
    length = len(audio)

    # If longer → random crop
    if length > TARGET_LENGTH:
        start = np.random.randint(0, length - TARGET_LENGTH)
        audio = audio[start:start + TARGET_LENGTH]

    # If shorter → pad with zeros
    elif length < TARGET_LENGTH:
        pad_amount = TARGET_LENGTH - length
        audio = np.pad(audio, (0, pad_amount), mode='constant')

    return audio

In [8]:
audio1_fixed = crop_or_pad(audio1)
audio2_fixed = crop_or_pad(audio2)

print(audio1_fixed.shape)  # should be (48000,)
print(audio2_fixed.shape)

(48000,)
(48000,)

In [9]:
import torchaudio
import torch
import torchaudio.transforms as T

## Create Log-Mel Spectrogram Transform

- Sample rate: 16 kHz  
- Window size: 25 ms (n_fft = 400)  
- Hop length: 10 ms (160 samples)  
- Number of Mel bins: 80  

`MelSpectrogram` converts waveform → Mel-frequency representation.  
`AmplitudeToDB` converts amplitude to log scale for stable training.

In [10]:
mel_transform = T.MelSpectrogram(
    sample_rate=16000,
    n_fft=400,              # 25 ms window (16000 * 0.025 = 400)
    hop_length=160,         # 10 ms stride (16000 * 0.01 = 160)
    n_mels=80
)

amplitude_to_db = T.AmplitudeToDB()

## Convert Audio to Log-Mel Spectrogram

Steps:
- Convert NumPy audio → Torch tensor  
- Add channel dimension (1, 48000)  
- Apply MelSpectrogram transform  
- Convert to log scale (dB)

Final output shape:
(1, 80, ~300) → Image-like input for CNN/ResNet

In [11]:
# Convert numpy → torch tensor
audio_tensor = torch.tensor(audio1_fixed).float()

# Add channel dimension (1, 48000)
audio_tensor = audio_tensor.unsqueeze(0)

# Compute Mel spectrogram
mel_spec = mel_transform(audio_tensor)

# Convert to log scale
log_mel_spec = amplitude_to_db(mel_spec)

print("Log-Mel shape:", log_mel_spec.shape)

Log-Mel shape: torch.Size([1, 80, 301])

## 5. Custom Dataset Class

`SpeakerPairDataset` handles the full preprocessing pipeline on the fly:
- Reads raw `.flac` audio with `soundfile`
- Converts stereo to mono if needed
- Applies `crop_or_pad()` to fix length at 3 seconds
- Computes the Log-Mel Spectrogram
- Returns `(mel1, mel2, label)` per pair

In [12]:
from torch.utils.data import Dataset
import soundfile as sf

In [13]:
class SpeakerPairDataset(Dataset):
    def __init__(self, dataframe, mel_transform, amplitude_to_db):
        self.df = dataframe
        self.mel_transform = mel_transform
        self.amplitude_to_db = amplitude_to_db

    def __len__(self):
        return len(self.df)

    def load_audio(self, path):
        audio, sr = sf.read(path)

        # Ensure mono
        if len(audio.shape) > 1:
            audio = np.mean(audio, axis=1)

        audio = crop_or_pad(audio)

        audio = torch.tensor(audio).float().unsqueeze(0)

        mel = self.mel_transform(audio)
        log_mel = self.amplitude_to_db(mel)

        return log_mel

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        mel1 = self.load_audio(row["path1_abs"])
        mel2 = self.load_audio(row["path2_abs"])

        label = torch.tensor(row["label"]).float()

        return mel1, mel2, label

## 6. Instantiate Training Dataset

Create a `SpeakerPairDataset` from the full 50,000-pair training DataFrame.

In [14]:
dataset = SpeakerPairDataset(df, mel_transform, amplitude_to_db)

print("Dataset size:", len(dataset))

Dataset size: 50000

In [15]:
mel1, mel2, label = dataset[0]

print("Mel1 shape:", mel1.shape)
print("Mel2 shape:", mel2.shape)
print("Label:", label)

Mel1 shape: torch.Size([1, 80, 301])
Mel2 shape: torch.Size([1, 80, 301])
Label: tensor(1.)

## 7. DataLoader Setup — Training

`DataLoader` wraps the dataset for efficient batched, multi-worker loading.
- `batch_size = 16` — number of pairs per batch
- `shuffle = True` — randomize order every epoch
- `pin_memory = True` — speeds up GPU data transfer

In [16]:
from torch.utils.data import DataLoader

batch_size = 16

dataloader = DataLoader(
    dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

print("DataLoader ready")

DataLoader ready

In [17]:
batch_mel1, batch_mel2, batch_labels = next(iter(dataloader))

print("Batch mel1:", batch_mel1.shape)
print("Batch mel2:", batch_mel2.shape)
print("Batch labels:", batch_labels.shape)

Batch mel1: torch.Size([16, 1, 80, 301])
Batch mel2: torch.Size([16, 1, 80, 301])
Batch labels: torch.Size([16])

## 8. Model Architecture — ResNetSpeaker

`ResNetSpeaker` is a Siamese network built on ResNet-18:
- **Input conv** modified from 3-channel RGB to 1-channel (grayscale Log-Mel Spectrogram)
- **Classification head** replaced with a 256-dimensional embedding layer
- **L2 normalization** applied to embeddings, enabling direct cosine similarity comparison

In [18]:
import torch.nn as nn
import torchvision.models as models

In [19]:
class ResNetSpeaker(nn.Module):
    def __init__(self, embedding_dim=256):
        super().__init__()

        # Load ResNet18 
        self.backbone = models.resnet18(weights=None)

        # Modify first conv layer to accept 1
        self.backbone.conv1 = nn.Conv2d(
            in_channels=1,
            out_channels=64,
            kernel_size=7,
            stride=2,
            padding=3,
            bias=False
        )

        # Remove final classification layer
        in_features = self.backbone.fc.in_features
        self.backbone.fc = nn.Identity()

        # Add embedding layer
        self.embedding = nn.Linear(in_features, embedding_dim)

    def forward(self, x):
        features = self.backbone(x)
        embedding = self.embedding(features)

        # Normalize embedding (important for cosine similarity)
        embedding = nn.functional.normalize(embedding, p=2, dim=1)

        return embedding

## 9. Initialize Model on Device

Detect and use GPU (CUDA) if available, otherwise fall back to CPU. Instantiate and print the full `ResNetSpeaker` architecture.

In [20]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = ResNetSpeaker(embedding_dim=256).to(device)

print(model)

ResNetSpeaker(
  (backbone): ResNet(
    (conv1): Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer2): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (downsample): Sequential(
          (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): BasicBlock(
        (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer3): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (downsample): Sequential(
          (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): BasicBlock(
        (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer4): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (downsample): Sequential(
          (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): BasicBlock(
        (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
    (fc): Identity()
  )
  (embedding): Linear(in_features=512, out_features=256, bias=True)
)

In [21]:
batch_mel1, batch_mel2, batch_labels = next(iter(dataloader))

batch_mel1 = batch_mel1.to(device)

embeddings = model(batch_mel1)

print("Embedding shape:", embeddings.shape)

Embedding shape: torch.Size([16, 256])

In [22]:
import torch.nn.functional as F

## 10. Contrastive Loss Function

`ContrastiveLoss` trains the model to:
- **Pull** same-speaker embeddings *closer* together (label = 1)
- **Push** different-speaker embeddings *further apart* (label = 0)

Distance is measured using **Euclidean distance** between the two L2-normalized embedding vectors.

In [23]:
class ContrastiveLoss(nn.Module):
    def __init__(self, margin=1.0):
        super().__init__()
        self.margin = margin

    def forward(self, emb1, emb2, label):
        # Euclidean distance
        distance = F.pairwise_distance(emb1, emb2)

        # Positive loss (label=1)
        pos_loss = label * torch.pow(distance, 2)

        # Negative loss (label=0)
        neg_loss = (1 - label) * torch.pow(torch.clamp(self.margin - distance, min=0.0), 2)

        loss = torch.mean(pos_loss + neg_loss)
        return loss

## 11. Training Configuration

Reinitialize the model (clean weights), define the contrastive loss criterion with `margin = 1.0`, and configure the **Adam optimizer** with a learning rate of `1e-3`.

In [24]:
model = ResNetSpeaker(256).to(device)

criterion = ContrastiveLoss(margin=1.0)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

## 12. Training Loop

Train for **30 epochs** over the full 50,000 training pairs.
- Each batch: forward pass → compute contrastive loss → backpropagation → optimizer step
- Live loss is displayed in the `tqdm` progress bar
- Average epoch loss is printed at the end of each epoch

In [25]:
from tqdm import tqdm

num_epochs = 30
print_every = 50   # print every 50 batches

for epoch in range(num_epochs):
    model.train()
    total_loss = 0

    progress_bar = tqdm(enumerate(dataloader), 
                        total=len(dataloader),
                        desc=f"Epoch {epoch+1}/{num_epochs}")

    for batch_idx, (mel1, mel2, labels) in progress_bar:

        mel1 = mel1.to(device)
        mel2 = mel2.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        emb1 = model(mel1)
        emb2 = model(mel2)

        loss = criterion(emb1, emb2, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # 🔹 Update tqdm live loss
        progress_bar.set_postfix(loss=loss.item())

        # 🔹 Extra debug print
        if batch_idx % print_every == 0:
            print(f"Epoch {epoch+1} | Batch {batch_idx}/{len(dataloader)} | Loss: {loss.item():.4f}")

    avg_loss = total_loss / len(dataloader)
    print(f"\nEpoch [{epoch+1}/{num_epochs}] - Avg Loss: {avg_loss:.4f}\n")

Epoch 1/30:   0%|          | 3/3125 [00:01<20:39,  2.52it/s, loss=0.256]

Epoch 1 | Batch 0/3125 | Loss: 0.3274

Epoch 1/30:   2%|▏         | 51/3125 [00:14<13:30,  3.79it/s, loss=0.291]

Epoch 1 | Batch 50/3125 | Loss: 0.2498

Epoch 1/30:   3%|▎         | 101/3125 [00:27<12:44,  3.95it/s, loss=0.223]

Epoch 1 | Batch 100/3125 | Loss: 0.1983

Epoch 1/30:   5%|▍         | 151/3125 [00:40<12:43,  3.90it/s, loss=0.076]

Epoch 1 | Batch 150/3125 | Loss: 0.1489

Epoch 1/30:   6%|▋         | 201/3125 [00:52<12:27,  3.91it/s, loss=0.113]

Epoch 1 | Batch 200/3125 | Loss: 0.1142

Epoch 1/30:   8%|▊         | 251/3125 [01:04<11:05,  4.32it/s, loss=0.213]

Epoch 1 | Batch 250/3125 | Loss: 0.2572

Epoch 1/30:  10%|▉         | 301/3125 [01:16<10:41,  4.40it/s, loss=0.152]

Epoch 1 | Batch 300/3125 | Loss: 0.0793

Epoch 1/30:  11%|█         | 351/3125 [01:27<10:18,  4.48it/s, loss=0.224]

Epoch 1 | Batch 350/3125 | Loss: 0.1166

Epoch 1/30:  13%|█▎        | 400/3125 [01:38<09:50,  4.62it/s, loss=0.326]

Epoch 1 | Batch 400/3125 | Loss: 0.3265

Epoch 1/30:  14%|█▍        | 450/3125 [01:49<10:01,  4.44it/s, loss=0.118]

Epoch 1 | Batch 450/3125 | Loss: 0.1178

Epoch 1/30:  16%|█▌        | 500/3125 [01:59<08:53,  4.92it/s, loss=0.175]

Epoch 1 | Batch 500/3125 | Loss: 0.1755

Epoch 1/30:  18%|█▊        | 551/3125 [02:10<08:53,  4.83it/s, loss=0.0857]

Epoch 1 | Batch 550/3125 | Loss: 0.1643

Epoch 1/30:  19%|█▉        | 601/3125 [02:21<09:15,  4.54it/s, loss=0.137]

Epoch 1 | Batch 600/3125 | Loss: 0.2000

Epoch 1/30:  21%|██        | 651/3125 [02:31<07:45,  5.31it/s, loss=0.156]

Epoch 1 | Batch 650/3125 | Loss: 0.1218

Epoch 1/30:  22%|██▏       | 701/3125 [02:40<07:33,  5.34it/s, loss=0.161]

Epoch 1 | Batch 700/3125 | Loss: 0.0793

Epoch 1/30:  24%|██▍       | 751/3125 [02:50<07:39,  5.17it/s, loss=0.115]

Epoch 1 | Batch 750/3125 | Loss: 0.1288

Epoch 1/30:  26%|██▌       | 801/3125 [02:59<07:19,  5.29it/s, loss=0.143]

Epoch 1 | Batch 800/3125 | Loss: 0.1790

Epoch 1/30:  27%|██▋       | 851/3125 [03:09<06:53,  5.51it/s, loss=0.0999]

Epoch 1 | Batch 850/3125 | Loss: 0.1076

Epoch 1/30:  29%|██▉       | 901/3125 [03:18<06:41,  5.54it/s, loss=0.124]

Epoch 1 | Batch 900/3125 | Loss: 0.1566

Epoch 1/30:  30%|███       | 951/3125 [03:27<06:17,  5.76it/s, loss=0.102]

Epoch 1 | Batch 950/3125 | Loss: 0.1496

Epoch 1/30:  32%|███▏      | 1000/3125 [03:36<06:39,  5.32it/s, loss=0.114]

Epoch 1 | Batch 1000/3125 | Loss: 0.1137

Epoch 1/30:  34%|███▎      | 1051/3125 [03:45<06:07,  5.65it/s, loss=0.174]

Epoch 1 | Batch 1050/3125 | Loss: 0.0920

Epoch 1/30:  35%|███▌      | 1101/3125 [03:54<06:12,  5.44it/s, loss=0.144]

Epoch 1 | Batch 1100/3125 | Loss: 0.1233

Epoch 1/30:  37%|███▋      | 1151/3125 [04:03<06:05,  5.40it/s, loss=0.127]

Epoch 1 | Batch 1150/3125 | Loss: 0.0615

Epoch 1/30:  38%|███▊      | 1201/3125 [04:11<05:16,  6.08it/s, loss=0.256]

Epoch 1 | Batch 1200/3125 | Loss: 0.1566

Epoch 1/30:  40%|████      | 1250/3125 [04:20<06:41,  4.67it/s, loss=0.122]

Epoch 1 | Batch 1250/3125 | Loss: 0.1216

Epoch 1/30:  42%|████▏     | 1300/3125 [04:28<04:31,  6.72it/s, loss=0.115]

Epoch 1 | Batch 1300/3125 | Loss: 0.1155

Epoch 1/30:  43%|████▎     | 1350/3125 [04:36<04:46,  6.20it/s, loss=0.216]

Epoch 1 | Batch 1350/3125 | Loss: 0.2157

Epoch 1/30:  45%|████▍     | 1401/3125 [04:44<04:05,  7.03it/s, loss=0.111]

Epoch 1 | Batch 1400/3125 | Loss: 0.1107

Epoch 1/30:  46%|████▋     | 1451/3125 [04:52<04:57,  5.63it/s, loss=0.105]

Epoch 1 | Batch 1450/3125 | Loss: 0.1058

Epoch 1/30:  48%|████▊     | 1501/3125 [05:00<04:33,  5.94it/s, loss=0.0507]

Epoch 1 | Batch 1500/3125 | Loss: 0.0865

Epoch 1/30:  50%|████▉     | 1551/3125 [05:08<04:11,  6.26it/s, loss=0.0943]

Epoch 1 | Batch 1550/3125 | Loss: 0.1438

Epoch 1/30:  51%|█████     | 1601/3125 [05:16<03:58,  6.40it/s, loss=0.0656]

Epoch 1 | Batch 1600/3125 | Loss: 0.0492

Epoch 1/30:  53%|█████▎    | 1651/3125 [05:23<03:42,  6.63it/s, loss=0.0593]

Epoch 1 | Batch 1650/3125 | Loss: 0.1140

Epoch 1/30:  54%|█████▍    | 1702/3125 [05:31<03:59,  5.95it/s, loss=0.147]

Epoch 1 | Batch 1700/3125 | Loss: 0.0781

Epoch 1/30:  56%|█████▌    | 1751/3125 [05:39<03:18,  6.92it/s, loss=0.135]

Epoch 1 | Batch 1750/3125 | Loss: 0.0473

Epoch 1/30:  58%|█████▊    | 1800/3125 [05:46<03:31,  6.25it/s, loss=0.0653]

Epoch 1 | Batch 1800/3125 | Loss: 0.0653

Epoch 1/30:  59%|█████▉    | 1850/3125 [05:53<03:12,  6.64it/s, loss=0.0868]

Epoch 1 | Batch 1850/3125 | Loss: 0.0868

Epoch 1/30:  61%|██████    | 1900/3125 [06:01<02:57,  6.90it/s, loss=0.116]

Epoch 1 | Batch 1900/3125 | Loss: 0.1157

Epoch 1/30:  62%|██████▏   | 1950/3125 [06:08<02:55,  6.71it/s, loss=0.172]

Epoch 1 | Batch 1950/3125 | Loss: 0.1723

Epoch 1/30:  64%|██████▍   | 2001/3125 [06:15<02:46,  6.74it/s, loss=0.111]

Epoch 1 | Batch 2000/3125 | Loss: 0.2146

Epoch 1/30:  66%|██████▌   | 2051/3125 [06:22<02:32,  7.04it/s, loss=0.0806]

Epoch 1 | Batch 2050/3125 | Loss: 0.1382

Epoch 1/30:  67%|██████▋   | 2101/3125 [06:29<02:20,  7.28it/s, loss=0.145]

Epoch 1 | Batch 2100/3125 | Loss: 0.1651

Epoch 1/30:  69%|██████▉   | 2151/3125 [06:36<02:13,  7.28it/s, loss=0.0573]

Epoch 1 | Batch 2150/3125 | Loss: 0.0739

Epoch 1/30:  70%|███████   | 2201/3125 [06:43<02:02,  7.56it/s, loss=0.08]

Epoch 1 | Batch 2200/3125 | Loss: 0.0666

Epoch 1/30:  72%|███████▏  | 2251/3125 [06:50<02:01,  7.22it/s, loss=0.0768]

Epoch 1 | Batch 2250/3125 | Loss: 0.1254

Epoch 1/30:  74%|███████▎  | 2301/3125 [06:57<02:00,  6.83it/s, loss=0.111]

Epoch 1 | Batch 2300/3125 | Loss: 0.1429

Epoch 1/30:  75%|███████▌  | 2351/3125 [07:04<01:49,  7.07it/s, loss=0.105]

Epoch 1 | Batch 2350/3125 | Loss: 0.1182

Epoch 1/30:  77%|███████▋  | 2401/3125 [07:11<01:44,  6.94it/s, loss=0.217]

Epoch 1 | Batch 2400/3125 | Loss: 0.1858

Epoch 1/30:  78%|███████▊  | 2451/3125 [07:18<01:41,  6.65it/s, loss=0.0663]

Epoch 1 | Batch 2450/3125 | Loss: 0.0997

Epoch 1/30:  80%|████████  | 2501/3125 [07:25<01:28,  7.08it/s, loss=0.0759]

Epoch 1 | Batch 2500/3125 | Loss: 0.0998

Epoch 1/30:  82%|████████▏ | 2551/3125 [07:32<01:17,  7.38it/s, loss=0.153]

Epoch 1 | Batch 2550/3125 | Loss: 0.0959

Epoch 1/30:  83%|████████▎ | 2602/3125 [07:40<01:09,  7.49it/s, loss=0.122]

Epoch 1 | Batch 2600/3125 | Loss: 0.1280

Epoch 1/30:  85%|████████▍ | 2650/3125 [07:46<01:07,  6.99it/s, loss=0.126]

Epoch 1 | Batch 2650/3125 | Loss: 0.1258

Epoch 1/30:  86%|████████▋ | 2702/3125 [07:53<00:57,  7.38it/s, loss=0.0903]

Epoch 1 | Batch 2700/3125 | Loss: 0.0612

Epoch 1/30:  88%|████████▊ | 2752/3125 [08:00<00:46,  8.07it/s, loss=0.0986]

Epoch 1 | Batch 2750/3125 | Loss: 0.1104

Epoch 1/30:  90%|████████▉ | 2800/3125 [08:07<00:44,  7.37it/s, loss=0.0732]

Epoch 1 | Batch 2800/3125 | Loss: 0.0732

Epoch 1/30:  91%|█████████ | 2850/3125 [08:13<00:36,  7.51it/s, loss=0.158]

Epoch 1 | Batch 2850/3125 | Loss: 0.1581

Epoch 1/30:  93%|█████████▎| 2901/3125 [08:20<00:30,  7.25it/s, loss=0.0993]

Epoch 1 | Batch 2900/3125 | Loss: 0.1252

Epoch 1/30:  94%|█████████▍| 2952/3125 [08:28<00:23,  7.31it/s, loss=0.106]

Epoch 1 | Batch 2950/3125 | Loss: 0.0939

Epoch 1/30:  96%|█████████▌| 3000/3125 [08:34<00:16,  7.64it/s, loss=0.0677]

Epoch 1 | Batch 3000/3125 | Loss: 0.0677

Epoch 1/30:  98%|█████████▊| 3052/3125 [08:41<00:09,  8.02it/s, loss=0.134]

Epoch 1 | Batch 3050/3125 | Loss: 0.1145

Epoch 1/30:  99%|█████████▉| 3100/3125 [08:47<00:03,  7.87it/s, loss=0.0795]

Epoch 1 | Batch 3100/3125 | Loss: 0.0795

Epoch 1/30: 100%|██████████| 3125/3125 [08:51<00:00,  5.88it/s, loss=0.109]

Epoch [1/30] - Avg Loss: 0.1306

Epoch 2/30:   0%|          | 1/3125 [00:00<15:35,  3.34it/s, loss=0.0959]

Epoch 2 | Batch 0/3125 | Loss: 0.0683

Epoch 2/30:   2%|▏         | 51/3125 [00:06<06:29,  7.89it/s, loss=0.14]

Epoch 2 | Batch 50/3125 | Loss: 0.0683

Epoch 2/30:   3%|▎         | 101/3125 [00:12<06:21,  7.92it/s, loss=0.0543]

Epoch 2 | Batch 100/3125 | Loss: 0.1086

Epoch 2/30:   5%|▍         | 151/3125 [00:19<05:54,  8.38it/s, loss=0.238]

Epoch 2 | Batch 150/3125 | Loss: 0.1763

Epoch 2/30:   6%|▋         | 201/3125 [00:25<06:07,  7.96it/s, loss=0.064]

Epoch 2 | Batch 200/3125 | Loss: 0.1144

Epoch 2/30:   8%|▊         | 251/3125 [00:31<05:48,  8.26it/s, loss=0.127]

Epoch 2 | Batch 250/3125 | Loss: 0.1605

Epoch 2/30:  10%|▉         | 302/3125 [00:38<05:49,  8.08it/s, loss=0.086]

Epoch 2 | Batch 300/3125 | Loss: 0.1038

Epoch 2/30:  11%|█▏        | 352/3125 [00:44<06:02,  7.66it/s, loss=0.118]

Epoch 2 | Batch 350/3125 | Loss: 0.1104

Epoch 2/30:  13%|█▎        | 402/3125 [00:50<05:27,  8.31it/s, loss=0.126]

Epoch 2 | Batch 400/3125 | Loss: 0.0877

Epoch 2/30:  14%|█▍        | 452/3125 [00:57<05:17,  8.43it/s, loss=0.136]

Epoch 2 | Batch 450/3125 | Loss: 0.1451

Epoch 2/30:  16%|█▌        | 502/3125 [01:03<05:24,  8.08it/s, loss=0.0555]

Epoch 2 | Batch 500/3125 | Loss: 0.0822

Epoch 2/30:  18%|█▊        | 552/3125 [01:09<05:04,  8.46it/s, loss=0.117]

Epoch 2 | Batch 550/3125 | Loss: 0.0455

Epoch 2/30:  19%|█▉        | 602/3125 [01:15<05:26,  7.73it/s, loss=0.0833]

Epoch 2 | Batch 600/3125 | Loss: 0.0631

Epoch 2/30:  21%|██        | 652/3125 [01:22<05:16,  7.82it/s, loss=0.0612]

Epoch 2 | Batch 650/3125 | Loss: 0.0762

Epoch 2/30:  22%|██▏       | 702/3125 [01:28<04:57,  8.14it/s, loss=0.158]

Epoch 2 | Batch 700/3125 | Loss: 0.1521

Epoch 2/30:  24%|██▍       | 750/3125 [01:34<05:21,  7.39it/s, loss=0.0821]

Epoch 2 | Batch 750/3125 | Loss: 0.0821

Epoch 2/30:  26%|██▌       | 802/3125 [01:41<05:00,  7.73it/s, loss=0.0702]

Epoch 2 | Batch 800/3125 | Loss: 0.0430

Epoch 2/30:  27%|██▋       | 852/3125 [01:47<04:44,  7.98it/s, loss=0.112]

Epoch 2 | Batch 850/3125 | Loss: 0.1247

Epoch 2/30:  29%|██▉       | 902/3125 [01:53<04:28,  8.29it/s, loss=0.118]

Epoch 2 | Batch 900/3125 | Loss: 0.1239

Epoch 2/30:  30%|███       | 952/3125 [01:59<04:27,  8.12it/s, loss=0.0758]

Epoch 2 | Batch 950/3125 | Loss: 0.0749

Epoch 2/30:  32%|███▏      | 1002/3125 [02:06<04:07,  8.58it/s, loss=0.0685]

Epoch 2 | Batch 1000/3125 | Loss: 0.1178

Epoch 2/30:  34%|███▎      | 1052/3125 [02:12<04:28,  7.71it/s, loss=0.104]

Epoch 2 | Batch 1050/3125 | Loss: 0.1641

Epoch 2/30:  35%|███▌      | 1102/3125 [02:18<04:21,  7.75it/s, loss=0.0686]

Epoch 2 | Batch 1100/3125 | Loss: 0.1236

Epoch 2/30:  37%|███▋      | 1150/3125 [02:25<04:28,  7.36it/s, loss=0.0861]

Epoch 2 | Batch 1150/3125 | Loss: 0.0861

Epoch 2/30:  38%|███▊      | 1202/3125 [02:31<04:14,  7.56it/s, loss=0.133]

Epoch 2 | Batch 1200/3125 | Loss: 0.1198

Epoch 2/30:  40%|████      | 1250/3125 [02:37<03:54,  8.00it/s, loss=0.104]

Epoch 2 | Batch 1250/3125 | Loss: 0.1043

Epoch 2/30:  42%|████▏     | 1300/3125 [02:44<03:45,  8.08it/s, loss=0.0661]

Epoch 2 | Batch 1300/3125 | Loss: 0.0661

Epoch 2/30:  43%|████▎     | 1352/3125 [02:50<03:41,  7.99it/s, loss=0.106]

Epoch 2 | Batch 1350/3125 | Loss: 0.0631

Epoch 2/30:  45%|████▍     | 1402/3125 [02:57<03:39,  7.87it/s, loss=0.0462]

Epoch 2 | Batch 1400/3125 | Loss: 0.1238

Epoch 2/30:  46%|████▋     | 1450/3125 [03:03<03:54,  7.14it/s, loss=0.148]

Epoch 2 | Batch 1450/3125 | Loss: 0.1479

Epoch 2/30:  48%|████▊     | 1500/3125 [03:09<03:17,  8.24it/s, loss=0.03]

Epoch 2 | Batch 1500/3125 | Loss: 0.0300

Epoch 2/30:  50%|████▉     | 1550/3125 [03:16<03:15,  8.07it/s, loss=0.133]

Epoch 2 | Batch 1550/3125 | Loss: 0.1330

Epoch 2/30:  51%|█████▏    | 1602/3125 [03:22<03:13,  7.86it/s, loss=0.157]

Epoch 2 | Batch 1600/3125 | Loss: 0.0806

Epoch 2/30:  53%|█████▎    | 1650/3125 [03:29<03:16,  7.51it/s, loss=0.0427]

Epoch 2 | Batch 1650/3125 | Loss: 0.0427

Epoch 2/30:  54%|█████▍    | 1702/3125 [03:35<02:59,  7.91it/s, loss=0.166]

Epoch 2 | Batch 1700/3125 | Loss: 0.1251

Epoch 2/30:  56%|█████▌    | 1750/3125 [03:42<02:56,  7.78it/s, loss=0.121]

Epoch 2 | Batch 1750/3125 | Loss: 0.1205

Epoch 2/30:  58%|█████▊    | 1802/3125 [03:48<02:46,  7.94it/s, loss=0.111]

Epoch 2 | Batch 1800/3125 | Loss: 0.1060

Epoch 2/30:  59%|█████▉    | 1850/3125 [03:54<02:49,  7.53it/s, loss=0.0581]

Epoch 2 | Batch 1850/3125 | Loss: 0.0581

Epoch 2/30:  61%|██████    | 1900/3125 [04:00<02:30,  8.11it/s, loss=0.0762]

Epoch 2 | Batch 1900/3125 | Loss: 0.0762

Epoch 2/30:  62%|██████▏   | 1952/3125 [04:07<02:27,  7.95it/s, loss=0.0492]

Epoch 2 | Batch 1950/3125 | Loss: 0.0959

Epoch 2/30:  64%|██████▍   | 2002/3125 [04:13<02:17,  8.14it/s, loss=0.119]

Epoch 2 | Batch 2000/3125 | Loss: 0.1135

Epoch 2/30:  66%|██████▌   | 2052/3125 [04:20<02:14,  7.97it/s, loss=0.029]

Epoch 2 | Batch 2050/3125 | Loss: 0.0341

Epoch 2/30:  67%|██████▋   | 2102/3125 [04:26<02:09,  7.91it/s, loss=0.0968]

Epoch 2 | Batch 2100/3125 | Loss: 0.0429

Epoch 2/30:  69%|██████▉   | 2152/3125 [04:32<01:59,  8.17it/s, loss=0.0762]

Epoch 2 | Batch 2150/3125 | Loss: 0.0634

Epoch 2/30:  70%|███████   | 2202/3125 [04:39<01:56,  7.89it/s, loss=0.0879]

Epoch 2 | Batch 2200/3125 | Loss: 0.0321

Epoch 2/30:  72%|███████▏  | 2252/3125 [04:45<01:55,  7.57it/s, loss=0.101]

Epoch 2 | Batch 2250/3125 | Loss: 0.1078

Epoch 2/30:  74%|███████▎  | 2300/3125 [04:52<01:48,  7.61it/s, loss=0.0834]

Epoch 2 | Batch 2300/3125 | Loss: 0.0834

Epoch 2/30:  75%|███████▌  | 2352/3125 [04:58<01:36,  8.04it/s, loss=0.0606]

Epoch 2 | Batch 2350/3125 | Loss: 0.1167

Epoch 2/30:  77%|███████▋  | 2402/3125 [05:05<01:29,  8.06it/s, loss=0.172]

Epoch 2 | Batch 2400/3125 | Loss: 0.0330

Epoch 2/30:  78%|███████▊  | 2452/3125 [05:11<01:22,  8.11it/s, loss=0.0898]

Epoch 2 | Batch 2450/3125 | Loss: 0.0848

Epoch 2/30:  80%|████████  | 2500/3125 [05:17<01:16,  8.15it/s, loss=0.082]

Epoch 2 | Batch 2500/3125 | Loss: 0.0820

Epoch 2/30:  82%|████████▏ | 2551/3125 [05:23<01:12,  7.96it/s, loss=0.066]

Epoch 2 | Batch 2550/3125 | Loss: 0.0853

Epoch 2/30:  83%|████████▎ | 2601/3125 [05:30<01:07,  7.74it/s, loss=0.0925]

Epoch 2 | Batch 2600/3125 | Loss: 0.1163

Epoch 2/30:  85%|████████▍ | 2651/3125 [05:36<00:59,  8.01it/s, loss=0.101]

Epoch 2 | Batch 2650/3125 | Loss: 0.0611

Epoch 2/30:  86%|████████▋ | 2701/3125 [05:43<00:54,  7.76it/s, loss=0.0981]

Epoch 2 | Batch 2700/3125 | Loss: 0.0969

Epoch 2/30:  88%|████████▊ | 2752/3125 [05:49<00:52,  7.16it/s, loss=0.0968]

Epoch 2 | Batch 2750/3125 | Loss: 0.1412

Epoch 2/30:  90%|████████▉ | 2801/3125 [05:56<00:41,  7.72it/s, loss=0.0858]

Epoch 2 | Batch 2800/3125 | Loss: 0.0495

Epoch 2/30:  91%|█████████▏| 2852/3125 [06:02<00:37,  7.29it/s, loss=0.0583]

Epoch 2 | Batch 2850/3125 | Loss: 0.0693

Epoch 2/30:  93%|█████████▎| 2902/3125 [06:09<00:27,  8.01it/s, loss=0.0211]

Epoch 2 | Batch 2900/3125 | Loss: 0.1349

Epoch 2/30:  94%|█████████▍| 2951/3125 [06:15<00:22,  7.68it/s, loss=0.125]

Epoch 2 | Batch 2950/3125 | Loss: 0.0927

Epoch 2/30:  96%|█████████▌| 3002/3125 [06:22<00:15,  7.78it/s, loss=0.0648]

Epoch 2 | Batch 3000/3125 | Loss: 0.0996

Epoch 2/30:  98%|█████████▊| 3051/3125 [06:28<00:10,  7.20it/s, loss=0.0606]

Epoch 2 | Batch 3050/3125 | Loss: 0.0863

Epoch 2/30:  99%|█████████▉| 3100/3125 [06:35<00:03,  7.10it/s, loss=0.118]

Epoch 2 | Batch 3100/3125 | Loss: 0.1181

Epoch 2/30: 100%|██████████| 3125/3125 [06:38<00:00,  7.85it/s, loss=0.179]

Epoch [2/30] - Avg Loss: 0.0950

Epoch 3/30:   0%|          | 1/3125 [00:00<17:54,  2.91it/s, loss=0.0738]

Epoch 3 | Batch 0/3125 | Loss: 0.1209

Epoch 3/30:   2%|▏         | 51/3125 [00:06<07:17,  7.03it/s, loss=0.111]

Epoch 3 | Batch 50/3125 | Loss: 0.1187

Epoch 3/30:   3%|▎         | 101/3125 [00:13<06:48,  7.40it/s, loss=0.15]

Epoch 3 | Batch 100/3125 | Loss: 0.1453

Epoch 3/30:   5%|▍         | 151/3125 [00:19<06:26,  7.69it/s, loss=0.0613]

Epoch 3 | Batch 150/3125 | Loss: 0.0978

Epoch 3/30:   6%|▋         | 201/3125 [00:26<08:30,  5.73it/s, loss=0.188]

Epoch 3 | Batch 200/3125 | Loss: 0.0937

Epoch 3/30:   8%|▊         | 251/3125 [00:32<06:04,  7.89it/s, loss=0.0298]

Epoch 3 | Batch 250/3125 | Loss: 0.0399

Epoch 3/30:  10%|▉         | 301/3125 [00:39<06:00,  7.83it/s, loss=0.0423]

Epoch 3 | Batch 300/3125 | Loss: 0.1506

Epoch 3/30:  11%|█         | 351/3125 [00:45<06:05,  7.58it/s, loss=0.0497]

Epoch 3 | Batch 350/3125 | Loss: 0.1203

Epoch 3/30:  13%|█▎        | 401/3125 [00:52<05:55,  7.67it/s, loss=0.0487]

Epoch 3 | Batch 400/3125 | Loss: 0.1500

Epoch 3/30:  14%|█▍        | 451/3125 [00:58<05:46,  7.71it/s, loss=0.118]

Epoch 3 | Batch 450/3125 | Loss: 0.0663

Epoch 3/30:  16%|█▌        | 502/3125 [01:05<05:37,  7.78it/s, loss=0.0523]

Epoch 3 | Batch 500/3125 | Loss: 0.0587

Epoch 3/30:  18%|█▊        | 550/3125 [01:11<05:18,  8.10it/s, loss=0.0485]

Epoch 3 | Batch 550/3125 | Loss: 0.0485

Epoch 3/30:  19%|█▉        | 601/3125 [01:18<05:16,  7.98it/s, loss=0.115]

Epoch 3 | Batch 600/3125 | Loss: 0.0822

Epoch 3/30:  21%|██        | 651/3125 [01:24<05:14,  7.85it/s, loss=0.0688]

Epoch 3 | Batch 650/3125 | Loss: 0.1081

Epoch 3/30:  22%|██▏       | 701/3125 [01:30<05:10,  7.81it/s, loss=0.0891]

Epoch 3 | Batch 700/3125 | Loss: 0.1154

Epoch 3/30:  24%|██▍       | 751/3125 [01:37<04:55,  8.04it/s, loss=0.114]

Epoch 3 | Batch 750/3125 | Loss: 0.1263

Epoch 3/30:  26%|██▌       | 801/3125 [01:43<04:54,  7.89it/s, loss=0.0934]

Epoch 3 | Batch 800/3125 | Loss: 0.0798

Epoch 3/30:  27%|██▋       | 851/3125 [01:50<05:05,  7.45it/s, loss=0.0879]

Epoch 3 | Batch 850/3125 | Loss: 0.1531

Epoch 3/30:  29%|██▉       | 901/3125 [01:56<04:32,  8.16it/s, loss=0.12]

Epoch 3 | Batch 900/3125 | Loss: 0.1136

Epoch 3/30:  30%|███       | 951/3125 [02:02<04:40,  7.75it/s, loss=0.154]

Epoch 3 | Batch 950/3125 | Loss: 0.1288

Epoch 3/30:  32%|███▏      | 1001/3125 [02:09<04:28,  7.92it/s, loss=0.158]

Epoch 3 | Batch 1000/3125 | Loss: 0.0609

Epoch 3/30:  34%|███▎      | 1051/3125 [02:15<04:45,  7.27it/s, loss=0.0557]

Epoch 3 | Batch 1050/3125 | Loss: 0.1156

Epoch 3/30:  35%|███▌      | 1101/3125 [02:22<04:07,  8.17it/s, loss=0.0526]

Epoch 3 | Batch 1100/3125 | Loss: 0.0518

Epoch 3/30:  37%|███▋      | 1151/3125 [02:28<04:07,  7.96it/s, loss=0.0612]

Epoch 3 | Batch 1150/3125 | Loss: 0.0657

Epoch 3/30:  38%|███▊      | 1201/3125 [02:34<03:55,  8.18it/s, loss=0.0946]

Epoch 3 | Batch 1200/3125 | Loss: 0.0775

Epoch 3/30:  40%|████      | 1251/3125 [02:40<04:02,  7.73it/s, loss=0.0899]

Epoch 3 | Batch 1250/3125 | Loss: 0.0756

Epoch 3/30:  42%|████▏     | 1301/3125 [02:47<03:59,  7.61it/s, loss=0.0583]

Epoch 3 | Batch 1300/3125 | Loss: 0.0755

Epoch 3/30:  43%|████▎     | 1351/3125 [02:53<03:38,  8.12it/s, loss=0.124]

Epoch 3 | Batch 1350/3125 | Loss: 0.0473

Epoch 3/30:  45%|████▍     | 1401/3125 [03:00<03:42,  7.73it/s, loss=0.0466]

Epoch 3 | Batch 1400/3125 | Loss: 0.1538

Epoch 3/30:  46%|████▋     | 1451/3125 [03:06<03:27,  8.07it/s, loss=0.108]

Epoch 3 | Batch 1450/3125 | Loss: 0.0918

Epoch 3/30:  48%|████▊     | 1501/3125 [03:12<03:33,  7.62it/s, loss=0.0755]

Epoch 3 | Batch 1500/3125 | Loss: 0.0654

Epoch 3/30:  50%|████▉     | 1551/3125 [03:19<03:17,  7.98it/s, loss=0.121]

Epoch 3 | Batch 1550/3125 | Loss: 0.0941

Epoch 3/30:  51%|█████     | 1601/3125 [03:25<03:13,  7.88it/s, loss=0.135]

Epoch 3 | Batch 1600/3125 | Loss: 0.1681

Epoch 3/30:  53%|█████▎    | 1651/3125 [03:31<03:00,  8.16it/s, loss=0.0624]

Epoch 3 | Batch 1650/3125 | Loss: 0.0864

Epoch 3/30:  54%|█████▍    | 1701/3125 [03:38<02:56,  8.07it/s, loss=0.0931]

Epoch 3 | Batch 1700/3125 | Loss: 0.1352

Epoch 3/30:  56%|█████▌    | 1751/3125 [03:44<02:49,  8.12it/s, loss=0.0535]

Epoch 3 | Batch 1750/3125 | Loss: 0.1017

Epoch 3/30:  58%|█████▊    | 1801/3125 [03:51<02:42,  8.15it/s, loss=0.0568]

Epoch 3 | Batch 1800/3125 | Loss: 0.0535

Epoch 3/30:  59%|█████▉    | 1851/3125 [03:57<02:31,  8.39it/s, loss=0.121]

Epoch 3 | Batch 1850/3125 | Loss: 0.0475

Epoch 3/30:  61%|██████    | 1901/3125 [04:03<02:47,  7.32it/s, loss=0.0658]

Epoch 3 | Batch 1900/3125 | Loss: 0.0673

Epoch 3/30:  62%|██████▏   | 1951/3125 [04:10<02:31,  7.76it/s, loss=0.0625]

Epoch 3 | Batch 1950/3125 | Loss: 0.1317

Epoch 3/30:  64%|██████▍   | 2001/3125 [04:16<02:21,  7.95it/s, loss=0.081]

Epoch 3 | Batch 2000/3125 | Loss: 0.1302

Epoch 3/30:  66%|██████▌   | 2051/3125 [04:23<02:18,  7.77it/s, loss=0.0271]

Epoch 3 | Batch 2050/3125 | Loss: 0.0705

Epoch 3/30:  67%|██████▋   | 2101/3125 [04:29<02:15,  7.57it/s, loss=0.0481]

Epoch 3 | Batch 2100/3125 | Loss: 0.0432

Epoch 3/30:  69%|██████▉   | 2151/3125 [04:36<02:06,  7.70it/s, loss=0.0784]

Epoch 3 | Batch 2150/3125 | Loss: 0.0330

Epoch 3/30:  70%|███████   | 2201/3125 [04:43<02:03,  7.51it/s, loss=0.0364]

Epoch 3 | Batch 2200/3125 | Loss: 0.0641

Epoch 3/30:  72%|███████▏  | 2251/3125 [04:49<02:05,  6.97it/s, loss=0.0502]

Epoch 3 | Batch 2250/3125 | Loss: 0.0669

Epoch 3/30:  74%|███████▎  | 2301/3125 [04:56<01:56,  7.06it/s, loss=0.0902]

Epoch 3 | Batch 2300/3125 | Loss: 0.0530

Epoch 3/30:  75%|███████▌  | 2351/3125 [05:02<01:34,  8.20it/s, loss=0.0481]

Epoch 3 | Batch 2350/3125 | Loss: 0.0749

Epoch 3/30:  77%|███████▋  | 2401/3125 [05:09<01:38,  7.35it/s, loss=0.125]

Epoch 3 | Batch 2400/3125 | Loss: 0.0893

Epoch 3/30:  78%|███████▊  | 2451/3125 [05:15<01:32,  7.32it/s, loss=0.119]

Epoch 3 | Batch 2450/3125 | Loss: 0.1316

Epoch 3/30:  80%|████████  | 2501/3125 [05:22<01:20,  7.76it/s, loss=0.104]

Epoch 3 | Batch 2500/3125 | Loss: 0.1327

Epoch 3/30:  82%|████████▏ | 2551/3125 [05:29<01:21,  7.08it/s, loss=0.0734]

Epoch 3 | Batch 2550/3125 | Loss: 0.0343

Epoch 3/30:  83%|████████▎ | 2601/3125 [05:35<01:09,  7.58it/s, loss=0.0927]

Epoch 3 | Batch 2600/3125 | Loss: 0.0424

Epoch 3/30:  85%|████████▍ | 2651/3125 [05:42<01:02,  7.63it/s, loss=0.0288]

Epoch 3 | Batch 2650/3125 | Loss: 0.1682

Epoch 3/30:  86%|████████▋ | 2701/3125 [05:48<00:53,  7.88it/s, loss=0.0364]

Epoch 3 | Batch 2700/3125 | Loss: 0.0737

Epoch 3/30:  88%|████████▊ | 2751/3125 [05:55<00:50,  7.42it/s, loss=0.107]

Epoch 3 | Batch 2750/3125 | Loss: 0.0718

Epoch 3/30:  90%|████████▉ | 2802/3125 [06:01<00:38,  8.30it/s, loss=0.0602]

Epoch 3 | Batch 2800/3125 | Loss: 0.1003

Epoch 3/30:  91%|█████████ | 2850/3125 [06:07<00:33,  8.11it/s, loss=0.0887]

Epoch 3 | Batch 2850/3125 | Loss: 0.0887

Epoch 3/30:  93%|█████████▎| 2900/3125 [06:14<00:32,  6.94it/s, loss=0.0657]

Epoch 3 | Batch 2900/3125 | Loss: 0.0657

Epoch 3/30:  94%|█████████▍| 2950/3125 [06:21<00:22,  7.81it/s, loss=0.0981]

Epoch 3 | Batch 2950/3125 | Loss: 0.0981

Epoch 3/30:  96%|█████████▌| 3002/3125 [06:28<00:15,  7.73it/s, loss=0.053]

Epoch 3 | Batch 3000/3125 | Loss: 0.0557

Epoch 3/30:  98%|█████████▊| 3050/3125 [06:34<00:09,  7.71it/s, loss=0.0514]

Epoch 3 | Batch 3050/3125 | Loss: 0.0514

Epoch 3/30:  99%|█████████▉| 3102/3125 [06:41<00:02,  7.81it/s, loss=0.126]

Epoch 3 | Batch 3100/3125 | Loss: 0.1421

Epoch 3/30: 100%|██████████| 3125/3125 [06:44<00:00,  7.73it/s, loss=0.0832]

Epoch [3/30] - Avg Loss: 0.0820

Epoch 4/30:   0%|          | 1/3125 [00:00<15:41,  3.32it/s, loss=0.0744]

Epoch 4 | Batch 0/3125 | Loss: 0.0515

Epoch 4/30:   2%|▏         | 51/3125 [00:06<06:03,  8.45it/s, loss=0.0267]

Epoch 4 | Batch 50/3125 | Loss: 0.0619

Epoch 4/30:   3%|▎         | 101/3125 [00:13<06:03,  8.32it/s, loss=0.0475]

Epoch 4 | Batch 100/3125 | Loss: 0.0867

Epoch 4/30:   5%|▍         | 151/3125 [00:19<06:02,  8.21it/s, loss=0.0923]

Epoch 4 | Batch 150/3125 | Loss: 0.1305

Epoch 4/30:   6%|▋         | 201/3125 [00:25<05:55,  8.23it/s, loss=0.0608]

Epoch 4 | Batch 200/3125 | Loss: 0.0820

Epoch 4/30:   8%|▊         | 251/3125 [00:31<05:55,  8.09it/s, loss=0.0449]

Epoch 4 | Batch 250/3125 | Loss: 0.0221

Epoch 4/30:  10%|▉         | 301/3125 [00:38<06:29,  7.26it/s, loss=0.0689]

Epoch 4 | Batch 300/3125 | Loss: 0.0278

Epoch 4/30:  11%|█         | 351/3125 [00:44<06:08,  7.52it/s, loss=0.057]

Epoch 4 | Batch 350/3125 | Loss: 0.0493

Epoch 4/30:  13%|█▎        | 401/3125 [00:51<05:52,  7.72it/s, loss=0.0531]

Epoch 4 | Batch 400/3125 | Loss: 0.0772

Epoch 4/30:  14%|█▍        | 451/3125 [00:57<05:51,  7.62it/s, loss=0.0453]

Epoch 4 | Batch 450/3125 | Loss: 0.0950

Epoch 4/30:  16%|█▌        | 501/3125 [01:03<05:19,  8.22it/s, loss=0.065]

Epoch 4 | Batch 500/3125 | Loss: 0.0312

Epoch 4/30:  18%|█▊        | 550/3125 [01:10<06:36,  6.50it/s, loss=0.0624]

Epoch 4 | Batch 550/3125 | Loss: 0.0624

Epoch 4/30:  19%|█▉        | 602/3125 [01:17<05:23,  7.81it/s, loss=0.11]

Epoch 4 | Batch 600/3125 | Loss: 0.0934

Epoch 4/30:  21%|██        | 651/3125 [01:23<05:23,  7.64it/s, loss=0.0514]

Epoch 4 | Batch 650/3125 | Loss: 0.0770

Epoch 4/30:  22%|██▏       | 701/3125 [01:30<05:08,  7.86it/s, loss=0.0586]

Epoch 4 | Batch 700/3125 | Loss: 0.0530

Epoch 4/30:  24%|██▍       | 751/3125 [01:36<05:01,  7.86it/s, loss=0.0457]

Epoch 4 | Batch 750/3125 | Loss: 0.1281

Epoch 4/30:  26%|██▌       | 801/3125 [01:42<04:50,  8.00it/s, loss=0.0845]

Epoch 4 | Batch 800/3125 | Loss: 0.1269

Epoch 4/30:  27%|██▋       | 851/3125 [01:48<04:38,  8.17it/s, loss=0.0932]

Epoch 4 | Batch 850/3125 | Loss: 0.0655

Epoch 4/30:  29%|██▉       | 901/3125 [01:55<04:59,  7.42it/s, loss=0.0688]

Epoch 4 | Batch 900/3125 | Loss: 0.0634

Epoch 4/30:  30%|███       | 951/3125 [02:01<04:35,  7.89it/s, loss=0.0898]

Epoch 4 | Batch 950/3125 | Loss: 0.0804

Epoch 4/30:  32%|███▏      | 1001/3125 [02:08<04:23,  8.05it/s, loss=0.0792]

Epoch 4 | Batch 1000/3125 | Loss: 0.0359

Epoch 4/30:  34%|███▎      | 1051/3125 [02:14<04:23,  7.88it/s, loss=0.0629]

Epoch 4 | Batch 1050/3125 | Loss: 0.0707

Epoch 4/30:  35%|███▌      | 1101/3125 [02:20<04:21,  7.75it/s, loss=0.0595]

Epoch 4 | Batch 1100/3125 | Loss: 0.1134

Epoch 4/30:  37%|███▋      | 1151/3125 [02:27<04:15,  7.72it/s, loss=0.0877]

Epoch 4 | Batch 1150/3125 | Loss: 0.0436

Epoch 4/30:  38%|███▊      | 1201/3125 [02:33<03:52,  8.28it/s, loss=0.099]

Epoch 4 | Batch 1200/3125 | Loss: 0.0731

Epoch 4/30:  40%|████      | 1251/3125 [02:39<04:11,  7.44it/s, loss=0.107]

Epoch 4 | Batch 1250/3125 | Loss: 0.0586

Epoch 4/30:  42%|████▏     | 1301/3125 [02:46<03:52,  7.85it/s, loss=0.0903]

Epoch 4 | Batch 1300/3125 | Loss: 0.0592

Epoch 4/30:  43%|████▎     | 1351/3125 [02:52<03:35,  8.22it/s, loss=0.0607]

Epoch 4 | Batch 1350/3125 | Loss: 0.0628

Epoch 4/30:  45%|████▍     | 1401/3125 [02:58<03:32,  8.11it/s, loss=0.0722]

Epoch 4 | Batch 1400/3125 | Loss: 0.0938

Epoch 4/30:  46%|████▋     | 1451/3125 [03:04<03:19,  8.38it/s, loss=0.071]

Epoch 4 | Batch 1450/3125 | Loss: 0.0714

Epoch 4/30:  48%|████▊     | 1501/3125 [03:11<03:32,  7.63it/s, loss=0.106]

Epoch 4 | Batch 1500/3125 | Loss: 0.1208

Epoch 4/30:  50%|████▉     | 1552/3125 [03:17<03:06,  8.41it/s, loss=0.0553]

Epoch 4 | Batch 1550/3125 | Loss: 0.0591

Epoch 4/30:  51%|█████▏    | 1602/3125 [03:23<03:05,  8.23it/s, loss=0.0433]

Epoch 4 | Batch 1600/3125 | Loss: 0.0713

Epoch 4/30:  53%|█████▎    | 1651/3125 [03:29<03:06,  7.91it/s, loss=0.0804]

Epoch 4 | Batch 1650/3125 | Loss: 0.0698

Epoch 4/30:  54%|█████▍    | 1702/3125 [03:36<02:50,  8.34it/s, loss=0.0718]

Epoch 4 | Batch 1700/3125 | Loss: 0.1212

Epoch 4/30:  56%|█████▌    | 1752/3125 [03:42<02:52,  7.96it/s, loss=0.0656]

Epoch 4 | Batch 1750/3125 | Loss: 0.0740

Epoch 4/30:  58%|█████▊    | 1802/3125 [03:48<02:47,  7.92it/s, loss=0.0273]

Epoch 4 | Batch 1800/3125 | Loss: 0.0395

Epoch 4/30:  59%|█████▉    | 1852/3125 [03:55<02:34,  8.25it/s, loss=0.0538]

Epoch 4 | Batch 1850/3125 | Loss: 0.0748

Epoch 4/30:  61%|██████    | 1902/3125 [04:01<02:28,  8.24it/s, loss=0.0808]

Epoch 4 | Batch 1900/3125 | Loss: 0.0440

Epoch 4/30:  62%|██████▏   | 1952/3125 [04:07<02:24,  8.11it/s, loss=0.0887]

Epoch 4 | Batch 1950/3125 | Loss: 0.0594

Epoch 4/30:  64%|██████▍   | 2000/3125 [04:13<02:18,  8.09it/s, loss=0.0628]

Epoch 4 | Batch 2000/3125 | Loss: 0.0628

Epoch 4/30:  66%|██████▌   | 2052/3125 [04:20<02:12,  8.09it/s, loss=0.171]

Epoch 4 | Batch 2050/3125 | Loss: 0.1168

Epoch 4/30:  67%|██████▋   | 2102/3125 [04:26<02:01,  8.39it/s, loss=0.0932]

Epoch 4 | Batch 2100/3125 | Loss: 0.1367

Epoch 4/30:  69%|██████▉   | 2152/3125 [04:32<01:56,  8.32it/s, loss=0.127]

Epoch 4 | Batch 2150/3125 | Loss: 0.0455

Epoch 4/30:  70%|███████   | 2202/3125 [04:38<01:55,  7.96it/s, loss=0.0406]

Epoch 4 | Batch 2200/3125 | Loss: 0.0483

Epoch 4/30:  72%|███████▏  | 2252/3125 [04:45<01:51,  7.82it/s, loss=0.167]

Epoch 4 | Batch 2250/3125 | Loss: 0.1494

Epoch 4/30:  74%|███████▎  | 2300/3125 [04:51<01:47,  7.65it/s, loss=0.101]

Epoch 4 | Batch 2300/3125 | Loss: 0.1005

Epoch 4/30:  75%|███████▌  | 2352/3125 [04:58<01:32,  8.34it/s, loss=0.0624]

Epoch 4 | Batch 2350/3125 | Loss: 0.0408

Epoch 4/30:  77%|███████▋  | 2402/3125 [05:04<01:31,  7.93it/s, loss=0.104]

Epoch 4 | Batch 2400/3125 | Loss: 0.0683

Epoch 4/30:  78%|███████▊  | 2452/3125 [05:10<01:30,  7.47it/s, loss=0.105]

Epoch 4 | Batch 2450/3125 | Loss: 0.0610

Epoch 4/30:  80%|████████  | 2502/3125 [05:16<01:13,  8.48it/s, loss=0.0342]

Epoch 4 | Batch 2500/3125 | Loss: 0.0427

Epoch 4/30:  82%|████████▏ | 2551/3125 [05:23<01:12,  7.89it/s, loss=0.0606]

Epoch 4 | Batch 2550/3125 | Loss: 0.1036

Epoch 4/30:  83%|████████▎ | 2601/3125 [05:29<01:04,  8.18it/s, loss=0.1]

Epoch 4 | Batch 2600/3125 | Loss: 0.0473

Epoch 4/30:  85%|████████▍ | 2651/3125 [05:35<01:00,  7.82it/s, loss=0.0106]

Epoch 4 | Batch 2650/3125 | Loss: 0.0818

Epoch 4/30:  86%|████████▋ | 2701/3125 [05:42<00:55,  7.70it/s, loss=0.025]

Epoch 4 | Batch 2700/3125 | Loss: 0.0767

Epoch 4/30:  88%|████████▊ | 2751/3125 [05:48<00:45,  8.19it/s, loss=0.0672]

Epoch 4 | Batch 2750/3125 | Loss: 0.0862

Epoch 4/30:  90%|████████▉ | 2802/3125 [05:54<00:41,  7.71it/s, loss=0.0969]

Epoch 4 | Batch 2800/3125 | Loss: 0.0669

Epoch 4/30:  91%|█████████▏| 2852/3125 [06:00<00:33,  8.22it/s, loss=0.0937]

Epoch 4 | Batch 2850/3125 | Loss: 0.0656

Epoch 4/30:  93%|█████████▎| 2902/3125 [06:07<00:27,  8.26it/s, loss=0.0414]

Epoch 4 | Batch 2900/3125 | Loss: 0.0840

Epoch 4/30:  94%|█████████▍| 2952/3125 [06:13<00:19,  8.75it/s, loss=0.0854]

Epoch 4 | Batch 2950/3125 | Loss: 0.1151

Epoch 4/30:  96%|█████████▌| 3002/3125 [06:19<00:15,  7.87it/s, loss=0.0374]

Epoch 4 | Batch 3000/3125 | Loss: 0.0522

Epoch 4/30:  98%|█████████▊| 3051/3125 [06:25<00:08,  8.49it/s, loss=0.0652]

Epoch 4 | Batch 3050/3125 | Loss: 0.0587

Epoch 4/30:  99%|█████████▉| 3102/3125 [06:32<00:02,  8.05it/s, loss=0.0666]

Epoch 4 | Batch 3100/3125 | Loss: 0.0636

Epoch 4/30: 100%|██████████| 3125/3125 [06:35<00:00,  7.91it/s, loss=0.0811]

Epoch [4/30] - Avg Loss: 0.0731

Epoch 5/30:   0%|          | 1/3125 [00:00<15:00,  3.47it/s, loss=0.0793]

Epoch 5 | Batch 0/3125 | Loss: 0.1138

Epoch 5/30:   2%|▏         | 51/3125 [00:06<06:44,  7.60it/s, loss=0.0562]

Epoch 5 | Batch 50/3125 | Loss: 0.0313

Epoch 5/30:   3%|▎         | 101/3125 [00:12<06:08,  8.20it/s, loss=0.0472]

Epoch 5 | Batch 100/3125 | Loss: 0.0873

Epoch 5/30:   5%|▍         | 151/3125 [00:19<06:27,  7.67it/s, loss=0.0927]

Epoch 5 | Batch 150/3125 | Loss: 0.0999

Epoch 5/30:   6%|▋         | 201/3125 [00:25<05:34,  8.75it/s, loss=0.0622]

Epoch 5 | Batch 200/3125 | Loss: 0.0628

Epoch 5/30:   8%|▊         | 251/3125 [00:31<05:38,  8.50it/s, loss=0.0504]

Epoch 5 | Batch 250/3125 | Loss: 0.0702

Epoch 5/30:  10%|▉         | 301/3125 [00:37<05:43,  8.21it/s, loss=0.0499]

Epoch 5 | Batch 300/3125 | Loss: 0.0703

Epoch 5/30:  11%|█         | 351/3125 [00:43<05:39,  8.17it/s, loss=0.0731]

Epoch 5 | Batch 350/3125 | Loss: 0.0380

Epoch 5/30:  13%|█▎        | 401/3125 [00:50<06:02,  7.52it/s, loss=0.0569]

Epoch 5 | Batch 400/3125 | Loss: 0.0511

Epoch 5/30:  14%|█▍        | 451/3125 [00:56<05:30,  8.09it/s, loss=0.082]

Epoch 5 | Batch 450/3125 | Loss: 0.0439

Epoch 5/30:  16%|█▌        | 501/3125 [01:02<05:21,  8.16it/s, loss=0.0961]

Epoch 5 | Batch 500/3125 | Loss: 0.0687

Epoch 5/30:  18%|█▊        | 551/3125 [01:09<05:30,  7.79it/s, loss=0.0579]

Epoch 5 | Batch 550/3125 | Loss: 0.0308

Epoch 5/30:  19%|█▉        | 601/3125 [01:15<05:05,  8.27it/s, loss=0.0332]

Epoch 5 | Batch 600/3125 | Loss: 0.0482

Epoch 5/30:  21%|██        | 651/3125 [01:21<05:28,  7.52it/s, loss=0.0313]

Epoch 5 | Batch 650/3125 | Loss: 0.0761

Epoch 5/30:  22%|██▏       | 701/3125 [01:28<05:05,  7.94it/s, loss=0.0529]

Epoch 5 | Batch 700/3125 | Loss: 0.1200

Epoch 5/30:  24%|██▍       | 751/3125 [01:34<04:58,  7.94it/s, loss=0.0675]

Epoch 5 | Batch 750/3125 | Loss: 0.0488

Epoch 5/30:  26%|██▌       | 801/3125 [01:40<04:54,  7.89it/s, loss=0.0465]

Epoch 5 | Batch 800/3125 | Loss: 0.0503

Epoch 5/30:  27%|██▋       | 851/3125 [01:46<04:51,  7.81it/s, loss=0.0418]

Epoch 5 | Batch 850/3125 | Loss: 0.0365

Epoch 5/30:  29%|██▉       | 901/3125 [01:52<04:49,  7.68it/s, loss=0.0273]

Epoch 5 | Batch 900/3125 | Loss: 0.0559

Epoch 5/30:  30%|███       | 952/3125 [01:59<04:25,  8.19it/s, loss=0.0284]

Epoch 5 | Batch 950/3125 | Loss: 0.0483

Epoch 5/30:  32%|███▏      | 1001/3125 [02:05<04:20,  8.15it/s, loss=0.0839]

Epoch 5 | Batch 1000/3125 | Loss: 0.0736

Epoch 5/30:  34%|███▎      | 1051/3125 [02:11<04:22,  7.89it/s, loss=0.0411]

Epoch 5 | Batch 1050/3125 | Loss: 0.0320

Epoch 5/30:  35%|███▌      | 1101/3125 [02:17<04:13,  7.99it/s, loss=0.0567]

Epoch 5 | Batch 1100/3125 | Loss: 0.0497

Epoch 5/30:  37%|███▋      | 1151/3125 [02:24<04:10,  7.87it/s, loss=0.0551]

Epoch 5 | Batch 1150/3125 | Loss: 0.1244

Epoch 5/30:  38%|███▊      | 1201/3125 [02:30<04:01,  7.98it/s, loss=0.0615]

Epoch 5 | Batch 1200/3125 | Loss: 0.1169

Epoch 5/30:  40%|████      | 1251/3125 [02:36<03:53,  8.02it/s, loss=0.0674]

Epoch 5 | Batch 1250/3125 | Loss: 0.1363

Epoch 5/30:  42%|████▏     | 1301/3125 [02:42<03:37,  8.40it/s, loss=0.117]

Epoch 5 | Batch 1300/3125 | Loss: 0.0305

Epoch 5/30:  43%|████▎     | 1352/3125 [02:48<03:59,  7.40it/s, loss=0.0424]

Epoch 5 | Batch 1350/3125 | Loss: 0.0638

Epoch 5/30:  45%|████▍     | 1402/3125 [02:55<03:56,  7.28it/s, loss=0.105]

Epoch 5 | Batch 1400/3125 | Loss: 0.0523

Epoch 5/30:  46%|████▋     | 1452/3125 [03:01<03:16,  8.50it/s, loss=0.0619]

Epoch 5 | Batch 1450/3125 | Loss: 0.0780

Epoch 5/30:  48%|████▊     | 1502/3125 [03:08<03:28,  7.77it/s, loss=0.0536]

Epoch 5 | Batch 1500/3125 | Loss: 0.0488

Epoch 5/30:  50%|████▉     | 1552/3125 [03:14<03:14,  8.07it/s, loss=0.0392]

Epoch 5 | Batch 1550/3125 | Loss: 0.0617

Epoch 5/30:  51%|█████▏    | 1602/3125 [03:20<03:11,  7.96it/s, loss=0.0517]

Epoch 5 | Batch 1600/3125 | Loss: 0.0761

Epoch 5/30:  53%|█████▎    | 1652/3125 [03:27<03:22,  7.27it/s, loss=0.134]

Epoch 5 | Batch 1650/3125 | Loss: 0.0280

Epoch 5/30:  54%|█████▍    | 1702/3125 [03:33<02:52,  8.23it/s, loss=0.066]

Epoch 5 | Batch 1700/3125 | Loss: 0.0385

Epoch 5/30:  56%|█████▌    | 1752/3125 [03:39<02:49,  8.09it/s, loss=0.0231]

Epoch 5 | Batch 1750/3125 | Loss: 0.0495

Epoch 5/30:  58%|█████▊    | 1801/3125 [03:45<02:39,  8.28it/s, loss=0.122]

Epoch 5 | Batch 1800/3125 | Loss: 0.0638

Epoch 5/30:  59%|█████▉    | 1851/3125 [03:52<02:49,  7.52it/s, loss=0.0557]

Epoch 5 | Batch 1850/3125 | Loss: 0.0571

Epoch 5/30:  61%|██████    | 1901/3125 [03:58<02:38,  7.72it/s, loss=0.0701]

Epoch 5 | Batch 1900/3125 | Loss: 0.0329

Epoch 5/30:  62%|██████▏   | 1951/3125 [04:04<02:23,  8.18it/s, loss=0.0708]

Epoch 5 | Batch 1950/3125 | Loss: 0.0429

Epoch 5/30:  64%|██████▍   | 2002/3125 [04:11<02:19,  8.06it/s, loss=0.0778]

Epoch 5 | Batch 2000/3125 | Loss: 0.0721

Epoch 5/30:  66%|██████▌   | 2052/3125 [04:17<02:06,  8.51it/s, loss=0.0692]

Epoch 5 | Batch 2050/3125 | Loss: 0.0493

Epoch 5/30:  67%|██████▋   | 2102/3125 [04:23<02:05,  8.15it/s, loss=0.0432]

Epoch 5 | Batch 2100/3125 | Loss: 0.0574

Epoch 5/30:  69%|██████▉   | 2151/3125 [04:30<02:12,  7.33it/s, loss=0.0506]

Epoch 5 | Batch 2150/3125 | Loss: 0.0601

Epoch 5/30:  70%|███████   | 2201/3125 [04:36<01:56,  7.93it/s, loss=0.0584]

Epoch 5 | Batch 2200/3125 | Loss: 0.0447

Epoch 5/30:  72%|███████▏  | 2251/3125 [04:42<01:49,  7.98it/s, loss=0.0807]

Epoch 5 | Batch 2250/3125 | Loss: 0.0526

Epoch 5/30:  74%|███████▎  | 2301/3125 [04:48<01:38,  8.34it/s, loss=0.0891]

Epoch 5 | Batch 2300/3125 | Loss: 0.0842

Epoch 5/30:  75%|███████▌  | 2351/3125 [04:55<01:30,  8.54it/s, loss=0.0798]

Epoch 5 | Batch 2350/3125 | Loss: 0.0451

Epoch 5/30:  77%|███████▋  | 2401/3125 [05:01<01:30,  8.03it/s, loss=0.0814]

Epoch 5 | Batch 2400/3125 | Loss: 0.0632

Epoch 5/30:  78%|███████▊  | 2451/3125 [05:07<01:32,  7.26it/s, loss=0.101]

Epoch 5 | Batch 2450/3125 | Loss: 0.0698

Epoch 5/30:  80%|████████  | 2501/3125 [05:13<01:17,  8.06it/s, loss=0.0892]

Epoch 5 | Batch 2500/3125 | Loss: 0.1180

Epoch 5/30:  82%|████████▏ | 2551/3125 [05:20<01:12,  7.87it/s, loss=0.0514]

Epoch 5 | Batch 2550/3125 | Loss: 0.0708

Epoch 5/30:  83%|████████▎ | 2602/3125 [05:26<01:06,  7.92it/s, loss=0.12]

Epoch 5 | Batch 2600/3125 | Loss: 0.0502

Epoch 5/30:  85%|████████▍ | 2652/3125 [05:32<01:01,  7.74it/s, loss=0.0488]

Epoch 5 | Batch 2650/3125 | Loss: 0.0434

Epoch 5/30:  86%|████████▋ | 2702/3125 [05:39<00:52,  8.06it/s, loss=0.0539]

Epoch 5 | Batch 2700/3125 | Loss: 0.0806

Epoch 5/30:  88%|████████▊ | 2750/3125 [05:44<00:45,  8.24it/s, loss=0.0525]

Epoch 5 | Batch 2750/3125 | Loss: 0.0525

Epoch 5/30:  90%|████████▉ | 2802/3125 [05:51<00:40,  8.05it/s, loss=0.0608]

Epoch 5 | Batch 2800/3125 | Loss: 0.0571

Epoch 5/30:  91%|█████████ | 2850/3125 [05:57<00:35,  7.80it/s, loss=0.0605]

Epoch 5 | Batch 2850/3125 | Loss: 0.0605

Epoch 5/30:  93%|█████████▎| 2900/3125 [06:03<00:33,  6.72it/s, loss=0.0197]

Epoch 5 | Batch 2900/3125 | Loss: 0.0197

Epoch 5/30:  94%|█████████▍| 2952/3125 [06:10<00:21,  8.12it/s, loss=0.0225]

Epoch 5 | Batch 2950/3125 | Loss: 0.0145

Epoch 5/30:  96%|█████████▌| 3000/3125 [06:16<00:15,  8.05it/s, loss=0.0467]

Epoch 5 | Batch 3000/3125 | Loss: 0.0467

Epoch 5/30:  98%|█████████▊| 3050/3125 [06:22<00:09,  7.92it/s, loss=0.0879]

Epoch 5 | Batch 3050/3125 | Loss: 0.0879

Epoch 5/30:  99%|█████████▉| 3102/3125 [06:29<00:03,  7.49it/s, loss=0.059]

Epoch 5 | Batch 3100/3125 | Loss: 0.0886

Epoch 5/30: 100%|██████████| 3125/3125 [06:32<00:00,  7.97it/s, loss=0.0825]

Epoch [5/30] - Avg Loss: 0.0656

Epoch 6/30:   0%|          | 1/3125 [00:00<14:56,  3.49it/s, loss=0.0218]

Epoch 6 | Batch 0/3125 | Loss: 0.0827

Epoch 6/30:   2%|▏         | 52/3125 [00:06<06:50,  7.49it/s, loss=0.0558]

Epoch 6 | Batch 50/3125 | Loss: 0.0322

Epoch 6/30:   3%|▎         | 100/3125 [00:13<06:51,  7.36it/s, loss=0.0452]

Epoch 6 | Batch 100/3125 | Loss: 0.0452

Epoch 6/30:   5%|▍         | 151/3125 [00:19<05:50,  8.49it/s, loss=0.117]

Epoch 6 | Batch 150/3125 | Loss: 0.0570

Epoch 6/30:   6%|▋         | 201/3125 [00:25<06:34,  7.41it/s, loss=0.052]

Epoch 6 | Batch 200/3125 | Loss: 0.0876

Epoch 6/30:   8%|▊         | 252/3125 [00:32<06:30,  7.36it/s, loss=0.0655]

Epoch 6 | Batch 250/3125 | Loss: 0.0249

Epoch 6/30:  10%|▉         | 302/3125 [00:39<05:54,  7.95it/s, loss=0.0387]

Epoch 6 | Batch 300/3125 | Loss: 0.0335

Epoch 6/30:  11%|█▏        | 352/3125 [00:46<05:47,  7.97it/s, loss=0.011]

Epoch 6 | Batch 350/3125 | Loss: 0.0572

Epoch 6/30:  13%|█▎        | 402/3125 [00:52<05:41,  7.97it/s, loss=0.102]

Epoch 6 | Batch 400/3125 | Loss: 0.0478

Epoch 6/30:  14%|█▍        | 452/3125 [00:58<05:46,  7.72it/s, loss=0.0515]

Epoch 6 | Batch 450/3125 | Loss: 0.0536

Epoch 6/30:  16%|█▌        | 500/3125 [01:05<06:32,  6.69it/s, loss=0.0551]

Epoch 6 | Batch 500/3125 | Loss: 0.0551

Epoch 6/30:  18%|█▊        | 552/3125 [01:12<05:19,  8.06it/s, loss=0.0827]

Epoch 6 | Batch 550/3125 | Loss: 0.0371

Epoch 6/30:  19%|█▉        | 600/3125 [01:18<05:24,  7.79it/s, loss=0.0962]

Epoch 6 | Batch 600/3125 | Loss: 0.0962

Epoch 6/30:  21%|██        | 652/3125 [01:24<05:05,  8.09it/s, loss=0.0617]

Epoch 6 | Batch 650/3125 | Loss: 0.0370

Epoch 6/30:  22%|██▏       | 702/3125 [01:30<04:58,  8.11it/s, loss=0.0644]

Epoch 6 | Batch 700/3125 | Loss: 0.1285

Epoch 6/30:  24%|██▍       | 750/3125 [01:37<05:22,  7.36it/s, loss=0.0417]

Epoch 6 | Batch 750/3125 | Loss: 0.0417

Epoch 6/30:  26%|██▌       | 802/3125 [01:44<04:56,  7.85it/s, loss=0.054]

Epoch 6 | Batch 800/3125 | Loss: 0.0710

Epoch 6/30:  27%|██▋       | 852/3125 [01:50<04:43,  8.01it/s, loss=0.0491]

Epoch 6 | Batch 850/3125 | Loss: 0.0432

Epoch 6/30:  29%|██▉       | 902/3125 [01:56<04:50,  7.66it/s, loss=0.0128]

Epoch 6 | Batch 900/3125 | Loss: 0.0872

Epoch 6/30:  30%|███       | 952/3125 [02:02<04:37,  7.82it/s, loss=0.0454]

Epoch 6 | Batch 950/3125 | Loss: 0.0473

Epoch 6/30:  32%|███▏      | 1002/3125 [02:09<04:59,  7.09it/s, loss=0.0439]

Epoch 6 | Batch 1000/3125 | Loss: 0.0417

Epoch 6/30:  34%|███▎      | 1052/3125 [02:15<04:21,  7.94it/s, loss=0.0445]

Epoch 6 | Batch 1050/3125 | Loss: 0.0905

Epoch 6/30:  35%|███▌      | 1102/3125 [02:22<04:19,  7.78it/s, loss=0.0674]

Epoch 6 | Batch 1100/3125 | Loss: 0.0665

Epoch 6/30:  37%|███▋      | 1150/3125 [02:28<04:22,  7.53it/s, loss=0.0569]

Epoch 6 | Batch 1150/3125 | Loss: 0.0569

Epoch 6/30:  38%|███▊      | 1202/3125 [02:34<04:04,  7.85it/s, loss=0.141]

Epoch 6 | Batch 1200/3125 | Loss: 0.0292

Epoch 6/30:  40%|████      | 1252/3125 [02:41<04:10,  7.49it/s, loss=0.0408]

Epoch 6 | Batch 1250/3125 | Loss: 0.0338

Epoch 6/30:  42%|████▏     | 1302/3125 [02:47<03:54,  7.79it/s, loss=0.0358]

Epoch 6 | Batch 1300/3125 | Loss: 0.0481

Epoch 6/30:  43%|████▎     | 1350/3125 [02:53<03:39,  8.08it/s, loss=0.0409]

Epoch 6 | Batch 1350/3125 | Loss: 0.0409

Epoch 6/30:  45%|████▍     | 1402/3125 [03:00<03:29,  8.22it/s, loss=0.0991]

Epoch 6 | Batch 1400/3125 | Loss: 0.0737

Epoch 6/30:  46%|████▋     | 1452/3125 [03:06<03:20,  8.33it/s, loss=0.144]

Epoch 6 | Batch 1450/3125 | Loss: 0.0605

Epoch 6/30:  48%|████▊     | 1502/3125 [03:12<03:45,  7.21it/s, loss=0.0591]

Epoch 6 | Batch 1500/3125 | Loss: 0.0328

Epoch 6/30:  50%|████▉     | 1552/3125 [03:19<03:14,  8.09it/s, loss=0.0481]

Epoch 6 | Batch 1550/3125 | Loss: 0.0263

Epoch 6/30:  51%|█████▏    | 1602/3125 [03:25<03:19,  7.63it/s, loss=0.0561]

Epoch 6 | Batch 1600/3125 | Loss: 0.0838

Epoch 6/30:  53%|█████▎    | 1652/3125 [03:32<03:11,  7.69it/s, loss=0.116]

Epoch 6 | Batch 1650/3125 | Loss: 0.0333

Epoch 6/30:  54%|█████▍    | 1702/3125 [03:38<03:01,  7.86it/s, loss=0.0291]

Epoch 6 | Batch 1700/3125 | Loss: 0.0261

Epoch 6/30:  56%|█████▌    | 1750/3125 [03:45<03:13,  7.10it/s, loss=0.134]

Epoch 6 | Batch 1750/3125 | Loss: 0.0479

Epoch 6/30:  58%|█████▊    | 1802/3125 [03:51<02:43,  8.09it/s, loss=0.0699]

Epoch 6 | Batch 1800/3125 | Loss: 0.0708

Epoch 6/30:  59%|█████▉    | 1852/3125 [03:58<02:36,  8.14it/s, loss=0.0328]

Epoch 6 | Batch 1850/3125 | Loss: 0.0787

Epoch 6/30:  61%|██████    | 1902/3125 [04:04<02:43,  7.48it/s, loss=0.0229]

Epoch 6 | Batch 1900/3125 | Loss: 0.0507

Epoch 6/30:  62%|██████▏   | 1950/3125 [04:11<02:27,  7.96it/s, loss=0.0501]

Epoch 6 | Batch 1950/3125 | Loss: 0.0501

Epoch 6/30:  64%|██████▍   | 2000/3125 [04:17<02:24,  7.81it/s, loss=0.0576]

Epoch 6 | Batch 2000/3125 | Loss: 0.0576

Epoch 6/30:  66%|██████▌   | 2052/3125 [04:24<02:12,  8.07it/s, loss=0.104]

Epoch 6 | Batch 2050/3125 | Loss: 0.0617

Epoch 6/30:  67%|██████▋   | 2102/3125 [04:30<02:05,  8.18it/s, loss=0.0379]

Epoch 6 | Batch 2100/3125 | Loss: 0.0654

Epoch 6/30:  69%|██████▉   | 2152/3125 [04:37<02:03,  7.88it/s, loss=0.0503]

Epoch 6 | Batch 2150/3125 | Loss: 0.0256

Epoch 6/30:  70%|███████   | 2202/3125 [04:43<01:58,  7.79it/s, loss=0.0443]

Epoch 6 | Batch 2200/3125 | Loss: 0.0477

Epoch 6/30:  72%|███████▏  | 2252/3125 [04:50<01:49,  7.99it/s, loss=0.0473]

Epoch 6 | Batch 2250/3125 | Loss: 0.0589

Epoch 6/30:  74%|███████▎  | 2302/3125 [04:56<01:42,  8.00it/s, loss=0.0891]

Epoch 6 | Batch 2300/3125 | Loss: 0.0463

Epoch 6/30:  75%|███████▌  | 2352/3125 [05:02<01:39,  7.77it/s, loss=0.039]

Epoch 6 | Batch 2350/3125 | Loss: 0.0518

Epoch 6/30:  77%|███████▋  | 2402/3125 [05:09<01:31,  7.90it/s, loss=0.0647]

Epoch 6 | Batch 2400/3125 | Loss: 0.0878

Epoch 6/30:  78%|███████▊  | 2452/3125 [05:15<01:26,  7.76it/s, loss=0.0501]

Epoch 6 | Batch 2450/3125 | Loss: 0.0440

Epoch 6/30:  80%|████████  | 2502/3125 [05:22<01:17,  8.02it/s, loss=0.034]

Epoch 6 | Batch 2500/3125 | Loss: 0.0520

Epoch 6/30:  82%|████████▏ | 2552/3125 [05:28<01:09,  8.22it/s, loss=0.0879]

Epoch 6 | Batch 2550/3125 | Loss: 0.0322

Epoch 6/30:  83%|████████▎ | 2602/3125 [05:34<01:08,  7.60it/s, loss=0.0437]

Epoch 6 | Batch 2600/3125 | Loss: 0.0425

Epoch 6/30:  85%|████████▍ | 2652/3125 [05:40<01:00,  7.87it/s, loss=0.066]

Epoch 6 | Batch 2650/3125 | Loss: 0.0327

Epoch 6/30:  86%|████████▋ | 2700/3125 [05:46<00:54,  7.77it/s, loss=0.051]

Epoch 6 | Batch 2700/3125 | Loss: 0.0510

Epoch 6/30:  88%|████████▊ | 2752/3125 [05:53<00:43,  8.57it/s, loss=0.0338]

Epoch 6 | Batch 2750/3125 | Loss: 0.0643

Epoch 6/30:  90%|████████▉ | 2801/3125 [05:59<00:41,  7.80it/s, loss=0.0441]

Epoch 6 | Batch 2800/3125 | Loss: 0.0811

Epoch 6/30:  91%|█████████ | 2851/3125 [06:06<00:34,  7.98it/s, loss=0.087]

Epoch 6 | Batch 2850/3125 | Loss: 0.0736

Epoch 6/30:  93%|█████████▎| 2901/3125 [06:12<00:28,  7.90it/s, loss=0.0312]

Epoch 6 | Batch 2900/3125 | Loss: 0.0476

Epoch 6/30:  94%|█████████▍| 2951/3125 [06:18<00:22,  7.59it/s, loss=0.0619]

Epoch 6 | Batch 2950/3125 | Loss: 0.1044

Epoch 6/30:  96%|█████████▌| 3001/3125 [06:25<00:15,  7.78it/s, loss=0.0444]

Epoch 6 | Batch 3000/3125 | Loss: 0.0776

Epoch 6/30:  98%|█████████▊| 3051/3125 [06:31<00:10,  7.30it/s, loss=0.0267]

Epoch 6 | Batch 3050/3125 | Loss: 0.0350

Epoch 6/30:  99%|█████████▉| 3101/3125 [06:37<00:03,  7.86it/s, loss=0.0651]

Epoch 6 | Batch 3100/3125 | Loss: 0.0604

Epoch 6/30: 100%|██████████| 3125/3125 [06:41<00:00,  7.79it/s, loss=0.0448]

Epoch [6/30] - Avg Loss: 0.0590

Epoch 7/30:   0%|          | 1/3125 [00:00<14:23,  3.62it/s, loss=0.0832]

Epoch 7 | Batch 0/3125 | Loss: 0.0461

Epoch 7/30:   2%|▏         | 51/3125 [00:06<06:02,  8.48it/s, loss=0.0899]

Epoch 7 | Batch 50/3125 | Loss: 0.0398

Epoch 7/30:   3%|▎         | 101/3125 [00:12<07:20,  6.86it/s, loss=0.0635]

Epoch 7 | Batch 100/3125 | Loss: 0.0635

Epoch 7/30:   5%|▍         | 152/3125 [00:19<05:49,  8.50it/s, loss=0.0726]

Epoch 7 | Batch 150/3125 | Loss: 0.0435

Epoch 7/30:   6%|▋         | 202/3125 [00:25<05:52,  8.30it/s, loss=0.0564]

Epoch 7 | Batch 200/3125 | Loss: 0.0477

Epoch 7/30:   8%|▊         | 250/3125 [00:31<06:00,  7.99it/s, loss=0.0576]

Epoch 7 | Batch 250/3125 | Loss: 0.0576

Epoch 7/30:  10%|▉         | 302/3125 [00:38<06:29,  7.24it/s, loss=0.0425]

Epoch 7 | Batch 300/3125 | Loss: 0.0552

Epoch 7/30:  11%|█         | 351/3125 [00:44<06:28,  7.14it/s, loss=0.028]

Epoch 7 | Batch 350/3125 | Loss: 0.0126

Epoch 7/30:  13%|█▎        | 401/3125 [00:50<05:48,  7.82it/s, loss=0.101]

Epoch 7 | Batch 400/3125 | Loss: 0.0435

Epoch 7/30:  14%|█▍        | 451/3125 [00:57<05:37,  7.93it/s, loss=0.0413]

Epoch 7 | Batch 450/3125 | Loss: 0.0433

Epoch 7/30:  16%|█▌        | 501/3125 [01:03<05:28,  8.00it/s, loss=0.0316]

Epoch 7 | Batch 500/3125 | Loss: 0.0351

Epoch 7/30:  18%|█▊        | 551/3125 [01:09<05:22,  7.97it/s, loss=0.0313]

Epoch 7 | Batch 550/3125 | Loss: 0.0478

Epoch 7/30:  19%|█▉        | 601/3125 [01:16<05:43,  7.34it/s, loss=0.061]

Epoch 7 | Batch 600/3125 | Loss: 0.0450

Epoch 7/30:  21%|██        | 652/3125 [01:22<04:54,  8.40it/s, loss=0.0318]

Epoch 7 | Batch 650/3125 | Loss: 0.0369

Epoch 7/30:  22%|██▏       | 702/3125 [01:28<04:42,  8.56it/s, loss=0.0711]

Epoch 7 | Batch 700/3125 | Loss: 0.0333

Epoch 7/30:  24%|██▍       | 752/3125 [01:34<04:59,  7.91it/s, loss=0.0325]

Epoch 7 | Batch 750/3125 | Loss: 0.0633

Epoch 7/30:  26%|██▌       | 801/3125 [01:41<04:51,  7.98it/s, loss=0.0391]

Epoch 7 | Batch 800/3125 | Loss: 0.0631

Epoch 7/30:  27%|██▋       | 851/3125 [01:47<04:52,  7.78it/s, loss=0.0773]

Epoch 7 | Batch 850/3125 | Loss: 0.0455

Epoch 7/30:  29%|██▉       | 901/3125 [01:54<04:33,  8.14it/s, loss=0.0455]

Epoch 7 | Batch 900/3125 | Loss: 0.0825

Epoch 7/30:  30%|███       | 951/3125 [02:00<04:17,  8.44it/s, loss=0.0706]

Epoch 7 | Batch 950/3125 | Loss: 0.0230

Epoch 7/30:  32%|███▏      | 1001/3125 [02:06<04:25,  7.99it/s, loss=0.0304]

Epoch 7 | Batch 1000/3125 | Loss: 0.0267

Epoch 7/30:  34%|███▎      | 1052/3125 [02:12<04:11,  8.25it/s, loss=0.0223]

Epoch 7 | Batch 1050/3125 | Loss: 0.0409

Epoch 7/30:  35%|███▌      | 1101/3125 [02:18<03:58,  8.50it/s, loss=0.0671]

Epoch 7 | Batch 1100/3125 | Loss: 0.0520

Epoch 7/30:  37%|███▋      | 1151/3125 [02:25<04:12,  7.83it/s, loss=0.0553]

Epoch 7 | Batch 1150/3125 | Loss: 0.0732

Epoch 7/30:  38%|███▊      | 1200/3125 [02:31<04:12,  7.64it/s, loss=0.0731]

Epoch 7 | Batch 1200/3125 | Loss: 0.0731

Epoch 7/30:  40%|████      | 1252/3125 [02:37<03:53,  8.03it/s, loss=0.0701]

Epoch 7 | Batch 1250/3125 | Loss: 0.0372

Epoch 7/30:  42%|████▏     | 1302/3125 [02:44<03:49,  7.94it/s, loss=0.101]

Epoch 7 | Batch 1300/3125 | Loss: 0.0566

Epoch 7/30:  43%|████▎     | 1352/3125 [02:50<03:39,  8.08it/s, loss=0.0263]

Epoch 7 | Batch 1350/3125 | Loss: 0.0977

Epoch 7/30:  45%|████▍     | 1401/3125 [02:56<03:36,  7.97it/s, loss=0.0792]

Epoch 7 | Batch 1400/3125 | Loss: 0.0622

Epoch 7/30:  46%|████▋     | 1451/3125 [03:03<03:36,  7.73it/s, loss=0.0582]

Epoch 7 | Batch 1450/3125 | Loss: 0.1041

Epoch 7/30:  48%|████▊     | 1501/3125 [03:09<03:18,  8.17it/s, loss=0.0372]

Epoch 7 | Batch 1500/3125 | Loss: 0.0663

Epoch 7/30:  50%|████▉     | 1551/3125 [03:15<03:31,  7.45it/s, loss=0.0163]

Epoch 7 | Batch 1550/3125 | Loss: 0.0865

Epoch 7/30:  51%|█████     | 1601/3125 [03:21<03:08,  8.08it/s, loss=0.0582]

Epoch 7 | Batch 1600/3125 | Loss: 0.0553

Epoch 7/30:  53%|█████▎    | 1652/3125 [03:28<03:02,  8.08it/s, loss=0.0528]

Epoch 7 | Batch 1650/3125 | Loss: 0.0609

Epoch 7/30:  54%|█████▍    | 1702/3125 [03:34<02:51,  8.32it/s, loss=0.0565]

Epoch 7 | Batch 1700/3125 | Loss: 0.0457

Epoch 7/30:  56%|█████▌    | 1752/3125 [03:40<02:59,  7.66it/s, loss=0.0359]

Epoch 7 | Batch 1750/3125 | Loss: 0.0324

Epoch 7/30:  58%|█████▊    | 1802/3125 [03:47<02:47,  7.91it/s, loss=0.141]

Epoch 7 | Batch 1800/3125 | Loss: 0.0264

Epoch 7/30:  59%|█████▉    | 1852/3125 [03:53<02:33,  8.31it/s, loss=0.102]

Epoch 7 | Batch 1850/3125 | Loss: 0.0252

Epoch 7/30:  61%|██████    | 1901/3125 [03:59<02:37,  7.79it/s, loss=0.0502]

Epoch 7 | Batch 1900/3125 | Loss: 0.0644

Epoch 7/30:  62%|██████▏   | 1951/3125 [04:06<02:30,  7.81it/s, loss=0.0404]

Epoch 7 | Batch 1950/3125 | Loss: 0.0703

Epoch 7/30:  64%|██████▍   | 2001/3125 [04:12<02:22,  7.91it/s, loss=0.06]

Epoch 7 | Batch 2000/3125 | Loss: 0.1699

Epoch 7/30:  66%|██████▌   | 2051/3125 [04:18<02:14,  7.96it/s, loss=0.0373]

Epoch 7 | Batch 2050/3125 | Loss: 0.0351

Epoch 7/30:  67%|██████▋   | 2102/3125 [04:24<02:08,  7.97it/s, loss=0.0189]

Epoch 7 | Batch 2100/3125 | Loss: 0.0494

Epoch 7/30:  69%|██████▉   | 2152/3125 [04:31<02:00,  8.06it/s, loss=0.0393]

Epoch 7 | Batch 2150/3125 | Loss: 0.0260

Epoch 7/30:  70%|███████   | 2202/3125 [04:37<01:50,  8.38it/s, loss=0.0218]

Epoch 7 | Batch 2200/3125 | Loss: 0.0572

Epoch 7/30:  72%|███████▏  | 2252/3125 [04:44<01:50,  7.92it/s, loss=0.0514]

Epoch 7 | Batch 2250/3125 | Loss: 0.0807

Epoch 7/30:  74%|███████▎  | 2302/3125 [04:50<01:41,  8.12it/s, loss=0.0323]

Epoch 7 | Batch 2300/3125 | Loss: 0.0349

Epoch 7/30:  75%|███████▌  | 2352/3125 [04:56<01:34,  8.20it/s, loss=0.0455]

Epoch 7 | Batch 2350/3125 | Loss: 0.0369

Epoch 7/30:  77%|███████▋  | 2400/3125 [05:02<01:30,  7.97it/s, loss=0.055]

Epoch 7 | Batch 2400/3125 | Loss: 0.0550

Epoch 7/30:  78%|███████▊  | 2452/3125 [05:09<01:20,  8.34it/s, loss=0.062]

Epoch 7 | Batch 2450/3125 | Loss: 0.0594

Epoch 7/30:  80%|████████  | 2501/3125 [05:15<01:18,  7.90it/s, loss=0.0449]

Epoch 7 | Batch 2500/3125 | Loss: 0.0656

Epoch 7/30:  82%|████████▏ | 2551/3125 [05:21<01:10,  8.11it/s, loss=0.041]

Epoch 7 | Batch 2550/3125 | Loss: 0.0887

Epoch 7/30:  83%|████████▎ | 2601/3125 [05:27<01:02,  8.44it/s, loss=0.0724]

Epoch 7 | Batch 2600/3125 | Loss: 0.0346

Epoch 7/30:  85%|████████▍ | 2652/3125 [05:34<01:09,  6.83it/s, loss=0.0825]

Epoch 7 | Batch 2650/3125 | Loss: 0.0393

Epoch 7/30:  86%|████████▋ | 2701/3125 [05:40<00:51,  8.24it/s, loss=0.0337]

Epoch 7 | Batch 2700/3125 | Loss: 0.0260

Epoch 7/30:  88%|████████▊ | 2751/3125 [05:46<00:50,  7.36it/s, loss=0.0399]

Epoch 7 | Batch 2750/3125 | Loss: 0.0541

Epoch 7/30:  90%|████████▉ | 2802/3125 [05:53<00:40,  8.01it/s, loss=0.0527]

Epoch 7 | Batch 2800/3125 | Loss: 0.0330

Epoch 7/30:  91%|█████████ | 2851/3125 [05:59<00:39,  6.87it/s, loss=0.0644]

Epoch 7 | Batch 2850/3125 | Loss: 0.0865

Epoch 7/30:  93%|█████████▎| 2901/3125 [06:06<00:31,  7.10it/s, loss=0.0777]

Epoch 7 | Batch 2900/3125 | Loss: 0.0642

Epoch 7/30:  94%|█████████▍| 2951/3125 [06:12<00:21,  8.00it/s, loss=0.037]

Epoch 7 | Batch 2950/3125 | Loss: 0.0315

Epoch 7/30:  96%|█████████▌| 3001/3125 [06:18<00:16,  7.63it/s, loss=0.063]

Epoch 7 | Batch 3000/3125 | Loss: 0.0632

Epoch 7/30:  98%|█████████▊| 3051/3125 [06:25<00:09,  7.79it/s, loss=0.0522]

Epoch 7 | Batch 3050/3125 | Loss: 0.1033

Epoch 7/30:  99%|█████████▉| 3101/3125 [06:31<00:03,  7.81it/s, loss=0.0403]

Epoch 7 | Batch 3100/3125 | Loss: 0.0444

Epoch 7/30: 100%|██████████| 3125/3125 [06:34<00:00,  7.92it/s, loss=0.122]

Epoch [7/30] - Avg Loss: 0.0524

Epoch 8/30:   0%|          | 1/3125 [00:00<14:54,  3.49it/s, loss=0.036]

Epoch 8 | Batch 0/3125 | Loss: 0.0843

Epoch 8/30:   2%|▏         | 51/3125 [00:06<06:08,  8.34it/s, loss=0.0281]

Epoch 8 | Batch 50/3125 | Loss: 0.0496

Epoch 8/30:   3%|▎         | 101/3125 [00:13<06:33,  7.69it/s, loss=0.0521]

Epoch 8 | Batch 100/3125 | Loss: 0.0779

Epoch 8/30:   5%|▍         | 151/3125 [00:19<06:21,  7.79it/s, loss=0.0251]

Epoch 8 | Batch 150/3125 | Loss: 0.0778

Epoch 8/30:   6%|▋         | 201/3125 [00:25<06:08,  7.93it/s, loss=0.0392]

Epoch 8 | Batch 200/3125 | Loss: 0.0225

Epoch 8/30:   8%|▊         | 251/3125 [00:31<05:51,  8.17it/s, loss=0.0888]

Epoch 8 | Batch 250/3125 | Loss: 0.0500

Epoch 8/30:  10%|▉         | 302/3125 [00:38<06:15,  7.51it/s, loss=0.0558]

Epoch 8 | Batch 300/3125 | Loss: 0.0344

Epoch 8/30:  11%|█         | 350/3125 [00:44<05:42,  8.11it/s, loss=0.0191]

Epoch 8 | Batch 350/3125 | Loss: 0.0191

Epoch 8/30:  13%|█▎        | 402/3125 [00:50<05:34,  8.15it/s, loss=0.0442]

Epoch 8 | Batch 400/3125 | Loss: 0.0592

Epoch 8/30:  14%|█▍        | 452/3125 [00:57<05:29,  8.11it/s, loss=0.0503]

Epoch 8 | Batch 450/3125 | Loss: 0.0447

Epoch 8/30:  16%|█▌        | 502/3125 [01:03<05:30,  7.94it/s, loss=0.027]

Epoch 8 | Batch 500/3125 | Loss: 0.0457

Epoch 8/30:  18%|█▊        | 552/3125 [01:09<05:11,  8.25it/s, loss=0.0074]

Epoch 8 | Batch 550/3125 | Loss: 0.0369

Epoch 8/30:  19%|█▉        | 602/3125 [01:16<05:20,  7.87it/s, loss=0.0421]

Epoch 8 | Batch 600/3125 | Loss: 0.0686

Epoch 8/30:  21%|██        | 652/3125 [01:22<05:15,  7.85it/s, loss=0.0606]

Epoch 8 | Batch 650/3125 | Loss: 0.0404

Epoch 8/30:  22%|██▏       | 702/3125 [01:28<05:15,  7.68it/s, loss=0.033]

Epoch 8 | Batch 700/3125 | Loss: 0.0234

Epoch 8/30:  24%|██▍       | 752/3125 [01:34<05:00,  7.89it/s, loss=0.0484]

Epoch 8 | Batch 750/3125 | Loss: 0.0590

Epoch 8/30:  26%|██▌       | 802/3125 [01:41<04:59,  7.76it/s, loss=0.0448]

Epoch 8 | Batch 800/3125 | Loss: 0.0567

Epoch 8/30:  27%|██▋       | 852/3125 [01:47<04:36,  8.21it/s, loss=0.0457]

Epoch 8 | Batch 850/3125 | Loss: 0.0307

Epoch 8/30:  29%|██▉       | 902/3125 [01:53<04:26,  8.35it/s, loss=0.0274]

Epoch 8 | Batch 900/3125 | Loss: 0.0363

Epoch 8/30:  30%|███       | 952/3125 [02:00<04:51,  7.45it/s, loss=0.0228]

Epoch 8 | Batch 950/3125 | Loss: 0.0488

Epoch 8/30:  32%|███▏      | 1001/3125 [02:06<04:15,  8.31it/s, loss=0.0366]

Epoch 8 | Batch 1000/3125 | Loss: 0.0468

Epoch 8/30:  34%|███▎      | 1051/3125 [02:12<05:08,  6.73it/s, loss=0.0399]

Epoch 8 | Batch 1050/3125 | Loss: 0.0688

Epoch 8/30:  35%|███▌      | 1102/3125 [02:19<04:26,  7.59it/s, loss=0.0318]

Epoch 8 | Batch 1100/3125 | Loss: 0.0263

Epoch 8/30:  37%|███▋      | 1150/3125 [02:25<04:04,  8.07it/s, loss=0.0607]

Epoch 8 | Batch 1150/3125 | Loss: 0.0607

Epoch 8/30:  38%|███▊      | 1202/3125 [02:31<03:54,  8.20it/s, loss=0.028]

Epoch 8 | Batch 1200/3125 | Loss: 0.0549

Epoch 8/30:  40%|████      | 1250/3125 [02:38<03:48,  8.20it/s, loss=0.0382]

Epoch 8 | Batch 1250/3125 | Loss: 0.0236

Epoch 8/30:  42%|████▏     | 1302/3125 [02:44<04:08,  7.34it/s, loss=0.0358]

Epoch 8 | Batch 1300/3125 | Loss: 0.0283

Epoch 8/30:  43%|████▎     | 1352/3125 [02:50<03:42,  7.96it/s, loss=0.0617]

Epoch 8 | Batch 1350/3125 | Loss: 0.0461

Epoch 8/30:  45%|████▍     | 1400/3125 [02:57<03:40,  7.82it/s, loss=0.0468]

Epoch 8 | Batch 1400/3125 | Loss: 0.1110

Epoch 8/30:  46%|████▋     | 1450/3125 [03:03<03:16,  8.53it/s, loss=0.0548]

Epoch 8 | Batch 1450/3125 | Loss: 0.0548

Epoch 8/30:  48%|████▊     | 1502/3125 [03:09<03:25,  7.90it/s, loss=0.0414]

Epoch 8 | Batch 1500/3125 | Loss: 0.0593

Epoch 8/30:  50%|████▉     | 1550/3125 [03:15<03:42,  7.08it/s, loss=0.0375]

Epoch 8 | Batch 1550/3125 | Loss: 0.0375

Epoch 8/30:  51%|█████▏    | 1602/3125 [03:22<03:11,  7.93it/s, loss=0.0226]

Epoch 8 | Batch 1600/3125 | Loss: 0.1209

Epoch 8/30:  53%|█████▎    | 1652/3125 [03:28<03:01,  8.11it/s, loss=0.0336]

Epoch 8 | Batch 1650/3125 | Loss: 0.0237

Epoch 8/30:  54%|█████▍    | 1702/3125 [03:35<02:58,  7.97it/s, loss=0.0906]

Epoch 8 | Batch 1700/3125 | Loss: 0.0436

Epoch 8/30:  56%|█████▌    | 1750/3125 [03:41<02:52,  7.98it/s, loss=0.0763]

Epoch 8 | Batch 1750/3125 | Loss: 0.0763

Epoch 8/30:  58%|█████▊    | 1800/3125 [03:47<03:01,  7.31it/s, loss=0.0179]

Epoch 8 | Batch 1800/3125 | Loss: 0.0179

Epoch 8/30:  59%|█████▉    | 1852/3125 [03:54<02:43,  7.78it/s, loss=0.067]

Epoch 8 | Batch 1850/3125 | Loss: 0.0345

Epoch 8/30:  61%|██████    | 1902/3125 [04:01<02:33,  7.97it/s, loss=0.025]

Epoch 8 | Batch 1900/3125 | Loss: 0.0701

Epoch 8/30:  62%|██████▏   | 1952/3125 [04:07<02:30,  7.82it/s, loss=0.071]

Epoch 8 | Batch 1950/3125 | Loss: 0.0690

Epoch 8/30:  64%|██████▍   | 2002/3125 [04:14<02:13,  8.41it/s, loss=0.0964]

Epoch 8 | Batch 2000/3125 | Loss: 0.0486

Epoch 8/30:  66%|██████▌   | 2050/3125 [04:20<02:33,  7.01it/s, loss=0.0508]

Epoch 8 | Batch 2050/3125 | Loss: 0.0508

Epoch 8/30:  67%|██████▋   | 2102/3125 [04:28<02:12,  7.72it/s, loss=0.0399]

Epoch 8 | Batch 2100/3125 | Loss: 0.0338

Epoch 8/30:  69%|██████▉   | 2152/3125 [04:34<02:14,  7.26it/s, loss=0.0386]

Epoch 8 | Batch 2150/3125 | Loss: 0.0380

Epoch 8/30:  70%|███████   | 2202/3125 [04:41<02:03,  7.48it/s, loss=0.0224]

Epoch 8 | Batch 2200/3125 | Loss: 0.0385

Epoch 8/30:  72%|███████▏  | 2250/3125 [04:47<01:46,  8.23it/s, loss=0.0695]

Epoch 8 | Batch 2250/3125 | Loss: 0.0593

Epoch 8/30:  74%|███████▎  | 2301/3125 [04:54<02:08,  6.42it/s, loss=0.0284]

Epoch 8 | Batch 2300/3125 | Loss: 0.0906

Epoch 8/30:  75%|███████▌  | 2351/3125 [05:00<01:37,  7.91it/s, loss=0.0319]

Epoch 8 | Batch 2350/3125 | Loss: 0.0527

Epoch 8/30:  77%|███████▋  | 2401/3125 [05:06<01:32,  7.81it/s, loss=0.0622]

Epoch 8 | Batch 2400/3125 | Loss: 0.0576

Epoch 8/30:  78%|███████▊  | 2451/3125 [05:12<01:24,  7.96it/s, loss=0.033]

Epoch 8 | Batch 2450/3125 | Loss: 0.0361

Epoch 8/30:  80%|████████  | 2501/3125 [05:19<01:19,  7.82it/s, loss=0.0475]

Epoch 8 | Batch 2500/3125 | Loss: 0.0569

Epoch 8/30:  82%|████████▏ | 2551/3125 [05:25<01:20,  7.13it/s, loss=0.0632]

Epoch 8 | Batch 2550/3125 | Loss: 0.0354

Epoch 8/30:  83%|████████▎ | 2602/3125 [05:32<01:02,  8.41it/s, loss=0.0299]

Epoch 8 | Batch 2600/3125 | Loss: 0.0359

Epoch 8/30:  85%|████████▍ | 2650/3125 [05:38<00:59,  8.01it/s, loss=0.0213]

Epoch 8 | Batch 2650/3125 | Loss: 0.0213

Epoch 8/30:  86%|████████▋ | 2702/3125 [05:44<00:56,  7.52it/s, loss=0.0356]

Epoch 8 | Batch 2700/3125 | Loss: 0.0542

Epoch 8/30:  88%|████████▊ | 2752/3125 [05:51<00:46,  7.95it/s, loss=0.0166]

Epoch 8 | Batch 2750/3125 | Loss: 0.0317

Epoch 8/30:  90%|████████▉ | 2800/3125 [05:57<00:46,  7.03it/s, loss=0.0438]

Epoch 8 | Batch 2800/3125 | Loss: 0.0438

Epoch 8/30:  91%|█████████ | 2850/3125 [06:04<00:34,  7.99it/s, loss=0.0357]

Epoch 8 | Batch 2850/3125 | Loss: 0.0357

Epoch 8/30:  93%|█████████▎| 2902/3125 [06:11<00:26,  8.26it/s, loss=0.0114]

Epoch 8 | Batch 2900/3125 | Loss: 0.0306

Epoch 8/30:  94%|█████████▍| 2950/3125 [06:17<00:23,  7.38it/s, loss=0.0374]

Epoch 8 | Batch 2950/3125 | Loss: 0.0374

Epoch 8/30:  96%|█████████▌| 3000/3125 [06:24<00:16,  7.59it/s, loss=0.0595]

Epoch 8 | Batch 3000/3125 | Loss: 0.0555

Epoch 8/30:  98%|█████████▊| 3050/3125 [06:30<00:10,  7.08it/s, loss=0.0357]

Epoch 8 | Batch 3050/3125 | Loss: 0.0357

Epoch 8/30:  99%|█████████▉| 3100/3125 [06:37<00:03,  7.68it/s, loss=0.0359]

Epoch 8 | Batch 3100/3125 | Loss: 0.0359

Epoch 8/30: 100%|██████████| 3125/3125 [06:40<00:00,  7.80it/s, loss=0.0502]

Epoch [8/30] - Avg Loss: 0.0463

Epoch 9/30:   0%|          | 1/3125 [00:00<17:22,  3.00it/s, loss=0.0416]

Epoch 9 | Batch 0/3125 | Loss: 0.0527

Epoch 9/30:   2%|▏         | 51/3125 [00:06<07:05,  7.22it/s, loss=0.0419]

Epoch 9 | Batch 50/3125 | Loss: 0.0717

Epoch 9/30:   3%|▎         | 102/3125 [00:13<06:10,  8.17it/s, loss=0.0779]

Epoch 9 | Batch 100/3125 | Loss: 0.0204

Epoch 9/30:   5%|▍         | 152/3125 [00:20<06:24,  7.73it/s, loss=0.0455]

Epoch 9 | Batch 150/3125 | Loss: 0.0489

Epoch 9/30:   6%|▋         | 202/3125 [00:26<05:57,  8.18it/s, loss=0.0191]

Epoch 9 | Batch 200/3125 | Loss: 0.0431

Epoch 9/30:   8%|▊         | 252/3125 [00:33<05:57,  8.04it/s, loss=0.0257]

Epoch 9 | Batch 250/3125 | Loss: 0.0345

Epoch 9/30:  10%|▉         | 302/3125 [00:39<06:08,  7.66it/s, loss=0.0324]

Epoch 9 | Batch 300/3125 | Loss: 0.0334

Epoch 9/30:  11%|█▏        | 352/3125 [00:46<05:42,  8.09it/s, loss=0.0626]

Epoch 9 | Batch 350/3125 | Loss: 0.0371

Epoch 9/30:  13%|█▎        | 400/3125 [00:52<05:49,  7.80it/s, loss=0.0309]

Epoch 9 | Batch 400/3125 | Loss: 0.0309

Epoch 9/30:  14%|█▍        | 452/3125 [00:59<05:35,  7.98it/s, loss=0.0565]

Epoch 9 | Batch 450/3125 | Loss: 0.0375

Epoch 9/30:  16%|█▌        | 501/3125 [01:05<05:34,  7.85it/s, loss=0.0358]

Epoch 9 | Batch 500/3125 | Loss: 0.0255

Epoch 9/30:  18%|█▊        | 551/3125 [01:12<05:31,  7.77it/s, loss=0.0526]

Epoch 9 | Batch 550/3125 | Loss: 0.0713

Epoch 9/30:  19%|█▉        | 601/3125 [01:18<05:51,  7.18it/s, loss=0.0197]

Epoch 9 | Batch 600/3125 | Loss: 0.0603

Epoch 9/30:  21%|██        | 652/3125 [01:24<05:13,  7.88it/s, loss=0.0326]

Epoch 9 | Batch 650/3125 | Loss: 0.0456

Epoch 9/30:  22%|██▏       | 701/3125 [01:31<05:16,  7.65it/s, loss=0.0468]

Epoch 9 | Batch 700/3125 | Loss: 0.0179

Epoch 9/30:  24%|██▍       | 751/3125 [01:37<05:06,  7.75it/s, loss=0.0104]

Epoch 9 | Batch 750/3125 | Loss: 0.0224

Epoch 9/30:  26%|██▌       | 801/3125 [01:44<04:53,  7.91it/s, loss=0.0157]

Epoch 9 | Batch 800/3125 | Loss: 0.0888

Epoch 9/30:  27%|██▋       | 851/3125 [01:50<04:43,  8.01it/s, loss=0.0329]

Epoch 9 | Batch 850/3125 | Loss: 0.0878

Epoch 9/30:  29%|██▉       | 901/3125 [01:57<04:52,  7.59it/s, loss=0.0257]

Epoch 9 | Batch 900/3125 | Loss: 0.0474

Epoch 9/30:  30%|███       | 951/3125 [02:04<04:30,  8.03it/s, loss=0.0962]

Epoch 9 | Batch 950/3125 | Loss: 0.0203

Epoch 9/30:  32%|███▏      | 1001/3125 [02:10<04:35,  7.71it/s, loss=0.0479]

Epoch 9 | Batch 1000/3125 | Loss: 0.0533

Epoch 9/30:  34%|███▎      | 1051/3125 [02:16<04:23,  7.87it/s, loss=0.0139]

Epoch 9 | Batch 1050/3125 | Loss: 0.0803

Epoch 9/30:  35%|███▌      | 1101/3125 [02:22<04:04,  8.29it/s, loss=0.0409]

Epoch 9 | Batch 1100/3125 | Loss: 0.0375

Epoch 9/30:  37%|███▋      | 1151/3125 [02:28<04:08,  7.94it/s, loss=0.0309]

Epoch 9 | Batch 1150/3125 | Loss: 0.0208

Epoch 9/30:  38%|███▊      | 1201/3125 [02:35<04:15,  7.54it/s, loss=0.0504]

Epoch 9 | Batch 1200/3125 | Loss: 0.0294

Epoch 9/30:  40%|████      | 1251/3125 [02:41<04:07,  7.59it/s, loss=0.0447]

Epoch 9 | Batch 1250/3125 | Loss: 0.0294

Epoch 9/30:  42%|████▏     | 1301/3125 [02:48<03:59,  7.61it/s, loss=0.05]

Epoch 9 | Batch 1300/3125 | Loss: 0.0821

Epoch 9/30:  43%|████▎     | 1351/3125 [02:54<03:38,  8.10it/s, loss=0.0405]

Epoch 9 | Batch 1350/3125 | Loss: 0.0287

Epoch 9/30:  45%|████▍     | 1401/3125 [03:00<03:41,  7.78it/s, loss=0.0739]

Epoch 9 | Batch 1400/3125 | Loss: 0.0387

Epoch 9/30:  46%|████▋     | 1451/3125 [03:07<04:27,  6.25it/s, loss=0.0784]

Epoch 9 | Batch 1450/3125 | Loss: 0.0143

Epoch 9/30:  48%|████▊     | 1501/3125 [03:14<03:44,  7.24it/s, loss=0.0294]

Epoch 9 | Batch 1500/3125 | Loss: 0.0234

Epoch 9/30:  50%|████▉     | 1550/3125 [03:21<03:52,  6.77it/s, loss=0.0515]

Epoch 9 | Batch 1550/3125 | Loss: 0.0515

Epoch 9/30:  51%|█████     | 1601/3125 [03:29<04:07,  6.15it/s, loss=0.0373]

Epoch 9 | Batch 1600/3125 | Loss: 0.0305

Epoch 9/30:  53%|█████▎    | 1651/3125 [03:36<03:55,  6.25it/s, loss=0.0333]

Epoch 9 | Batch 1650/3125 | Loss: 0.0259

Epoch 9/30:  54%|█████▍    | 1700/3125 [03:43<03:49,  6.21it/s, loss=0.0432]

Epoch 9 | Batch 1700/3125 | Loss: 0.0432

Epoch 9/30:  56%|█████▌    | 1750/3125 [03:51<03:26,  6.67it/s, loss=0.00954]

Epoch 9 | Batch 1750/3125 | Loss: 0.0095

Epoch 9/30:  58%|█████▊    | 1800/3125 [03:58<03:33,  6.20it/s, loss=0.0785]

Epoch 9 | Batch 1800/3125 | Loss: 0.0785

Epoch 9/30:  59%|█████▉    | 1852/3125 [04:05<02:52,  7.37it/s, loss=0.066]

Epoch 9 | Batch 1850/3125 | Loss: 0.0426

Epoch 9/30:  61%|██████    | 1900/3125 [04:13<03:18,  6.18it/s, loss=0.023]

Epoch 9 | Batch 1900/3125 | Loss: 0.0230

Epoch 9/30:  62%|██████▏   | 1950/3125 [04:20<03:02,  6.42it/s, loss=0.0289]

Epoch 9 | Batch 1950/3125 | Loss: 0.0289

Epoch 9/30:  64%|██████▍   | 2000/3125 [04:28<02:55,  6.42it/s, loss=0.0555]

Epoch 9 | Batch 2000/3125 | Loss: 0.0555

Epoch 9/30:  66%|██████▌   | 2052/3125 [04:35<02:24,  7.43it/s, loss=0.0332]

Epoch 9 | Batch 2050/3125 | Loss: 0.0260

Epoch 9/30:  67%|██████▋   | 2101/3125 [04:43<02:19,  7.32it/s, loss=0.0808]

Epoch 9 | Batch 2100/3125 | Loss: 0.0808

Epoch 9/30:  69%|██████▉   | 2151/3125 [04:50<02:17,  7.06it/s, loss=0.0287]

Epoch 9 | Batch 2150/3125 | Loss: 0.0319

Epoch 9/30:  70%|███████   | 2201/3125 [04:58<02:29,  6.18it/s, loss=0.043]

Epoch 9 | Batch 2200/3125 | Loss: 0.0392

Epoch 9/30:  72%|███████▏  | 2251/3125 [05:05<02:06,  6.92it/s, loss=0.016]

Epoch 9 | Batch 2250/3125 | Loss: 0.0270

Epoch 9/30:  74%|███████▎  | 2301/3125 [05:12<01:58,  6.93it/s, loss=0.0413]

Epoch 9 | Batch 2300/3125 | Loss: 0.0510

Epoch 9/30:  75%|███████▌  | 2351/3125 [05:20<01:47,  7.22it/s, loss=0.053]

Epoch 9 | Batch 2350/3125 | Loss: 0.0389

Epoch 9/30:  77%|███████▋  | 2401/3125 [05:27<01:50,  6.58it/s, loss=0.0192]

Epoch 9 | Batch 2400/3125 | Loss: 0.0476

Epoch 9/30:  78%|███████▊  | 2451/3125 [05:35<01:41,  6.67it/s, loss=0.0182]

Epoch 9 | Batch 2450/3125 | Loss: 0.0361

Epoch 9/30:  80%|████████  | 2501/3125 [05:42<01:19,  7.84it/s, loss=0.0429]

Epoch 9 | Batch 2500/3125 | Loss: 0.0421

Epoch 9/30:  82%|████████▏ | 2551/3125 [05:49<01:34,  6.06it/s, loss=0.0479]

Epoch 9 | Batch 2550/3125 | Loss: 0.0556

Epoch 9/30:  83%|████████▎ | 2601/3125 [05:56<01:09,  7.49it/s, loss=0.0384]

Epoch 9 | Batch 2600/3125 | Loss: 0.0337

Epoch 9/30:  85%|████████▍ | 2652/3125 [06:04<01:05,  7.18it/s, loss=0.0309]

Epoch 9 | Batch 2650/3125 | Loss: 0.0602

Epoch 9/30:  86%|████████▋ | 2702/3125 [06:11<01:06,  6.35it/s, loss=0.063]

Epoch 9 | Batch 2700/3125 | Loss: 0.0320

Epoch 9/30:  88%|████████▊ | 2752/3125 [06:18<00:56,  6.64it/s, loss=0.0176]

Epoch 9 | Batch 2750/3125 | Loss: 0.0226

Epoch 9/30:  90%|████████▉ | 2801/3125 [06:25<00:46,  6.93it/s, loss=0.028]

Epoch 9 | Batch 2800/3125 | Loss: 0.0358

Epoch 9/30:  91%|█████████ | 2851/3125 [06:33<00:40,  6.72it/s, loss=0.0556]

Epoch 9 | Batch 2850/3125 | Loss: 0.0239

Epoch 9/30:  93%|█████████▎| 2901/3125 [06:40<00:29,  7.62it/s, loss=0.0461]

Epoch 9 | Batch 2900/3125 | Loss: 0.0380

Epoch 9/30:  94%|█████████▍| 2952/3125 [06:47<00:25,  6.83it/s, loss=0.028]

Epoch 9 | Batch 2950/3125 | Loss: 0.0224

Epoch 9/30:  96%|█████████▌| 3002/3125 [06:55<00:20,  6.08it/s, loss=0.0496]

Epoch 9 | Batch 3000/3125 | Loss: 0.0126

Epoch 9/30:  98%|█████████▊| 3052/3125 [07:02<00:10,  7.06it/s, loss=0.036]

Epoch 9 | Batch 3050/3125 | Loss: 0.0277

Epoch 9/30:  99%|█████████▉| 3100/3125 [07:09<00:03,  7.46it/s, loss=0.0633]

Epoch 9 | Batch 3100/3125 | Loss: 0.0633

Epoch 9/30: 100%|██████████| 3125/3125 [07:13<00:00,  7.22it/s, loss=0.0437]

Epoch [9/30] - Avg Loss: 0.0401

Epoch 10/30:   0%|          | 1/3125 [00:00<16:46,  3.11it/s, loss=0.0161]

Epoch 10 | Batch 0/3125 | Loss: 0.0175

Epoch 10/30:   2%|▏         | 51/3125 [00:07<06:57,  7.36it/s, loss=0.0215]

Epoch 10 | Batch 50/3125 | Loss: 0.0398

Epoch 10/30:   3%|▎         | 101/3125 [00:14<08:23,  6.01it/s, loss=0.0188]

Epoch 10 | Batch 100/3125 | Loss: 0.0369

Epoch 10/30:   5%|▍         | 151/3125 [00:21<06:28,  7.66it/s, loss=0.0275]

Epoch 10 | Batch 150/3125 | Loss: 0.0113

Epoch 10/30:   6%|▋         | 201/3125 [00:28<06:38,  7.33it/s, loss=0.0212]

Epoch 10 | Batch 200/3125 | Loss: 0.0242

Epoch 10/30:   8%|▊         | 251/3125 [00:35<06:31,  7.35it/s, loss=0.0397]

Epoch 10 | Batch 250/3125 | Loss: 0.0446

Epoch 10/30:  10%|▉         | 301/3125 [00:41<06:05,  7.73it/s, loss=0.0281]

Epoch 10 | Batch 300/3125 | Loss: 0.0706

Epoch 10/30:  11%|█         | 351/3125 [00:49<07:19,  6.32it/s, loss=0.028]

Epoch 10 | Batch 350/3125 | Loss: 0.0148

Epoch 10/30:  13%|█▎        | 400/3125 [00:56<05:55,  7.67it/s, loss=0.0153]

Epoch 10 | Batch 400/3125 | Loss: 0.0153

Epoch 10/30:  14%|█▍        | 450/3125 [01:03<06:15,  7.13it/s, loss=0.0407]

Epoch 10 | Batch 450/3125 | Loss: 0.0407

Epoch 10/30:  16%|█▌        | 500/3125 [01:10<06:08,  7.12it/s, loss=0.0645]

Epoch 10 | Batch 500/3125 | Loss: 0.0645

Epoch 10/30:  18%|█▊        | 550/3125 [01:17<06:27,  6.64it/s, loss=0.0294]

Epoch 10 | Batch 550/3125 | Loss: 0.0294

Epoch 10/30:  19%|█▉        | 600/3125 [01:25<06:36,  6.37it/s, loss=0.0453]

Epoch 10 | Batch 600/3125 | Loss: 0.0453

Epoch 10/30:  21%|██        | 652/3125 [01:32<05:41,  7.24it/s, loss=0.031]

Epoch 10 | Batch 650/3125 | Loss: 0.0308

Epoch 10/30:  22%|██▏       | 700/3125 [01:39<05:41,  7.11it/s, loss=0.0607]

Epoch 10 | Batch 700/3125 | Loss: 0.0607

Epoch 10/30:  24%|██▍       | 750/3125 [02:01<06:30,  6.08it/s, loss=0.0313]

Epoch 10 | Batch 750/3125 | Loss: 0.0313

Epoch 10/30:  26%|██▌       | 802/3125 [02:08<05:47,  6.68it/s, loss=0.0292]

Epoch 10 | Batch 800/3125 | Loss: 0.0334

Epoch 10/30:  27%|██▋       | 850/3125 [02:16<06:02,  6.28it/s, loss=0.0566]

Epoch 10 | Batch 850/3125 | Loss: 0.0566

Epoch 10/30:  29%|██▉       | 902/3125 [02:23<05:03,  7.34it/s, loss=0.0285]

Epoch 10 | Batch 900/3125 | Loss: 0.0485

Epoch 10/30:  30%|███       | 950/3125 [02:30<05:30,  6.58it/s, loss=0.023]

Epoch 10 | Batch 950/3125 | Loss: 0.0230

Epoch 10/30:  32%|███▏      | 1000/3125 [02:38<04:39,  7.59it/s, loss=0.0396]

Epoch 10 | Batch 1000/3125 | Loss: 0.0396

Epoch 10/30:  34%|███▎      | 1050/3125 [02:45<04:55,  7.01it/s, loss=0.0153]

Epoch 10 | Batch 1050/3125 | Loss: 0.0153

Epoch 10/30:  35%|███▌      | 1100/3125 [02:52<04:32,  7.42it/s, loss=0.0428]

Epoch 10 | Batch 1100/3125 | Loss: 0.0428

Epoch 10/30:  37%|███▋      | 1152/3125 [02:59<04:47,  6.86it/s, loss=0.0351]

Epoch 10 | Batch 1150/3125 | Loss: 0.0198

Epoch 10/30:  38%|███▊      | 1200/3125 [03:06<04:34,  7.00it/s, loss=0.0261]

Epoch 10 | Batch 1200/3125 | Loss: 0.0261

Epoch 10/30:  40%|████      | 1251/3125 [03:13<04:26,  7.02it/s, loss=0.0464]

Epoch 10 | Batch 1250/3125 | Loss: 0.0629

Epoch 10/30:  42%|████▏     | 1301/3125 [03:20<04:09,  7.31it/s, loss=0.0602]

Epoch 10 | Batch 1300/3125 | Loss: 0.0202

Epoch 10/30:  43%|████▎     | 1351/3125 [03:27<03:45,  7.86it/s, loss=0.0268]

Epoch 10 | Batch 1350/3125 | Loss: 0.0354

Epoch 10/30:  45%|████▍     | 1401/3125 [03:33<03:51,  7.45it/s, loss=0.0358]

Epoch 10 | Batch 1400/3125 | Loss: 0.0101

Epoch 10/30:  46%|████▋     | 1451/3125 [03:40<03:34,  7.81it/s, loss=0.0376]

Epoch 10 | Batch 1450/3125 | Loss: 0.0401

Epoch 10/30:  48%|████▊     | 1501/3125 [03:47<03:32,  7.63it/s, loss=0.0403]

Epoch 10 | Batch 1500/3125 | Loss: 0.0229

Epoch 10/30:  50%|████▉     | 1551/3125 [03:53<03:26,  7.61it/s, loss=0.0529]

Epoch 10 | Batch 1550/3125 | Loss: 0.0395

Epoch 10/30:  51%|█████     | 1601/3125 [04:00<03:21,  7.55it/s, loss=0.0345]

Epoch 10 | Batch 1600/3125 | Loss: 0.0248

Epoch 10/30:  53%|█████▎    | 1651/3125 [04:06<03:13,  7.63it/s, loss=0.0115]

Epoch 10 | Batch 1650/3125 | Loss: 0.0295

Epoch 10/30:  54%|█████▍    | 1701/3125 [04:13<03:01,  7.87it/s, loss=0.0624]

Epoch 10 | Batch 1700/3125 | Loss: 0.0429

Epoch 10/30:  56%|█████▌    | 1752/3125 [04:20<02:51,  8.02it/s, loss=0.0396]

Epoch 10 | Batch 1750/3125 | Loss: 0.0567

Epoch 10/30:  58%|█████▊    | 1802/3125 [04:26<03:01,  7.28it/s, loss=0.0709]

Epoch 10 | Batch 1800/3125 | Loss: 0.0299

Epoch 10/30:  59%|█████▉    | 1852/3125 [04:33<02:43,  7.77it/s, loss=0.068]

Epoch 10 | Batch 1850/3125 | Loss: 0.0414

Epoch 10/30:  61%|██████    | 1901/3125 [04:39<02:36,  7.81it/s, loss=0.0361]

Epoch 10 | Batch 1900/3125 | Loss: 0.0567

Epoch 10/30:  62%|██████▏   | 1951/3125 [04:46<02:38,  7.41it/s, loss=0.0508]

Epoch 10 | Batch 1950/3125 | Loss: 0.0195

Epoch 10/30:  64%|██████▍   | 2002/3125 [04:52<02:33,  7.34it/s, loss=0.0297]

Epoch 10 | Batch 2000/3125 | Loss: 0.0481

Epoch 10/30:  66%|██████▌   | 2052/3125 [04:59<02:15,  7.90it/s, loss=0.0312]

Epoch 10 | Batch 2050/3125 | Loss: 0.0415

Epoch 10/30:  67%|██████▋   | 2102/3125 [05:05<02:17,  7.43it/s, loss=0.0167]

Epoch 10 | Batch 2100/3125 | Loss: 0.0560

Epoch 10/30:  69%|██████▉   | 2152/3125 [05:12<02:01,  8.00it/s, loss=0.0297]

Epoch 10 | Batch 2150/3125 | Loss: 0.0226

Epoch 10/30:  70%|███████   | 2200/3125 [05:19<02:07,  7.25it/s, loss=0.019]

Epoch 10 | Batch 2200/3125 | Loss: 0.0190

Epoch 10/30:  72%|███████▏  | 2252/3125 [05:25<01:47,  8.10it/s, loss=0.0303]

Epoch 10 | Batch 2250/3125 | Loss: 0.0416

Epoch 10/30:  74%|███████▎  | 2302/3125 [05:32<01:42,  8.07it/s, loss=0.0138]

Epoch 10 | Batch 2300/3125 | Loss: 0.1020

Epoch 10/30:  75%|███████▌  | 2351/3125 [05:38<01:40,  7.68it/s, loss=0.0311]

Epoch 10 | Batch 2350/3125 | Loss: 0.0429

Epoch 10/30:  77%|███████▋  | 2402/3125 [05:44<01:31,  7.90it/s, loss=0.0409]

Epoch 10 | Batch 2400/3125 | Loss: 0.0254

Epoch 10/30:  78%|███████▊  | 2450/3125 [05:51<01:34,  7.14it/s, loss=0.0157]

Epoch 10 | Batch 2450/3125 | Loss: 0.0157

Epoch 10/30:  80%|████████  | 2502/3125 [05:57<01:15,  8.24it/s, loss=0.024]

Epoch 10 | Batch 2500/3125 | Loss: 0.0150

Epoch 10/30:  82%|████████▏ | 2552/3125 [06:03<01:07,  8.52it/s, loss=0.0565]

Epoch 10 | Batch 2550/3125 | Loss: 0.0382

Epoch 10/30:  83%|████████▎ | 2600/3125 [06:09<01:06,  7.88it/s, loss=0.0288]

Epoch 10 | Batch 2600/3125 | Loss: 0.0288

Epoch 10/30:  85%|████████▍ | 2652/3125 [06:16<00:57,  8.21it/s, loss=0.0224]

Epoch 10 | Batch 2650/3125 | Loss: 0.0399

Epoch 10/30:  86%|████████▋ | 2700/3125 [06:22<01:02,  6.75it/s, loss=0.0646]

Epoch 10 | Batch 2700/3125 | Loss: 0.0646

Epoch 10/30:  88%|████████▊ | 2752/3125 [06:29<00:47,  7.90it/s, loss=0.0165]

Epoch 10 | Batch 2750/3125 | Loss: 0.0154

Epoch 10/30:  90%|████████▉ | 2802/3125 [06:35<00:42,  7.52it/s, loss=0.0259]

Epoch 10 | Batch 2800/3125 | Loss: 0.0316

Epoch 10/30:  91%|█████████▏| 2852/3125 [06:42<00:33,  8.13it/s, loss=0.0333]

Epoch 10 | Batch 2850/3125 | Loss: 0.0309

Epoch 10/30:  93%|█████████▎| 2902/3125 [06:48<00:26,  8.27it/s, loss=0.0164]

Epoch 10 | Batch 2900/3125 | Loss: 0.0140

Epoch 10/30:  94%|█████████▍| 2950/3125 [06:54<00:24,  7.04it/s, loss=0.0291]

Epoch 10 | Batch 2950/3125 | Loss: 0.0291

Epoch 10/30:  96%|█████████▌| 3002/3125 [07:01<00:14,  8.49it/s, loss=0.0409]

Epoch 10 | Batch 3000/3125 | Loss: 0.0646

Epoch 10/30:  98%|█████████▊| 3052/3125 [07:07<00:09,  7.86it/s, loss=0.0189]

Epoch 10 | Batch 3050/3125 | Loss: 0.0141

Epoch 10/30:  99%|█████████▉| 3102/3125 [07:14<00:02,  7.74it/s, loss=0.013]

Epoch 10 | Batch 3100/3125 | Loss: 0.0352

Epoch 10/30: 100%|██████████| 3125/3125 [07:16<00:00,  7.15it/s, loss=0.0335]

Epoch [10/30] - Avg Loss: 0.0353

Epoch 11/30:   0%|          | 1/3125 [00:00<14:26,  3.61it/s, loss=0.0441]

Epoch 11 | Batch 0/3125 | Loss: 0.0355

Epoch 11/30:   2%|▏         | 52/3125 [00:06<06:18,  8.12it/s, loss=0.0337]

Epoch 11 | Batch 50/3125 | Loss: 0.0181

Epoch 11/30:   3%|▎         | 101/3125 [00:13<06:57,  7.25it/s, loss=0.0228]

Epoch 11 | Batch 100/3125 | Loss: 0.0401

Epoch 11/30:   5%|▍         | 151/3125 [00:19<06:07,  8.09it/s, loss=0.0217]

Epoch 11 | Batch 150/3125 | Loss: 0.0291

Epoch 11/30:   6%|▋         | 200/3125 [00:25<06:10,  7.90it/s, loss=0.0159]

Epoch 11 | Batch 200/3125 | Loss: 0.0159

Epoch 11/30:   8%|▊         | 251/3125 [00:32<06:04,  7.88it/s, loss=0.0495]

Epoch 11 | Batch 250/3125 | Loss: 0.0221

Epoch 11/30:  10%|▉         | 301/3125 [00:38<06:24,  7.34it/s, loss=0.0701]

Epoch 11 | Batch 300/3125 | Loss: 0.0221

Epoch 11/30:  11%|█         | 350/3125 [00:44<06:58,  6.64it/s, loss=0.0312]

Epoch 11 | Batch 350/3125 | Loss: 0.0312

Epoch 11/30:  13%|█▎        | 401/3125 [00:51<05:52,  7.73it/s, loss=0.0267]

Epoch 11 | Batch 400/3125 | Loss: 0.0347

Epoch 11/30:  14%|█▍        | 451/3125 [00:57<05:41,  7.82it/s, loss=0.00926]

Epoch 11 | Batch 450/3125 | Loss: 0.0277

Epoch 11/30:  16%|█▌        | 501/3125 [01:04<05:47,  7.55it/s, loss=0.0375]

Epoch 11 | Batch 500/3125 | Loss: 0.0378

Epoch 11/30:  18%|█▊        | 551/3125 [01:10<05:14,  8.19it/s, loss=0.0289]

Epoch 11 | Batch 550/3125 | Loss: 0.0470

Epoch 11/30:  19%|█▉        | 601/3125 [01:17<06:21,  6.62it/s, loss=0.0216]

Epoch 11 | Batch 600/3125 | Loss: 0.0588

Epoch 11/30:  21%|██        | 651/3125 [01:24<05:19,  7.75it/s, loss=0.0257]

Epoch 11 | Batch 650/3125 | Loss: 0.0183

Epoch 11/30:  22%|██▏       | 701/3125 [01:30<04:59,  8.08it/s, loss=0.0347]

Epoch 11 | Batch 700/3125 | Loss: 0.0143

Epoch 11/30:  24%|██▍       | 751/3125 [01:36<04:51,  8.13it/s, loss=0.0503]

Epoch 11 | Batch 750/3125 | Loss: 0.0322

Epoch 11/30:  26%|██▌       | 801/3125 [01:43<05:13,  7.41it/s, loss=0.021]

Epoch 11 | Batch 800/3125 | Loss: 0.0283

Epoch 11/30:  27%|██▋       | 851/3125 [01:49<04:44,  7.99it/s, loss=0.0172]

Epoch 11 | Batch 850/3125 | Loss: 0.0410

Epoch 11/30:  29%|██▉       | 901/3125 [01:56<04:55,  7.52it/s, loss=0.0107]

Epoch 11 | Batch 900/3125 | Loss: 0.0416

Epoch 11/30:  30%|███       | 951/3125 [02:02<04:30,  8.03it/s, loss=0.0595]

Epoch 11 | Batch 950/3125 | Loss: 0.0318

Epoch 11/30:  32%|███▏      | 1001/3125 [02:08<04:18,  8.20it/s, loss=0.0159]

Epoch 11 | Batch 1000/3125 | Loss: 0.0566

Epoch 11/30:  34%|███▎      | 1051/3125 [02:15<04:06,  8.41it/s, loss=0.0386]

Epoch 11 | Batch 1050/3125 | Loss: 0.0264

Epoch 11/30:  35%|███▌      | 1101/3125 [02:21<04:12,  8.01it/s, loss=0.0214]

Epoch 11 | Batch 1100/3125 | Loss: 0.0308

Epoch 11/30:  37%|███▋      | 1151/3125 [02:28<04:15,  7.73it/s, loss=0.0299]

Epoch 11 | Batch 1150/3125 | Loss: 0.0266

Epoch 11/30:  38%|███▊      | 1201/3125 [02:34<04:00,  8.01it/s, loss=0.0137]

Epoch 11 | Batch 1200/3125 | Loss: 0.0358

Epoch 11/30:  40%|████      | 1251/3125 [02:40<04:01,  7.75it/s, loss=0.0417]

Epoch 11 | Batch 1250/3125 | Loss: 0.0227

Epoch 11/30:  42%|████▏     | 1301/3125 [02:46<03:57,  7.67it/s, loss=0.0367]

Epoch 11 | Batch 1300/3125 | Loss: 0.0339

Epoch 11/30:  43%|████▎     | 1351/3125 [02:52<03:42,  7.98it/s, loss=0.0297]

Epoch 11 | Batch 1350/3125 | Loss: 0.0312

Epoch 11/30:  45%|████▍     | 1401/3125 [02:59<03:47,  7.59it/s, loss=0.0727]

Epoch 11 | Batch 1400/3125 | Loss: 0.0506

Epoch 11/30:  46%|████▋     | 1451/3125 [03:05<03:32,  7.88it/s, loss=0.0219]

Epoch 11 | Batch 1450/3125 | Loss: 0.0364

Epoch 11/30:  48%|████▊     | 1501/3125 [03:12<03:33,  7.60it/s, loss=0.0243]

Epoch 11 | Batch 1500/3125 | Loss: 0.0121

Epoch 11/30:  50%|████▉     | 1551/3125 [03:18<03:12,  8.18it/s, loss=0.021]

Epoch 11 | Batch 1550/3125 | Loss: 0.0373

Epoch 11/30:  51%|█████     | 1601/3125 [03:24<03:05,  8.21it/s, loss=0.0204]

Epoch 11 | Batch 1600/3125 | Loss: 0.0315

Epoch 11/30:  53%|█████▎    | 1651/3125 [03:31<03:47,  6.47it/s, loss=0.0281]

Epoch 11 | Batch 1650/3125 | Loss: 0.0317

Epoch 11/30:  54%|█████▍    | 1701/3125 [03:37<03:03,  7.75it/s, loss=0.0179]

Epoch 11 | Batch 1700/3125 | Loss: 0.0877

Epoch 11/30:  56%|█████▌    | 1751/3125 [03:43<02:42,  8.46it/s, loss=0.0497]

Epoch 11 | Batch 1750/3125 | Loss: 0.0291

Epoch 11/30:  58%|█████▊    | 1801/3125 [03:49<02:37,  8.39it/s, loss=0.0357]

Epoch 11 | Batch 1800/3125 | Loss: 0.0254

Epoch 11/30:  59%|█████▉    | 1851/3125 [03:55<02:37,  8.09it/s, loss=0.0657]

Epoch 11 | Batch 1850/3125 | Loss: 0.0206

Epoch 11/30:  61%|██████    | 1901/3125 [04:02<02:32,  8.03it/s, loss=0.0146]

Epoch 11 | Batch 1900/3125 | Loss: 0.0289

Epoch 11/30:  62%|██████▏   | 1951/3125 [04:08<02:34,  7.60it/s, loss=0.0081]

Epoch 11 | Batch 1950/3125 | Loss: 0.0309

Epoch 11/30:  64%|██████▍   | 2001/3125 [04:15<02:18,  8.09it/s, loss=0.0248]

Epoch 11 | Batch 2000/3125 | Loss: 0.0301

Epoch 11/30:  66%|██████▌   | 2051/3125 [04:21<02:17,  7.83it/s, loss=0.0234]

Epoch 11 | Batch 2050/3125 | Loss: 0.0464

Epoch 11/30:  67%|██████▋   | 2102/3125 [04:27<02:05,  8.13it/s, loss=0.0735]

Epoch 11 | Batch 2100/3125 | Loss: 0.0139

Epoch 11/30:  69%|██████▉   | 2152/3125 [04:33<01:52,  8.65it/s, loss=0.0639]

Epoch 11 | Batch 2150/3125 | Loss: 0.0238

Epoch 11/30:  70%|███████   | 2202/3125 [04:40<01:48,  8.50it/s, loss=0.0212]

Epoch 11 | Batch 2200/3125 | Loss: 0.0289

Epoch 11/30:  72%|███████▏  | 2252/3125 [04:46<01:41,  8.62it/s, loss=0.0278]

Epoch 11 | Batch 2250/3125 | Loss: 0.0331

Epoch 11/30:  74%|███████▎  | 2302/3125 [04:52<01:39,  8.26it/s, loss=0.0469]

Epoch 11 | Batch 2300/3125 | Loss: 0.0179

Epoch 11/30:  75%|███████▌  | 2352/3125 [04:58<01:35,  8.14it/s, loss=0.0141]

Epoch 11 | Batch 2350/3125 | Loss: 0.0138

Epoch 11/30:  77%|███████▋  | 2402/3125 [05:04<01:28,  8.14it/s, loss=0.0204]

Epoch 11 | Batch 2400/3125 | Loss: 0.0301

Epoch 11/30:  78%|███████▊  | 2450/3125 [05:11<01:39,  6.75it/s, loss=0.0329]

Epoch 11 | Batch 2450/3125 | Loss: 0.0329

Epoch 11/30:  80%|████████  | 2500/3125 [05:17<01:22,  7.54it/s, loss=0.0338]

Epoch 11 | Batch 2500/3125 | Loss: 0.0338

Epoch 11/30:  82%|████████▏ | 2552/3125 [05:24<01:12,  7.86it/s, loss=0.0456]

Epoch 11 | Batch 2550/3125 | Loss: 0.0513

Epoch 11/30:  83%|████████▎ | 2602/3125 [05:30<01:07,  7.77it/s, loss=0.0351]

Epoch 11 | Batch 2600/3125 | Loss: 0.0279

Epoch 11/30:  85%|████████▍ | 2652/3125 [05:36<00:57,  8.24it/s, loss=0.0269]

Epoch 11 | Batch 2650/3125 | Loss: 0.0171

Epoch 11/30:  86%|████████▋ | 2702/3125 [05:42<00:55,  7.64it/s, loss=0.0385]

Epoch 11 | Batch 2700/3125 | Loss: 0.0158

Epoch 11/30:  88%|████████▊ | 2752/3125 [05:49<00:45,  8.27it/s, loss=0.0144]

Epoch 11 | Batch 2750/3125 | Loss: 0.0285

Epoch 11/30:  90%|████████▉ | 2802/3125 [05:55<00:39,  8.11it/s, loss=0.0143]

Epoch 11 | Batch 2800/3125 | Loss: 0.0086

Epoch 11/30:  91%|█████████▏| 2852/3125 [06:01<00:33,  8.08it/s, loss=0.03]

Epoch 11 | Batch 2850/3125 | Loss: 0.0258

Epoch 11/30:  93%|█████████▎| 2902/3125 [06:08<00:28,  7.70it/s, loss=0.0163]

Epoch 11 | Batch 2900/3125 | Loss: 0.0413

Epoch 11/30:  94%|█████████▍| 2952/3125 [06:14<00:21,  8.19it/s, loss=0.0469]

Epoch 11 | Batch 2950/3125 | Loss: 0.0234

Epoch 11/30:  96%|█████████▌| 3002/3125 [06:21<00:15,  8.12it/s, loss=0.0307]

Epoch 11 | Batch 3000/3125 | Loss: 0.0153

Epoch 11/30:  98%|█████████▊| 3052/3125 [06:27<00:08,  8.45it/s, loss=0.0432]

Epoch 11 | Batch 3050/3125 | Loss: 0.0173

Epoch 11/30:  99%|█████████▉| 3102/3125 [06:33<00:02,  8.00it/s, loss=0.0223]

Epoch 11 | Batch 3100/3125 | Loss: 0.0329

Epoch 11/30: 100%|██████████| 3125/3125 [06:36<00:00,  7.89it/s, loss=0.0226]

Epoch [11/30] - Avg Loss: 0.0306

Epoch 12/30:   0%|          | 1/3125 [00:00<16:17,  3.20it/s, loss=0.0293]

Epoch 12 | Batch 0/3125 | Loss: 0.0216

Epoch 12/30:   2%|▏         | 52/3125 [00:06<06:05,  8.40it/s, loss=0.026]

Epoch 12 | Batch 50/3125 | Loss: 0.0804

Epoch 12/30:   3%|▎         | 101/3125 [00:12<06:07,  8.24it/s, loss=0.00523]

Epoch 12 | Batch 100/3125 | Loss: 0.0191

Epoch 12/30:   5%|▍         | 150/3125 [00:19<05:52,  8.44it/s, loss=0.0347]

Epoch 12 | Batch 150/3125 | Loss: 0.0347

Epoch 12/30:   6%|▋         | 202/3125 [00:25<06:06,  7.97it/s, loss=0.018]

Epoch 12 | Batch 200/3125 | Loss: 0.0635

Epoch 12/30:   8%|▊         | 252/3125 [00:31<06:05,  7.87it/s, loss=0.0209]

Epoch 12 | Batch 250/3125 | Loss: 0.0295

Epoch 12/30:  10%|▉         | 302/3125 [00:37<05:39,  8.32it/s, loss=0.0243]

Epoch 12 | Batch 300/3125 | Loss: 0.0145

Epoch 12/30:  11%|█▏        | 352/3125 [00:43<05:23,  8.58it/s, loss=0.0113]

Epoch 12 | Batch 350/3125 | Loss: 0.0172

Epoch 12/30:  13%|█▎        | 401/3125 [00:50<05:37,  8.06it/s, loss=0.0258]

Epoch 12 | Batch 400/3125 | Loss: 0.0151

Epoch 12/30:  14%|█▍        | 452/3125 [00:56<05:17,  8.43it/s, loss=0.022]

Epoch 12 | Batch 450/3125 | Loss: 0.0356

Epoch 12/30:  16%|█▌        | 502/3125 [01:02<05:28,  7.98it/s, loss=0.0339]

Epoch 12 | Batch 500/3125 | Loss: 0.0298

Epoch 12/30:  18%|█▊        | 552/3125 [01:08<05:21,  8.01it/s, loss=0.0206]

Epoch 12 | Batch 550/3125 | Loss: 0.0145

Epoch 12/30:  19%|█▉        | 602/3125 [01:14<05:01,  8.37it/s, loss=0.0356]

Epoch 12 | Batch 600/3125 | Loss: 0.0238

Epoch 12/30:  21%|██        | 650/3125 [01:21<05:56,  6.94it/s, loss=0.0218]

Epoch 12 | Batch 650/3125 | Loss: 0.0218

Epoch 12/30:  22%|██▏       | 702/3125 [01:27<05:07,  7.89it/s, loss=0.0261]

Epoch 12 | Batch 700/3125 | Loss: 0.0249

Epoch 12/30:  24%|██▍       | 750/3125 [01:34<04:58,  7.96it/s, loss=0.0283]

Epoch 12 | Batch 750/3125 | Loss: 0.0283

Epoch 12/30:  26%|██▌       | 802/3125 [01:40<05:04,  7.63it/s, loss=0.0417]

Epoch 12 | Batch 800/3125 | Loss: 0.0200

Epoch 12/30:  27%|██▋       | 852/3125 [01:46<04:45,  7.97it/s, loss=0.00968]

Epoch 12 | Batch 850/3125 | Loss: 0.0078

Epoch 12/30:  29%|██▉       | 900/3125 [01:52<04:40,  7.93it/s, loss=0.027]

Epoch 12 | Batch 900/3125 | Loss: 0.0270

Epoch 12/30:  30%|███       | 952/3125 [01:59<04:28,  8.09it/s, loss=0.0187]

Epoch 12 | Batch 950/3125 | Loss: 0.0113

Epoch 12/30:  32%|███▏      | 1002/3125 [02:05<04:09,  8.51it/s, loss=0.0171]

Epoch 12 | Batch 1000/3125 | Loss: 0.0366

Epoch 12/30:  34%|███▎      | 1051/3125 [02:11<04:29,  7.68it/s, loss=0.0324]

Epoch 12 | Batch 1050/3125 | Loss: 0.0369

Epoch 12/30:  35%|███▌      | 1102/3125 [02:17<04:13,  7.97it/s, loss=0.0195]

Epoch 12 | Batch 1100/3125 | Loss: 0.0134

Epoch 12/30:  37%|███▋      | 1151/3125 [02:23<03:56,  8.35it/s, loss=0.0347]

Epoch 12 | Batch 1150/3125 | Loss: 0.0291

Epoch 12/30:  38%|███▊      | 1201/3125 [02:30<04:14,  7.56it/s, loss=0.0181]

Epoch 12 | Batch 1200/3125 | Loss: 0.0208

Epoch 12/30:  40%|████      | 1251/3125 [02:37<03:43,  8.40it/s, loss=0.0139]

Epoch 12 | Batch 1250/3125 | Loss: 0.0087

Epoch 12/30:  42%|████▏     | 1301/3125 [02:43<03:49,  7.96it/s, loss=0.0202]

Epoch 12 | Batch 1300/3125 | Loss: 0.0732

Epoch 12/30:  43%|████▎     | 1351/3125 [02:49<03:41,  8.01it/s, loss=0.0252]

Epoch 12 | Batch 1350/3125 | Loss: 0.0247

Epoch 12/30:  45%|████▍     | 1401/3125 [02:55<03:30,  8.20it/s, loss=0.0277]

Epoch 12 | Batch 1400/3125 | Loss: 0.0356

Epoch 12/30:  46%|████▋     | 1451/3125 [03:02<04:12,  6.63it/s, loss=0.0134]

Epoch 12 | Batch 1450/3125 | Loss: 0.0753

Epoch 12/30:  48%|████▊     | 1501/3125 [03:08<03:29,  7.76it/s, loss=0.0112]

Epoch 12 | Batch 1500/3125 | Loss: 0.0345

Epoch 12/30:  50%|████▉     | 1551/3125 [03:14<03:12,  8.18it/s, loss=0.00946]

Epoch 12 | Batch 1550/3125 | Loss: 0.0175

Epoch 12/30:  51%|█████     | 1601/3125 [03:21<03:08,  8.07it/s, loss=0.0126]

Epoch 12 | Batch 1600/3125 | Loss: 0.0138

Epoch 12/30:  53%|█████▎    | 1651/3125 [03:27<03:01,  8.13it/s, loss=0.033]

Epoch 12 | Batch 1650/3125 | Loss: 0.0217

Epoch 12/30:  54%|█████▍    | 1701/3125 [03:33<02:58,  7.98it/s, loss=0.0124]

Epoch 12 | Batch 1700/3125 | Loss: 0.0278

Epoch 12/30:  56%|█████▌    | 1751/3125 [03:40<02:49,  8.10it/s, loss=0.0376]

Epoch 12 | Batch 1750/3125 | Loss: 0.0158

Epoch 12/30:  58%|█████▊    | 1801/3125 [03:46<02:41,  8.20it/s, loss=0.0144]

Epoch 12 | Batch 1800/3125 | Loss: 0.0356

Epoch 12/30:  59%|█████▉    | 1851/3125 [03:52<02:36,  8.12it/s, loss=0.0233]

Epoch 12 | Batch 1850/3125 | Loss: 0.0103

Epoch 12/30:  61%|██████    | 1901/3125 [03:58<02:36,  7.82it/s, loss=0.0108]

Epoch 12 | Batch 1900/3125 | Loss: 0.0319

Epoch 12/30:  62%|██████▏   | 1951/3125 [04:05<02:21,  8.28it/s, loss=0.038]

Epoch 12 | Batch 1950/3125 | Loss: 0.0081

Epoch 12/30:  64%|██████▍   | 2001/3125 [04:11<02:26,  7.69it/s, loss=0.0387]

Epoch 12 | Batch 2000/3125 | Loss: 0.0520

Epoch 12/30:  66%|██████▌   | 2051/3125 [04:17<02:07,  8.43it/s, loss=0.0355]

Epoch 12 | Batch 2050/3125 | Loss: 0.0099

Epoch 12/30:  67%|██████▋   | 2101/3125 [04:23<02:08,  7.99it/s, loss=0.0433]

Epoch 12 | Batch 2100/3125 | Loss: 0.0194

Epoch 12/30:  69%|██████▉   | 2151/3125 [04:30<02:01,  8.05it/s, loss=0.045]

Epoch 12 | Batch 2150/3125 | Loss: 0.0316

Epoch 12/30:  70%|███████   | 2201/3125 [04:36<01:57,  7.87it/s, loss=0.0258]

Epoch 12 | Batch 2200/3125 | Loss: 0.0413

Epoch 12/30:  72%|███████▏  | 2252/3125 [04:43<02:12,  6.57it/s, loss=0.033]

Epoch 12 | Batch 2250/3125 | Loss: 0.0103

Epoch 12/30:  74%|███████▎  | 2301/3125 [04:49<01:43,  7.96it/s, loss=0.063]

Epoch 12 | Batch 2300/3125 | Loss: 0.0072

Epoch 12/30:  75%|███████▌  | 2352/3125 [04:55<01:36,  8.01it/s, loss=0.0333]

Epoch 12 | Batch 2350/3125 | Loss: 0.0270

Epoch 12/30:  77%|███████▋  | 2401/3125 [05:01<01:35,  7.55it/s, loss=0.0334]

Epoch 12 | Batch 2400/3125 | Loss: 0.0084

Epoch 12/30:  78%|███████▊  | 2451/3125 [05:07<01:24,  7.95it/s, loss=0.0116]

Epoch 12 | Batch 2450/3125 | Loss: 0.0125

Epoch 12/30:  80%|████████  | 2502/3125 [05:14<01:33,  6.68it/s, loss=0.0171]

Epoch 12 | Batch 2500/3125 | Loss: 0.0443

Epoch 12/30:  82%|████████▏ | 2552/3125 [05:20<01:07,  8.49it/s, loss=0.0335]

Epoch 12 | Batch 2550/3125 | Loss: 0.0685

Epoch 12/30:  83%|████████▎ | 2602/3125 [05:26<01:04,  8.13it/s, loss=0.0127]

Epoch 12 | Batch 2600/3125 | Loss: 0.0138

Epoch 12/30:  85%|████████▍ | 2652/3125 [05:33<00:59,  7.98it/s, loss=0.0126]

Epoch 12 | Batch 2650/3125 | Loss: 0.0064

Epoch 12/30:  86%|████████▋ | 2700/3125 [05:39<00:50,  8.39it/s, loss=0.0217]

Epoch 12 | Batch 2700/3125 | Loss: 0.0217

Epoch 12/30:  88%|████████▊ | 2752/3125 [05:45<00:43,  8.64it/s, loss=0.0488]

Epoch 12 | Batch 2750/3125 | Loss: 0.0222

Epoch 12/30:  90%|████████▉ | 2802/3125 [05:52<00:39,  8.12it/s, loss=0.00746]

Epoch 12 | Batch 2800/3125 | Loss: 0.0162

Epoch 12/30:  91%|█████████▏| 2852/3125 [05:58<00:33,  8.21it/s, loss=0.014]

Epoch 12 | Batch 2850/3125 | Loss: 0.0228

Epoch 12/30:  93%|█████████▎| 2900/3125 [06:04<00:27,  8.10it/s, loss=0.0153]

Epoch 12 | Batch 2900/3125 | Loss: 0.0153

Epoch 12/30:  94%|█████████▍| 2952/3125 [06:10<00:20,  8.40it/s, loss=0.0179]

Epoch 12 | Batch 2950/3125 | Loss: 0.0615

Epoch 12/30:  96%|█████████▌| 3002/3125 [06:17<00:14,  8.37it/s, loss=0.02]

Epoch 12 | Batch 3000/3125 | Loss: 0.0075

Epoch 12/30:  98%|█████████▊| 3051/3125 [06:23<00:10,  7.14it/s, loss=0.026]

Epoch 12 | Batch 3050/3125 | Loss: 0.0742

Epoch 12/30:  99%|█████████▉| 3101/3125 [06:30<00:03,  7.71it/s, loss=0.034]

Epoch 12 | Batch 3100/3125 | Loss: 0.0112

Epoch 12/30: 100%|██████████| 3125/3125 [06:33<00:00,  7.95it/s, loss=0.0414]

Epoch [12/30] - Avg Loss: 0.0267

Epoch 13/30:   0%|          | 1/3125 [00:00<15:52,  3.28it/s, loss=0.0112]

Epoch 13 | Batch 0/3125 | Loss: 0.0154

Epoch 13/30:   2%|▏         | 52/3125 [00:06<06:43,  7.62it/s, loss=0.00989]

Epoch 13 | Batch 50/3125 | Loss: 0.0099

Epoch 13/30:   3%|▎         | 102/3125 [00:13<06:15,  8.05it/s, loss=0.0126]

Epoch 13 | Batch 100/3125 | Loss: 0.0164

Epoch 13/30:   5%|▍         | 152/3125 [00:19<06:18,  7.86it/s, loss=0.0136]

Epoch 13 | Batch 150/3125 | Loss: 0.0132

Epoch 13/30:   6%|▋         | 202/3125 [00:25<05:53,  8.26it/s, loss=0.0245]

Epoch 13 | Batch 200/3125 | Loss: 0.0267

Epoch 13/30:   8%|▊         | 252/3125 [00:32<05:50,  8.21it/s, loss=0.0617]

Epoch 13 | Batch 250/3125 | Loss: 0.0179

Epoch 13/30:  10%|▉         | 302/3125 [00:38<05:30,  8.54it/s, loss=0.0138]

Epoch 13 | Batch 300/3125 | Loss: 0.0348

Epoch 13/30:  11%|█         | 350/3125 [00:44<05:35,  8.28it/s, loss=0.0135]

Epoch 13 | Batch 350/3125 | Loss: 0.0135

Epoch 13/30:  13%|█▎        | 402/3125 [00:50<05:27,  8.33it/s, loss=0.0167]

Epoch 13 | Batch 400/3125 | Loss: 0.0106

Epoch 13/30:  14%|█▍        | 450/3125 [00:56<06:30,  6.85it/s, loss=0.0225]

Epoch 13 | Batch 450/3125 | Loss: 0.0225

Epoch 13/30:  16%|█▌        | 502/3125 [01:03<05:18,  8.24it/s, loss=0.0107]

Epoch 13 | Batch 500/3125 | Loss: 0.0148

Epoch 13/30:  18%|█▊        | 552/3125 [01:09<05:15,  8.14it/s, loss=0.04]

Epoch 13 | Batch 550/3125 | Loss: 0.0357

Epoch 13/30:  19%|█▉        | 602/3125 [01:15<05:00,  8.39it/s, loss=0.0188]

Epoch 13 | Batch 600/3125 | Loss: 0.0132

Epoch 13/30:  21%|██        | 652/3125 [01:21<04:51,  8.49it/s, loss=0.021]

Epoch 13 | Batch 650/3125 | Loss: 0.0180

Epoch 13/30:  22%|██▏       | 700/3125 [01:27<05:35,  7.22it/s, loss=0.0291]

Epoch 13 | Batch 700/3125 | Loss: 0.0291

Epoch 13/30:  24%|██▍       | 752/3125 [01:34<04:43,  8.37it/s, loss=0.00648]

Epoch 13 | Batch 750/3125 | Loss: 0.0420

Epoch 13/30:  26%|██▌       | 802/3125 [01:40<04:47,  8.08it/s, loss=0.0133]

Epoch 13 | Batch 800/3125 | Loss: 0.0305

Epoch 13/30:  27%|██▋       | 852/3125 [01:46<04:41,  8.07it/s, loss=0.0538]

Epoch 13 | Batch 850/3125 | Loss: 0.0117

Epoch 13/30:  29%|██▉       | 902/3125 [01:53<04:37,  8.01it/s, loss=0.0435]

Epoch 13 | Batch 900/3125 | Loss: 0.0309

Epoch 13/30:  30%|███       | 952/3125 [01:59<04:36,  7.87it/s, loss=0.0328]

Epoch 13 | Batch 950/3125 | Loss: 0.0160

Epoch 13/30:  32%|███▏      | 1002/3125 [02:05<04:17,  8.23it/s, loss=0.0107]

Epoch 13 | Batch 1000/3125 | Loss: 0.0212

Epoch 13/30:  34%|███▎      | 1052/3125 [02:12<04:13,  8.18it/s, loss=0.0199]

Epoch 13 | Batch 1050/3125 | Loss: 0.0181

Epoch 13/30:  35%|███▌      | 1102/3125 [02:18<04:05,  8.25it/s, loss=0.0117]

Epoch 13 | Batch 1100/3125 | Loss: 0.0139

Epoch 13/30:  37%|███▋      | 1152/3125 [02:24<04:00,  8.19it/s, loss=0.00622]

Epoch 13 | Batch 1150/3125 | Loss: 0.0200

Epoch 13/30:  38%|███▊      | 1202/3125 [02:30<03:59,  8.03it/s, loss=0.00732]

Epoch 13 | Batch 1200/3125 | Loss: 0.0464

Epoch 13/30:  40%|████      | 1252/3125 [02:37<04:15,  7.32it/s, loss=0.0209]

Epoch 13 | Batch 1250/3125 | Loss: 0.0357

Epoch 13/30:  42%|████▏     | 1302/3125 [02:43<03:32,  8.56it/s, loss=0.0203]

Epoch 13 | Batch 1300/3125 | Loss: 0.0556

Epoch 13/30:  43%|████▎     | 1352/3125 [02:49<03:35,  8.22it/s, loss=0.0225]

Epoch 13 | Batch 1350/3125 | Loss: 0.0096

Epoch 13/30:  45%|████▍     | 1402/3125 [02:56<03:39,  7.86it/s, loss=0.0125]

Epoch 13 | Batch 1400/3125 | Loss: 0.0367

Epoch 13/30:  46%|████▋     | 1452/3125 [03:02<03:17,  8.48it/s, loss=0.0128]

Epoch 13 | Batch 1450/3125 | Loss: 0.0330

Epoch 13/30:  48%|████▊     | 1502/3125 [03:08<03:20,  8.10it/s, loss=0.00968]

Epoch 13 | Batch 1500/3125 | Loss: 0.0327

Epoch 13/30:  50%|████▉     | 1551/3125 [03:14<03:09,  8.30it/s, loss=0.02]

Epoch 13 | Batch 1550/3125 | Loss: 0.0487

Epoch 13/30:  51%|█████     | 1601/3125 [03:21<03:00,  8.46it/s, loss=0.0134]

Epoch 13 | Batch 1600/3125 | Loss: 0.0113

Epoch 13/30:  53%|█████▎    | 1651/3125 [03:26<02:55,  8.40it/s, loss=0.0266]

Epoch 13 | Batch 1650/3125 | Loss: 0.0218

Epoch 13/30:  54%|█████▍    | 1702/3125 [03:33<02:51,  8.32it/s, loss=0.0226]

Epoch 13 | Batch 1700/3125 | Loss: 0.0108

Epoch 13/30:  56%|█████▌    | 1751/3125 [03:39<02:56,  7.79it/s, loss=0.0396]

Epoch 13 | Batch 1750/3125 | Loss: 0.0199

Epoch 13/30:  58%|█████▊    | 1801/3125 [03:45<03:11,  6.92it/s, loss=0.0144]

Epoch 13 | Batch 1800/3125 | Loss: 0.0570

Epoch 13/30:  59%|█████▉    | 1851/3125 [03:52<02:32,  8.33it/s, loss=0.0497]

Epoch 13 | Batch 1850/3125 | Loss: 0.0359

Epoch 13/30:  61%|██████    | 1901/3125 [03:58<02:28,  8.23it/s, loss=0.0302]

Epoch 13 | Batch 1900/3125 | Loss: 0.0039

Epoch 13/30:  62%|██████▏   | 1952/3125 [04:04<02:26,  8.00it/s, loss=0.0225]

Epoch 13 | Batch 1950/3125 | Loss: 0.0398

Epoch 13/30:  64%|██████▍   | 2002/3125 [04:10<02:19,  8.03it/s, loss=0.0676]

Epoch 13 | Batch 2000/3125 | Loss: 0.0138

Epoch 13/30:  66%|██████▌   | 2052/3125 [04:16<02:10,  8.24it/s, loss=0.0205]

Epoch 13 | Batch 2050/3125 | Loss: 0.0254

Epoch 13/30:  67%|██████▋   | 2102/3125 [04:23<02:10,  7.87it/s, loss=0.0299]

Epoch 13 | Batch 2100/3125 | Loss: 0.0124

Epoch 13/30:  69%|██████▉   | 2152/3125 [04:29<02:06,  7.71it/s, loss=0.0244]

Epoch 13 | Batch 2150/3125 | Loss: 0.0384

Epoch 13/30:  70%|███████   | 2202/3125 [04:35<01:55,  8.00it/s, loss=0.0105]

Epoch 13 | Batch 2200/3125 | Loss: 0.0566

Epoch 13/30:  72%|███████▏  | 2251/3125 [04:41<01:47,  8.15it/s, loss=0.0221]

Epoch 13 | Batch 2250/3125 | Loss: 0.0226

Epoch 13/30:  74%|███████▎  | 2302/3125 [04:48<01:48,  7.60it/s, loss=0.0354]

Epoch 13 | Batch 2300/3125 | Loss: 0.0579

Epoch 13/30:  75%|███████▌  | 2350/3125 [04:55<01:55,  6.74it/s, loss=0.0113]

Epoch 13 | Batch 2350/3125 | Loss: 0.0113

Epoch 13/30:  77%|███████▋  | 2402/3125 [05:01<01:30,  7.98it/s, loss=0.0314]

Epoch 13 | Batch 2400/3125 | Loss: 0.0060

Epoch 13/30:  78%|███████▊  | 2452/3125 [05:07<01:25,  7.90it/s, loss=0.0361]

Epoch 13 | Batch 2450/3125 | Loss: 0.0194

Epoch 13/30:  80%|████████  | 2502/3125 [05:13<01:13,  8.53it/s, loss=0.0356]

Epoch 13 | Batch 2500/3125 | Loss: 0.0124

Epoch 13/30:  82%|████████▏ | 2552/3125 [05:20<01:10,  8.08it/s, loss=0.0321]

Epoch 13 | Batch 2550/3125 | Loss: 0.0252

Epoch 13/30:  83%|████████▎ | 2600/3125 [05:26<01:11,  7.34it/s, loss=0.00952]

Epoch 13 | Batch 2600/3125 | Loss: 0.0095

Epoch 13/30:  85%|████████▍ | 2652/3125 [05:33<00:59,  7.90it/s, loss=0.00631]

Epoch 13 | Batch 2650/3125 | Loss: 0.0109

Epoch 13/30:  86%|████████▋ | 2700/3125 [05:39<00:52,  8.03it/s, loss=0.0322]

Epoch 13 | Batch 2700/3125 | Loss: 0.0322

Epoch 13/30:  88%|████████▊ | 2752/3125 [05:46<00:47,  7.88it/s, loss=0.0224]

Epoch 13 | Batch 2750/3125 | Loss: 0.0095

Epoch 13/30:  90%|████████▉ | 2802/3125 [05:52<00:38,  8.41it/s, loss=0.0115]

Epoch 13 | Batch 2800/3125 | Loss: 0.0345

Epoch 13/30:  91%|█████████▏| 2852/3125 [05:58<00:36,  7.56it/s, loss=0.0292]

Epoch 13 | Batch 2850/3125 | Loss: 0.0101

Epoch 13/30:  93%|█████████▎| 2901/3125 [06:05<00:31,  7.03it/s, loss=0.0215]

Epoch 13 | Batch 2900/3125 | Loss: 0.0154

Epoch 13/30:  94%|█████████▍| 2951/3125 [06:12<00:21,  7.95it/s, loss=0.0119]

Epoch 13 | Batch 2950/3125 | Loss: 0.0139

Epoch 13/30:  96%|█████████▌| 3001/3125 [06:18<00:14,  8.31it/s, loss=0.0177]

Epoch 13 | Batch 3000/3125 | Loss: 0.0116

Epoch 13/30:  98%|█████████▊| 3052/3125 [06:24<00:09,  7.88it/s, loss=0.00976]

Epoch 13 | Batch 3050/3125 | Loss: 0.0241

Epoch 13/30:  99%|█████████▉| 3101/3125 [06:31<00:03,  7.54it/s, loss=0.0197]

Epoch 13 | Batch 3100/3125 | Loss: 0.0136

Epoch 13/30: 100%|██████████| 3125/3125 [06:34<00:00,  7.92it/s, loss=0.0377]

Epoch [13/30] - Avg Loss: 0.0234

Epoch 14/30:   0%|          | 1/3125 [00:00<18:10,  2.86it/s, loss=0.0118]

Epoch 14 | Batch 0/3125 | Loss: 0.0150

Epoch 14/30:   2%|▏         | 51/3125 [00:07<06:11,  8.27it/s, loss=0.016]

Epoch 14 | Batch 50/3125 | Loss: 0.0126

Epoch 14/30:   3%|▎         | 101/3125 [00:13<06:24,  7.87it/s, loss=0.0287]

Epoch 14 | Batch 100/3125 | Loss: 0.0130

Epoch 14/30:   5%|▍         | 151/3125 [00:19<06:19,  7.83it/s, loss=0.0115]

Epoch 14 | Batch 150/3125 | Loss: 0.0271

Epoch 14/30:   6%|▋         | 201/3125 [00:26<06:20,  7.68it/s, loss=0.00533]

Epoch 14 | Batch 200/3125 | Loss: 0.0217

Epoch 14/30:   8%|▊         | 251/3125 [00:32<05:49,  8.21it/s, loss=0.0541]

Epoch 14 | Batch 250/3125 | Loss: 0.0226

Epoch 14/30:  10%|▉         | 301/3125 [00:39<05:28,  8.61it/s, loss=0.028]

Epoch 14 | Batch 300/3125 | Loss: 0.0037

Epoch 14/30:  11%|█         | 351/3125 [00:45<06:11,  7.47it/s, loss=0.0142]

Epoch 14 | Batch 350/3125 | Loss: 0.0149

Epoch 14/30:  13%|█▎        | 401/3125 [00:52<05:35,  8.12it/s, loss=0.0055]

Epoch 14 | Batch 400/3125 | Loss: 0.0245

Epoch 14/30:  14%|█▍        | 451/3125 [00:58<05:26,  8.20it/s, loss=0.0688]

Epoch 14 | Batch 450/3125 | Loss: 0.0177

Epoch 14/30:  16%|█▌        | 501/3125 [01:04<05:35,  7.81it/s, loss=0.0289]

Epoch 14 | Batch 500/3125 | Loss: 0.0136

Epoch 14/30:  18%|█▊        | 551/3125 [01:11<05:35,  7.68it/s, loss=0.0221]

Epoch 14 | Batch 550/3125 | Loss: 0.0165

Epoch 14/30:  19%|█▉        | 601/3125 [01:18<05:46,  7.28it/s, loss=0.00855]

Epoch 14 | Batch 600/3125 | Loss: 0.0275

Epoch 14/30:  21%|██        | 651/3125 [01:24<05:13,  7.90it/s, loss=0.0245]

Epoch 14 | Batch 650/3125 | Loss: 0.0154

Epoch 14/30:  22%|██▏       | 701/3125 [01:31<05:28,  7.39it/s, loss=0.00816]

Epoch 14 | Batch 700/3125 | Loss: 0.0233

Epoch 14/30:  24%|██▍       | 750/3125 [01:37<04:59,  7.93it/s, loss=0.0114]

Epoch 14 | Batch 750/3125 | Loss: 0.0114

Epoch 14/30:  26%|██▌       | 802/3125 [01:45<05:49,  6.65it/s, loss=0.0126]

Epoch 14 | Batch 800/3125 | Loss: 0.0094

Epoch 14/30:  27%|██▋       | 852/3125 [01:51<04:42,  8.06it/s, loss=0.0238]

Epoch 14 | Batch 850/3125 | Loss: 0.0380

Epoch 14/30:  29%|██▉       | 900/3125 [01:58<04:50,  7.67it/s, loss=0.0174]

Epoch 14 | Batch 900/3125 | Loss: 0.0174

Epoch 14/30:  30%|███       | 950/3125 [02:04<04:48,  7.54it/s, loss=0.0178]

Epoch 14 | Batch 950/3125 | Loss: 0.0178

Epoch 14/30:  32%|███▏      | 1002/3125 [02:11<04:26,  7.97it/s, loss=0.0352]

Epoch 14 | Batch 1000/3125 | Loss: 0.0244

Epoch 14/30:  34%|███▎      | 1050/3125 [02:18<05:29,  6.30it/s, loss=0.0218]

Epoch 14 | Batch 1050/3125 | Loss: 0.0218

Epoch 14/30:  35%|███▌      | 1102/3125 [02:25<04:27,  7.55it/s, loss=0.00448]

Epoch 14 | Batch 1100/3125 | Loss: 0.0130

Epoch 14/30:  37%|███▋      | 1152/3125 [02:31<04:19,  7.62it/s, loss=0.00545]

Epoch 14 | Batch 1150/3125 | Loss: 0.0138

Epoch 14/30:  38%|███▊      | 1200/3125 [02:37<03:44,  8.57it/s, loss=0.00615]

Epoch 14 | Batch 1200/3125 | Loss: 0.0062

Epoch 14/30:  40%|████      | 1252/3125 [02:44<03:52,  8.05it/s, loss=0.0428]

Epoch 14 | Batch 1250/3125 | Loss: 0.0085

Epoch 14/30:  42%|████▏     | 1300/3125 [02:50<04:13,  7.20it/s, loss=0.0103]

Epoch 14 | Batch 1300/3125 | Loss: 0.0103

Epoch 14/30:  43%|████▎     | 1351/3125 [02:57<03:48,  7.75it/s, loss=0.0146]

Epoch 14 | Batch 1350/3125 | Loss: 0.0138

Epoch 14/30:  45%|████▍     | 1401/3125 [03:03<03:41,  7.79it/s, loss=0.0274]

Epoch 14 | Batch 1400/3125 | Loss: 0.0344

Epoch 14/30:  46%|████▋     | 1451/3125 [03:09<03:23,  8.23it/s, loss=0.0214]

Epoch 14 | Batch 1450/3125 | Loss: 0.0075

Epoch 14/30:  48%|████▊     | 1501/3125 [03:16<03:24,  7.93it/s, loss=0.00971]

Epoch 14 | Batch 1500/3125 | Loss: 0.0289

Epoch 14/30:  50%|████▉     | 1551/3125 [03:22<03:29,  7.51it/s, loss=0.0186]

Epoch 14 | Batch 1550/3125 | Loss: 0.0095

Epoch 14/30:  51%|█████     | 1601/3125 [03:29<03:20,  7.59it/s, loss=0.0395]

Epoch 14 | Batch 1600/3125 | Loss: 0.0126

Epoch 14/30:  53%|█████▎    | 1651/3125 [03:35<03:06,  7.89it/s, loss=0.0683]

Epoch 14 | Batch 1650/3125 | Loss: 0.0026

Epoch 14/30:  54%|█████▍    | 1701/3125 [03:41<02:49,  8.42it/s, loss=0.0219]

Epoch 14 | Batch 1700/3125 | Loss: 0.0034

Epoch 14/30:  56%|█████▌    | 1751/3125 [03:48<02:51,  8.02it/s, loss=0.0337]

Epoch 14 | Batch 1750/3125 | Loss: 0.0328

Epoch 14/30:  58%|█████▊    | 1801/3125 [03:54<02:40,  8.27it/s, loss=0.0209]

Epoch 14 | Batch 1800/3125 | Loss: 0.0658

Epoch 14/30:  59%|█████▉    | 1852/3125 [04:01<03:04,  6.89it/s, loss=0.017]

Epoch 14 | Batch 1850/3125 | Loss: 0.0128

Epoch 14/30:  61%|██████    | 1902/3125 [04:08<02:50,  7.19it/s, loss=0.0612]

Epoch 14 | Batch 1900/3125 | Loss: 0.0292

Epoch 14/30:  62%|██████▏   | 1952/3125 [04:14<02:28,  7.90it/s, loss=0.00514]

Epoch 14 | Batch 1950/3125 | Loss: 0.0079

Epoch 14/30:  64%|██████▍   | 2002/3125 [04:21<02:12,  8.45it/s, loss=0.0263]

Epoch 14 | Batch 2000/3125 | Loss: 0.0313

Epoch 14/30:  66%|██████▌   | 2052/3125 [04:27<02:22,  7.53it/s, loss=0.0461]

Epoch 14 | Batch 2050/3125 | Loss: 0.0321

Epoch 14/30:  67%|██████▋   | 2100/3125 [04:34<02:50,  6.00it/s, loss=0.0169]

Epoch 14 | Batch 2100/3125 | Loss: 0.0169

Epoch 14/30:  69%|██████▉   | 2150/3125 [04:40<01:57,  8.27it/s, loss=0.0194]

Epoch 14 | Batch 2150/3125 | Loss: 0.0194

Epoch 14/30:  70%|███████   | 2200/3125 [04:47<01:49,  8.45it/s, loss=0.0271]

Epoch 14 | Batch 2200/3125 | Loss: 0.0271

Epoch 14/30:  72%|███████▏  | 2252/3125 [04:53<01:54,  7.65it/s, loss=0.0186]

Epoch 14 | Batch 2250/3125 | Loss: 0.0190

Epoch 14/30:  74%|███████▎  | 2302/3125 [04:59<01:46,  7.74it/s, loss=0.0159]

Epoch 14 | Batch 2300/3125 | Loss: 0.0175

Epoch 14/30:  75%|███████▌  | 2350/3125 [05:06<01:42,  7.54it/s, loss=0.0462]

Epoch 14 | Batch 2350/3125 | Loss: 0.0462

Epoch 14/30:  77%|███████▋  | 2402/3125 [05:13<01:29,  8.04it/s, loss=0.00312]

Epoch 14 | Batch 2400/3125 | Loss: 0.0368

Epoch 14/30:  78%|███████▊  | 2452/3125 [05:19<01:25,  7.85it/s, loss=0.0442]

Epoch 14 | Batch 2450/3125 | Loss: 0.0282

Epoch 14/30:  80%|████████  | 2500/3125 [05:26<01:28,  7.04it/s, loss=0.0186]

Epoch 14 | Batch 2500/3125 | Loss: 0.0186

Epoch 14/30:  82%|████████▏ | 2552/3125 [05:32<01:11,  8.04it/s, loss=0.0395]

Epoch 14 | Batch 2550/3125 | Loss: 0.0240

Epoch 14/30:  83%|████████▎ | 2602/3125 [05:39<01:07,  7.79it/s, loss=0.0206]

Epoch 14 | Batch 2600/3125 | Loss: 0.0379

Epoch 14/30:  85%|████████▍ | 2652/3125 [05:45<00:57,  8.27it/s, loss=0.0188]

Epoch 14 | Batch 2650/3125 | Loss: 0.0089

Epoch 14/30:  86%|████████▋ | 2701/3125 [05:51<00:52,  8.13it/s, loss=0.0363]

Epoch 14 | Batch 2700/3125 | Loss: 0.0142

Epoch 14/30:  88%|████████▊ | 2751/3125 [05:58<00:47,  7.86it/s, loss=0.0122]

Epoch 14 | Batch 2750/3125 | Loss: 0.0024

Epoch 14/30:  90%|████████▉ | 2801/3125 [06:04<00:44,  7.27it/s, loss=0.0168]

Epoch 14 | Batch 2800/3125 | Loss: 0.0119

Epoch 14/30:  91%|█████████ | 2851/3125 [06:10<00:33,  8.13it/s, loss=0.0118]

Epoch 14 | Batch 2850/3125 | Loss: 0.0739

Epoch 14/30:  93%|█████████▎| 2901/3125 [06:17<00:33,  6.74it/s, loss=0.0161]

Epoch 14 | Batch 2900/3125 | Loss: 0.0286

Epoch 14/30:  94%|█████████▍| 2951/3125 [06:24<00:24,  7.12it/s, loss=0.0223]

Epoch 14 | Batch 2950/3125 | Loss: 0.0279

Epoch 14/30:  96%|█████████▌| 3001/3125 [06:30<00:14,  8.28it/s, loss=0.0269]

Epoch 14 | Batch 3000/3125 | Loss: 0.0401

Epoch 14/30:  98%|█████████▊| 3051/3125 [06:36<00:09,  8.05it/s, loss=0.00988]

Epoch 14 | Batch 3050/3125 | Loss: 0.0214

Epoch 14/30:  99%|█████████▉| 3101/3125 [06:42<00:02,  8.13it/s, loss=0.00839]

Epoch 14 | Batch 3100/3125 | Loss: 0.0119

Epoch 14/30: 100%|██████████| 3125/3125 [06:45<00:00,  7.70it/s, loss=0.00312]

Epoch [14/30] - Avg Loss: 0.0206

Epoch 15/30:   0%|          | 1/3125 [00:00<14:38,  3.55it/s, loss=0.0198]

Epoch 15 | Batch 0/3125 | Loss: 0.0140

Epoch 15/30:   2%|▏         | 51/3125 [00:06<07:14,  7.08it/s, loss=0.0131]

Epoch 15 | Batch 50/3125 | Loss: 0.0135

Epoch 15/30:   3%|▎         | 101/3125 [00:13<06:01,  8.36it/s, loss=0.0458]

Epoch 15 | Batch 100/3125 | Loss: 0.0112

Epoch 15/30:   5%|▍         | 151/3125 [00:19<06:01,  8.23it/s, loss=0.0301]

Epoch 15 | Batch 150/3125 | Loss: 0.0358

Epoch 15/30:   6%|▋         | 201/3125 [00:25<05:56,  8.19it/s, loss=0.00781]

Epoch 15 | Batch 200/3125 | Loss: 0.0082

Epoch 15/30:   8%|▊         | 251/3125 [00:32<05:51,  8.18it/s, loss=0.0171]

Epoch 15 | Batch 250/3125 | Loss: 0.0074

Epoch 15/30:  10%|▉         | 301/3125 [00:38<06:24,  7.35it/s, loss=0.03]

Epoch 15 | Batch 300/3125 | Loss: 0.0237

Epoch 15/30:  11%|█         | 351/3125 [00:44<05:43,  8.07it/s, loss=0.0506]

Epoch 15 | Batch 350/3125 | Loss: 0.0254

Epoch 15/30:  13%|█▎        | 401/3125 [00:51<05:24,  8.39it/s, loss=0.0348]

Epoch 15 | Batch 400/3125 | Loss: 0.0087

Epoch 15/30:  14%|█▍        | 451/3125 [00:57<05:35,  7.96it/s, loss=0.0519]

Epoch 15 | Batch 450/3125 | Loss: 0.0511

Epoch 15/30:  16%|█▌        | 501/3125 [01:03<05:18,  8.24it/s, loss=0.00669]

Epoch 15 | Batch 500/3125 | Loss: 0.0101

Epoch 15/30:  18%|█▊        | 552/3125 [01:09<05:12,  8.22it/s, loss=0.0115]

Epoch 15 | Batch 550/3125 | Loss: 0.0143

Epoch 15/30:  19%|█▉        | 601/3125 [01:16<06:05,  6.90it/s, loss=0.0394]

Epoch 15 | Batch 600/3125 | Loss: 0.0151

Epoch 15/30:  21%|██        | 652/3125 [01:22<04:54,  8.40it/s, loss=0.0576]

Epoch 15 | Batch 650/3125 | Loss: 0.0116

Epoch 15/30:  22%|██▏       | 702/3125 [01:28<05:31,  7.32it/s, loss=0.0105]

Epoch 15 | Batch 700/3125 | Loss: 0.0118

Epoch 15/30:  24%|██▍       | 751/3125 [01:35<04:57,  7.98it/s, loss=0.0213]

Epoch 15 | Batch 750/3125 | Loss: 0.0100

Epoch 15/30:  26%|██▌       | 801/3125 [01:41<04:48,  8.04it/s, loss=0.0125]

Epoch 15 | Batch 800/3125 | Loss: 0.0059

Epoch 15/30:  27%|██▋       | 851/3125 [01:48<05:41,  6.66it/s, loss=0.00892]

Epoch 15 | Batch 850/3125 | Loss: 0.0123

Epoch 15/30:  29%|██▉       | 901/3125 [01:54<04:33,  8.14it/s, loss=0.0177]

Epoch 15 | Batch 900/3125 | Loss: 0.0117

Epoch 15/30:  30%|███       | 951/3125 [02:01<04:37,  7.84it/s, loss=0.0125]

Epoch 15 | Batch 950/3125 | Loss: 0.0038

Epoch 15/30:  32%|███▏      | 1001/3125 [02:07<04:35,  7.71it/s, loss=0.0208]

Epoch 15 | Batch 1000/3125 | Loss: 0.0116

Epoch 15/30:  34%|███▎      | 1051/3125 [02:13<04:23,  7.86it/s, loss=0.0656]

Epoch 15 | Batch 1050/3125 | Loss: 0.0084

Epoch 15/30:  35%|███▌      | 1101/3125 [02:19<04:10,  8.07it/s, loss=0.00752]

Epoch 15 | Batch 1100/3125 | Loss: 0.0274

Epoch 15/30:  37%|███▋      | 1152/3125 [02:26<03:54,  8.43it/s, loss=0.0476]

Epoch 15 | Batch 1150/3125 | Loss: 0.0136

Epoch 15/30:  38%|███▊      | 1202/3125 [02:33<03:49,  8.36it/s, loss=0.00982]

Epoch 15 | Batch 1200/3125 | Loss: 0.0176

Epoch 15/30:  40%|████      | 1252/3125 [02:39<03:56,  7.92it/s, loss=0.0128]

Epoch 15 | Batch 1250/3125 | Loss: 0.0068

Epoch 15/30:  42%|████▏     | 1302/3125 [02:45<03:44,  8.13it/s, loss=0.00564]

Epoch 15 | Batch 1300/3125 | Loss: 0.0371

Epoch 15/30:  43%|████▎     | 1352/3125 [02:51<03:42,  7.96it/s, loss=0.0246]

Epoch 15 | Batch 1350/3125 | Loss: 0.0090

Epoch 15/30:  45%|████▍     | 1400/3125 [02:57<04:35,  6.26it/s, loss=0.0102]

Epoch 15 | Batch 1400/3125 | Loss: 0.0102

Epoch 15/30:  46%|████▋     | 1452/3125 [03:04<03:25,  8.15it/s, loss=0.0168]

Epoch 15 | Batch 1450/3125 | Loss: 0.0230

Epoch 15/30:  48%|████▊     | 1502/3125 [03:10<03:17,  8.20it/s, loss=0.0016]

Epoch 15 | Batch 1500/3125 | Loss: 0.0112

Epoch 15/30:  50%|████▉     | 1550/3125 [03:16<03:06,  8.44it/s, loss=0.00778]

Epoch 15 | Batch 1550/3125 | Loss: 0.0078

Epoch 15/30:  51%|█████▏    | 1602/3125 [03:23<03:20,  7.59it/s, loss=0.0139]

Epoch 15 | Batch 1600/3125 | Loss: 0.0031

Epoch 15/30:  53%|█████▎    | 1652/3125 [03:29<03:03,  8.04it/s, loss=0.0192]

Epoch 15 | Batch 1650/3125 | Loss: 0.0107

Epoch 15/30:  54%|█████▍    | 1701/3125 [03:36<02:59,  7.94it/s, loss=0.0135]

Epoch 15 | Batch 1700/3125 | Loss: 0.0063

Epoch 15/30:  56%|█████▌    | 1751/3125 [03:42<02:55,  7.83it/s, loss=0.0157]

Epoch 15 | Batch 1750/3125 | Loss: 0.0442

Epoch 15/30:  58%|█████▊    | 1801/3125 [03:49<02:57,  7.45it/s, loss=0.0145]

Epoch 15 | Batch 1800/3125 | Loss: 0.0118

Epoch 15/30:  59%|█████▉    | 1851/3125 [03:55<02:35,  8.21it/s, loss=0.0191]

Epoch 15 | Batch 1850/3125 | Loss: 0.0058

Epoch 15/30:  61%|██████    | 1901/3125 [04:01<02:32,  8.03it/s, loss=0.00784]

Epoch 15 | Batch 1900/3125 | Loss: 0.0270

Epoch 15/30:  62%|██████▏   | 1951/3125 [04:08<02:44,  7.12it/s, loss=0.0141]

Epoch 15 | Batch 1950/3125 | Loss: 0.0240

Epoch 15/30:  64%|██████▍   | 2001/3125 [04:14<02:14,  8.35it/s, loss=0.0275]

Epoch 15 | Batch 2000/3125 | Loss: 0.0159

Epoch 15/30:  66%|██████▌   | 2051/3125 [04:20<02:15,  7.91it/s, loss=0.0156]

Epoch 15 | Batch 2050/3125 | Loss: 0.0280

Epoch 15/30:  67%|██████▋   | 2101/3125 [04:26<02:05,  8.15it/s, loss=0.00598]

Epoch 15 | Batch 2100/3125 | Loss: 0.0134

Epoch 15/30:  69%|██████▉   | 2152/3125 [04:32<01:59,  8.12it/s, loss=0.00783]

Epoch 15 | Batch 2150/3125 | Loss: 0.0149

Epoch 15/30:  70%|███████   | 2200/3125 [04:39<02:13,  6.93it/s, loss=0.00641]

Epoch 15 | Batch 2200/3125 | Loss: 0.0064

Epoch 15/30:  72%|███████▏  | 2252/3125 [04:45<01:47,  8.14it/s, loss=0.0172]

Epoch 15 | Batch 2250/3125 | Loss: 0.0062

Epoch 15/30:  74%|███████▎  | 2302/3125 [04:51<01:52,  7.32it/s, loss=0.0217]

Epoch 15 | Batch 2300/3125 | Loss: 0.0185

Epoch 15/30:  75%|███████▌  | 2352/3125 [04:58<01:44,  7.41it/s, loss=0.00617]

Epoch 15 | Batch 2350/3125 | Loss: 0.0088

Epoch 15/30:  77%|███████▋  | 2402/3125 [05:04<01:26,  8.38it/s, loss=0.0192]

Epoch 15 | Batch 2400/3125 | Loss: 0.0093

Epoch 15/30:  78%|███████▊  | 2452/3125 [05:10<01:18,  8.60it/s, loss=0.0173]

Epoch 15 | Batch 2450/3125 | Loss: 0.0230

Epoch 15/30:  80%|████████  | 2501/3125 [05:17<01:24,  7.35it/s, loss=0.00831]

Epoch 15 | Batch 2500/3125 | Loss: 0.0118

Epoch 15/30:  82%|████████▏ | 2551/3125 [05:23<01:09,  8.22it/s, loss=0.0352]

Epoch 15 | Batch 2550/3125 | Loss: 0.0106

Epoch 15/30:  83%|████████▎ | 2601/3125 [05:29<01:13,  7.16it/s, loss=0.0425]

Epoch 15 | Batch 2600/3125 | Loss: 0.0180

Epoch 15/30:  85%|████████▍ | 2652/3125 [05:36<01:01,  7.74it/s, loss=0.00754]

Epoch 15 | Batch 2650/3125 | Loss: 0.0226

Epoch 15/30:  86%|████████▋ | 2702/3125 [05:42<00:50,  8.42it/s, loss=0.0205]

Epoch 15 | Batch 2700/3125 | Loss: 0.0164

Epoch 15/30:  88%|████████▊ | 2750/3125 [05:48<00:59,  6.35it/s, loss=0.00999]

Epoch 15 | Batch 2750/3125 | Loss: 0.0100

Epoch 15/30:  90%|████████▉ | 2800/3125 [05:55<00:39,  8.24it/s, loss=0.00932]

Epoch 15 | Batch 2800/3125 | Loss: 0.0093

Epoch 15/30:  91%|█████████▏| 2852/3125 [06:02<00:34,  7.85it/s, loss=0.00744]

Epoch 15 | Batch 2850/3125 | Loss: 0.0178

Epoch 15/30:  93%|█████████▎| 2900/3125 [06:08<00:29,  7.67it/s, loss=0.0216]

Epoch 15 | Batch 2900/3125 | Loss: 0.0216

Epoch 15/30:  94%|█████████▍| 2952/3125 [06:14<00:21,  8.18it/s, loss=0.00486]

Epoch 15 | Batch 2950/3125 | Loss: 0.0101

Epoch 15/30:  96%|█████████▌| 3002/3125 [06:21<00:15,  8.13it/s, loss=0.0112]

Epoch 15 | Batch 3000/3125 | Loss: 0.0116

Epoch 15/30:  98%|█████████▊| 3050/3125 [06:27<00:09,  7.77it/s, loss=0.0495]

Epoch 15 | Batch 3050/3125 | Loss: 0.0495

Epoch 15/30:  99%|█████████▉| 3102/3125 [06:34<00:02,  8.14it/s, loss=0.0161]

Epoch 15 | Batch 3100/3125 | Loss: 0.0206

Epoch 15/30: 100%|██████████| 3125/3125 [06:37<00:00,  7.86it/s, loss=0.0144]

Epoch [15/30] - Avg Loss: 0.0180

Epoch 16/30:   0%|          | 1/3125 [00:00<15:19,  3.40it/s, loss=0.0164]

Epoch 16 | Batch 0/3125 | Loss: 0.0292

Epoch 16/30:   2%|▏         | 52/3125 [00:06<06:45,  7.58it/s, loss=0.0247]

Epoch 16 | Batch 50/3125 | Loss: 0.0164

Epoch 16/30:   3%|▎         | 102/3125 [00:13<06:22,  7.91it/s, loss=0.0228]

Epoch 16 | Batch 100/3125 | Loss: 0.0070

Epoch 16/30:   5%|▍         | 152/3125 [00:19<06:36,  7.49it/s, loss=0.00385]

Epoch 16 | Batch 150/3125 | Loss: 0.0243

Epoch 16/30:   6%|▋         | 201/3125 [00:25<05:51,  8.32it/s, loss=0.0341]

Epoch 16 | Batch 200/3125 | Loss: 0.0126

Epoch 16/30:   8%|▊         | 251/3125 [00:32<06:22,  7.51it/s, loss=0.0381]

Epoch 16 | Batch 250/3125 | Loss: 0.0084

Epoch 16/30:  10%|▉         | 301/3125 [00:38<05:42,  8.25it/s, loss=0.0187]

Epoch 16 | Batch 300/3125 | Loss: 0.0041

Epoch 16/30:  11%|█         | 351/3125 [00:44<05:42,  8.10it/s, loss=0.00939]

Epoch 16 | Batch 350/3125 | Loss: 0.0321

Epoch 16/30:  13%|█▎        | 401/3125 [00:51<05:59,  7.58it/s, loss=0.0189]

Epoch 16 | Batch 400/3125 | Loss: 0.0238

Epoch 16/30:  14%|█▍        | 451/3125 [00:57<05:58,  7.46it/s, loss=0.0526]

Epoch 16 | Batch 450/3125 | Loss: 0.0220

Epoch 16/30:  16%|█▌        | 501/3125 [01:04<05:22,  8.13it/s, loss=0.0368]

Epoch 16 | Batch 500/3125 | Loss: 0.0106

Epoch 16/30:  18%|█▊        | 551/3125 [01:10<05:10,  8.29it/s, loss=0.044]

Epoch 16 | Batch 550/3125 | Loss: 0.0132

Epoch 16/30:  19%|█▉        | 602/3125 [01:16<04:48,  8.74it/s, loss=0.0325]

Epoch 16 | Batch 600/3125 | Loss: 0.0230

Epoch 16/30:  21%|██        | 651/3125 [01:22<05:33,  7.41it/s, loss=0.00863]

Epoch 16 | Batch 650/3125 | Loss: 0.0055

Epoch 16/30:  22%|██▏       | 701/3125 [01:29<05:50,  6.91it/s, loss=0.0159]

Epoch 16 | Batch 700/3125 | Loss: 0.0295

Epoch 16/30:  24%|██▍       | 751/3125 [01:35<05:07,  7.73it/s, loss=0.0659]

Epoch 16 | Batch 750/3125 | Loss: 0.0261

Epoch 16/30:  26%|██▌       | 801/3125 [01:41<04:35,  8.42it/s, loss=0.00708]

Epoch 16 | Batch 800/3125 | Loss: 0.0445

Epoch 16/30:  27%|██▋       | 852/3125 [01:48<04:31,  8.37it/s, loss=0.011]

Epoch 16 | Batch 850/3125 | Loss: 0.0049

Epoch 16/30:  29%|██▉       | 902/3125 [01:54<04:39,  7.94it/s, loss=0.0131]

Epoch 16 | Batch 900/3125 | Loss: 0.0270

Epoch 16/30:  30%|███       | 951/3125 [02:00<04:34,  7.91it/s, loss=0.00616]

Epoch 16 | Batch 950/3125 | Loss: 0.0097

Epoch 16/30:  32%|███▏      | 1001/3125 [02:07<04:30,  7.86it/s, loss=0.011]

Epoch 16 | Batch 1000/3125 | Loss: 0.0559

Epoch 16/30:  34%|███▎      | 1051/3125 [02:13<04:14,  8.14it/s, loss=0.0117]

Epoch 16 | Batch 1050/3125 | Loss: 0.0129

Epoch 16/30:  35%|███▌      | 1101/3125 [02:19<04:13,  7.97it/s, loss=0.0104]

Epoch 16 | Batch 1100/3125 | Loss: 0.0142

Epoch 16/30:  37%|███▋      | 1151/3125 [02:26<04:07,  7.97it/s, loss=0.00587]

Epoch 16 | Batch 1150/3125 | Loss: 0.0167

Epoch 16/30:  38%|███▊      | 1201/3125 [02:32<03:56,  8.14it/s, loss=0.0142]

Epoch 16 | Batch 1200/3125 | Loss: 0.0433

Epoch 16/30:  40%|████      | 1251/3125 [02:38<04:14,  7.35it/s, loss=0.016]

Epoch 16 | Batch 1250/3125 | Loss: 0.0190

Epoch 16/30:  42%|████▏     | 1301/3125 [02:45<03:53,  7.82it/s, loss=0.0249]

Epoch 16 | Batch 1300/3125 | Loss: 0.0131

Epoch 16/30:  43%|████▎     | 1351/3125 [02:51<03:32,  8.35it/s, loss=0.00427]

Epoch 16 | Batch 1350/3125 | Loss: 0.0424

Epoch 16/30:  45%|████▍     | 1401/3125 [02:58<03:35,  8.02it/s, loss=0.0131]

Epoch 16 | Batch 1400/3125 | Loss: 0.0084

Epoch 16/30:  46%|████▋     | 1451/3125 [03:04<03:28,  8.04it/s, loss=0.0316]

Epoch 16 | Batch 1450/3125 | Loss: 0.0140

Epoch 16/30:  48%|████▊     | 1501/3125 [03:10<03:40,  7.36it/s, loss=0.00914]

Epoch 16 | Batch 1500/3125 | Loss: 0.0124

Epoch 16/30:  50%|████▉     | 1551/3125 [03:17<03:22,  7.76it/s, loss=0.0195]

Epoch 16 | Batch 1550/3125 | Loss: 0.0087

Epoch 16/30:  51%|█████     | 1601/3125 [03:23<02:56,  8.64it/s, loss=0.0199]

Epoch 16 | Batch 1600/3125 | Loss: 0.0156

Epoch 16/30:  53%|█████▎    | 1651/3125 [03:30<03:20,  7.35it/s, loss=0.00276]

Epoch 16 | Batch 1650/3125 | Loss: 0.0071

Epoch 16/30:  54%|█████▍    | 1701/3125 [03:36<03:11,  7.44it/s, loss=0.00617]

Epoch 16 | Batch 1700/3125 | Loss: 0.0053

Epoch 16/30:  56%|█████▌    | 1752/3125 [03:42<02:53,  7.92it/s, loss=0.0177]

Epoch 16 | Batch 1750/3125 | Loss: 0.0027

Epoch 16/30:  58%|█████▊    | 1800/3125 [03:49<03:06,  7.12it/s, loss=0.00858]

Epoch 16 | Batch 1800/3125 | Loss: 0.0086

Epoch 16/30:  59%|█████▉    | 1852/3125 [03:56<02:33,  8.27it/s, loss=0.00765]

Epoch 16 | Batch 1850/3125 | Loss: 0.0087

Epoch 16/30:  61%|██████    | 1902/3125 [04:02<02:27,  8.28it/s, loss=0.031]

Epoch 16 | Batch 1900/3125 | Loss: 0.0553

Epoch 16/30:  62%|██████▏   | 1952/3125 [04:08<02:25,  8.05it/s, loss=0.00788]

Epoch 16 | Batch 1950/3125 | Loss: 0.0111

Epoch 16/30:  64%|██████▍   | 2002/3125 [04:15<02:18,  8.10it/s, loss=0.0144]

Epoch 16 | Batch 2000/3125 | Loss: 0.0546

Epoch 16/30:  66%|██████▌   | 2052/3125 [04:21<02:15,  7.89it/s, loss=0.00279]

Epoch 16 | Batch 2050/3125 | Loss: 0.0054

Epoch 16/30:  67%|██████▋   | 2102/3125 [04:28<02:05,  8.16it/s, loss=0.0141]

Epoch 16 | Batch 2100/3125 | Loss: 0.0825

Epoch 16/30:  69%|██████▉   | 2152/3125 [04:34<01:59,  8.15it/s, loss=0.0229]

Epoch 16 | Batch 2150/3125 | Loss: 0.0095

Epoch 16/30:  70%|███████   | 2202/3125 [04:40<01:56,  7.90it/s, loss=0.00855]

Epoch 16 | Batch 2200/3125 | Loss: 0.0282

Epoch 16/30:  72%|███████▏  | 2252/3125 [04:46<01:40,  8.68it/s, loss=0.0267]

Epoch 16 | Batch 2250/3125 | Loss: 0.0070

Epoch 16/30:  74%|███████▎  | 2302/3125 [04:52<01:42,  8.04it/s, loss=0.00417]

Epoch 16 | Batch 2300/3125 | Loss: 0.0452

Epoch 16/30:  75%|███████▌  | 2350/3125 [04:59<01:58,  6.55it/s, loss=0.0344]

Epoch 16 | Batch 2350/3125 | Loss: 0.0344

Epoch 16/30:  77%|███████▋  | 2402/3125 [05:06<01:31,  7.90it/s, loss=0.0133]

Epoch 16 | Batch 2400/3125 | Loss: 0.0571

Epoch 16/30:  78%|███████▊  | 2452/3125 [05:12<01:25,  7.83it/s, loss=0.057]

Epoch 16 | Batch 2450/3125 | Loss: 0.0120

Epoch 16/30:  80%|████████  | 2502/3125 [05:18<01:15,  8.28it/s, loss=0.00744]

Epoch 16 | Batch 2500/3125 | Loss: 0.0071

Epoch 16/30:  82%|████████▏ | 2552/3125 [05:24<01:09,  8.24it/s, loss=0.0246]

Epoch 16 | Batch 2550/3125 | Loss: 0.0131

Epoch 16/30:  83%|████████▎ | 2602/3125 [05:31<01:16,  6.81it/s, loss=0.0112]

Epoch 16 | Batch 2600/3125 | Loss: 0.0054

Epoch 16/30:  85%|████████▍ | 2652/3125 [05:37<00:57,  8.17it/s, loss=0.00684]

Epoch 16 | Batch 2650/3125 | Loss: 0.0224

Epoch 16/30:  86%|████████▋ | 2700/3125 [05:43<00:51,  8.21it/s, loss=0.0116]

Epoch 16 | Batch 2700/3125 | Loss: 0.0116

Epoch 16/30:  88%|████████▊ | 2752/3125 [05:50<00:44,  8.32it/s, loss=0.00371]

Epoch 16 | Batch 2750/3125 | Loss: 0.0084

Epoch 16/30:  90%|████████▉ | 2802/3125 [05:56<00:39,  8.27it/s, loss=0.00761]

Epoch 16 | Batch 2800/3125 | Loss: 0.0135

Epoch 16/30:  91%|█████████ | 2850/3125 [06:02<00:33,  8.09it/s, loss=0.0264]

Epoch 16 | Batch 2850/3125 | Loss: 0.0264

Epoch 16/30:  93%|█████████▎| 2902/3125 [06:09<00:30,  7.20it/s, loss=0.0087]

Epoch 16 | Batch 2900/3125 | Loss: 0.0051

Epoch 16/30:  94%|█████████▍| 2952/3125 [06:15<00:20,  8.35it/s, loss=0.0318]

Epoch 16 | Batch 2950/3125 | Loss: 0.0016

Epoch 16/30:  96%|█████████▌| 3002/3125 [06:21<00:14,  8.31it/s, loss=0.01]

Epoch 16 | Batch 3000/3125 | Loss: 0.0203

Epoch 16/30:  98%|█████████▊| 3051/3125 [06:27<00:08,  8.28it/s, loss=0.00622]

Epoch 16 | Batch 3050/3125 | Loss: 0.0143

Epoch 16/30:  99%|█████████▉| 3102/3125 [06:34<00:02,  8.26it/s, loss=0.0253]

Epoch 16 | Batch 3100/3125 | Loss: 0.0038

Epoch 16/30: 100%|██████████| 3125/3125 [06:37<00:00,  7.87it/s, loss=0.0134]

Epoch [16/30] - Avg Loss: 0.0158

Epoch 17/30:   0%|          | 1/3125 [00:00<14:48,  3.52it/s, loss=0.0189]

Epoch 17 | Batch 0/3125 | Loss: 0.0084

Epoch 17/30:   2%|▏         | 51/3125 [00:06<07:21,  6.96it/s, loss=0.052]

Epoch 17 | Batch 50/3125 | Loss: 0.0194

Epoch 17/30:   3%|▎         | 101/3125 [00:13<06:27,  7.80it/s, loss=0.00672]

Epoch 17 | Batch 100/3125 | Loss: 0.0049

Epoch 17/30:   5%|▍         | 151/3125 [00:19<06:12,  7.98it/s, loss=0.0116]

Epoch 17 | Batch 150/3125 | Loss: 0.0113

Epoch 17/30:   6%|▋         | 201/3125 [00:25<05:53,  8.27it/s, loss=0.0634]

Epoch 17 | Batch 200/3125 | Loss: 0.0103

Epoch 17/30:   8%|▊         | 251/3125 [00:31<05:55,  8.08it/s, loss=0.027]

Epoch 17 | Batch 250/3125 | Loss: 0.0060

Epoch 17/30:  10%|▉         | 301/3125 [00:38<05:49,  8.08it/s, loss=0.00645]

Epoch 17 | Batch 300/3125 | Loss: 0.0062

Epoch 17/30:  11%|█         | 351/3125 [00:44<05:54,  7.82it/s, loss=0.0129]

Epoch 17 | Batch 350/3125 | Loss: 0.0144

Epoch 17/30:  13%|█▎        | 402/3125 [00:51<05:31,  8.21it/s, loss=0.0492]

Epoch 17 | Batch 400/3125 | Loss: 0.0431

Epoch 17/30:  14%|█▍        | 452/3125 [00:57<05:49,  7.65it/s, loss=0.0102]

Epoch 17 | Batch 450/3125 | Loss: 0.0135

Epoch 17/30:  16%|█▌        | 502/3125 [01:03<05:41,  7.69it/s, loss=0.0063]

Epoch 17 | Batch 500/3125 | Loss: 0.0141

Epoch 17/30:  18%|█▊        | 552/3125 [01:09<05:05,  8.42it/s, loss=0.00462]

Epoch 17 | Batch 550/3125 | Loss: 0.0157

Epoch 17/30:  19%|█▉        | 601/3125 [01:16<06:17,  6.69it/s, loss=0.00819]

Epoch 17 | Batch 600/3125 | Loss: 0.0033

Epoch 17/30:  21%|██        | 652/3125 [01:22<04:49,  8.54it/s, loss=0.0131]

Epoch 17 | Batch 650/3125 | Loss: 0.0184

Epoch 17/30:  22%|██▏       | 701/3125 [01:28<04:51,  8.32it/s, loss=0.0191]

Epoch 17 | Batch 700/3125 | Loss: 0.0142

Epoch 17/30:  24%|██▍       | 751/3125 [01:35<05:05,  7.78it/s, loss=0.00689]

Epoch 17 | Batch 750/3125 | Loss: 0.0049

Epoch 17/30:  26%|██▌       | 801/3125 [01:41<04:30,  8.60it/s, loss=0.00497]

Epoch 17 | Batch 800/3125 | Loss: 0.0100

Epoch 17/30:  27%|██▋       | 852/3125 [01:47<04:56,  7.66it/s, loss=0.00757]

Epoch 17 | Batch 850/3125 | Loss: 0.0044

Epoch 17/30:  29%|██▉       | 901/3125 [01:54<05:01,  7.37it/s, loss=0.00811]

Epoch 17 | Batch 900/3125 | Loss: 0.0036

Epoch 17/30:  30%|███       | 951/3125 [02:00<04:20,  8.36it/s, loss=0.0128]

Epoch 17 | Batch 950/3125 | Loss: 0.0112

Epoch 17/30:  32%|███▏      | 1001/3125 [02:06<04:20,  8.15it/s, loss=0.00388]

Epoch 17 | Batch 1000/3125 | Loss: 0.0067

Epoch 17/30:  34%|███▎      | 1051/3125 [02:12<04:12,  8.21it/s, loss=0.0105]

Epoch 17 | Batch 1050/3125 | Loss: 0.0368

Epoch 17/30:  35%|███▌      | 1101/3125 [02:18<04:03,  8.33it/s, loss=0.0191]

Epoch 17 | Batch 1100/3125 | Loss: 0.0541

Epoch 17/30:  37%|███▋      | 1151/3125 [02:25<04:58,  6.61it/s, loss=0.00639]

Epoch 17 | Batch 1150/3125 | Loss: 0.0379

Epoch 17/30:  38%|███▊      | 1201/3125 [02:31<03:43,  8.60it/s, loss=0.0217]

Epoch 17 | Batch 1200/3125 | Loss: 0.0058

Epoch 17/30:  40%|████      | 1251/3125 [02:38<03:37,  8.61it/s, loss=0.0078]

Epoch 17 | Batch 1250/3125 | Loss: 0.0061

Epoch 17/30:  42%|████▏     | 1302/3125 [02:44<04:03,  7.49it/s, loss=0.0113]

Epoch 17 | Batch 1300/3125 | Loss: 0.0021

Epoch 17/30:  43%|████▎     | 1352/3125 [02:50<03:39,  8.06it/s, loss=0.00544]

Epoch 17 | Batch 1350/3125 | Loss: 0.0101

Epoch 17/30:  45%|████▍     | 1402/3125 [02:56<03:31,  8.14it/s, loss=0.00166]

Epoch 17 | Batch 1400/3125 | Loss: 0.0100

Epoch 17/30:  46%|████▋     | 1451/3125 [03:03<04:07,  6.77it/s, loss=0.0037]

Epoch 17 | Batch 1450/3125 | Loss: 0.0186

Epoch 17/30:  48%|████▊     | 1501/3125 [03:09<03:24,  7.96it/s, loss=0.00731]

Epoch 17 | Batch 1500/3125 | Loss: 0.0142

Epoch 17/30:  50%|████▉     | 1551/3125 [03:15<03:09,  8.32it/s, loss=0.00417]

Epoch 17 | Batch 1550/3125 | Loss: 0.0063

Epoch 17/30:  51%|█████     | 1601/3125 [03:22<03:09,  8.03it/s, loss=0.00626]

Epoch 17 | Batch 1600/3125 | Loss: 0.0042

Epoch 17/30:  53%|█████▎    | 1651/3125 [03:28<03:09,  7.78it/s, loss=0.0127]

Epoch 17 | Batch 1650/3125 | Loss: 0.0036

Epoch 17/30:  54%|█████▍    | 1701/3125 [03:34<03:29,  6.80it/s, loss=0.00967]

Epoch 17 | Batch 1700/3125 | Loss: 0.0125

Epoch 17/30:  56%|█████▌    | 1751/3125 [03:41<02:44,  8.37it/s, loss=0.0128]

Epoch 17 | Batch 1750/3125 | Loss: 0.0079

Epoch 17/30:  58%|█████▊    | 1801/3125 [03:47<02:50,  7.77it/s, loss=0.00471]

Epoch 17 | Batch 1800/3125 | Loss: 0.0052

Epoch 17/30:  59%|█████▉    | 1851/3125 [03:54<02:53,  7.36it/s, loss=0.0164]

Epoch 17 | Batch 1850/3125 | Loss: 0.0130

Epoch 17/30:  61%|██████    | 1901/3125 [04:00<02:26,  8.33it/s, loss=0.00741]

Epoch 17 | Batch 1900/3125 | Loss: 0.0081

Epoch 17/30:  62%|██████▏   | 1951/3125 [04:06<02:19,  8.43it/s, loss=0.00864]

Epoch 17 | Batch 1950/3125 | Loss: 0.0288

Epoch 17/30:  64%|██████▍   | 2000/3125 [04:13<02:50,  6.58it/s, loss=0.00864]

Epoch 17 | Batch 2000/3125 | Loss: 0.0086

Epoch 17/30:  66%|██████▌   | 2052/3125 [04:19<02:11,  8.16it/s, loss=0.0101]

Epoch 17 | Batch 2050/3125 | Loss: 0.0185

Epoch 17/30:  67%|██████▋   | 2102/3125 [04:25<02:06,  8.07it/s, loss=0.0397]

Epoch 17 | Batch 2100/3125 | Loss: 0.0157

Epoch 17/30:  69%|██████▉   | 2152/3125 [04:31<02:01,  8.00it/s, loss=0.00495]

Epoch 17 | Batch 2150/3125 | Loss: 0.0146

Epoch 17/30:  70%|███████   | 2201/3125 [04:38<01:54,  8.06it/s, loss=0.0282]

Epoch 17 | Batch 2200/3125 | Loss: 0.0026

Epoch 17/30:  72%|███████▏  | 2251/3125 [04:44<02:11,  6.62it/s, loss=0.0138]

Epoch 17 | Batch 2250/3125 | Loss: 0.0037

Epoch 17/30:  74%|███████▎  | 2301/3125 [04:51<01:42,  8.08it/s, loss=0.0135]

Epoch 17 | Batch 2300/3125 | Loss: 0.0278

Epoch 17/30:  75%|███████▌  | 2351/3125 [04:57<01:40,  7.71it/s, loss=0.00574]

Epoch 17 | Batch 2350/3125 | Loss: 0.0060

Epoch 17/30:  77%|███████▋  | 2401/3125 [05:04<01:28,  8.18it/s, loss=0.0122]

Epoch 17 | Batch 2400/3125 | Loss: 0.0504

Epoch 17/30:  78%|███████▊  | 2452/3125 [05:10<01:28,  7.59it/s, loss=0.0326]

Epoch 17 | Batch 2450/3125 | Loss: 0.0127

Epoch 17/30:  80%|████████  | 2502/3125 [05:16<01:20,  7.75it/s, loss=0.00936]

Epoch 17 | Batch 2500/3125 | Loss: 0.0290

Epoch 17/30:  82%|████████▏ | 2551/3125 [05:23<01:22,  6.99it/s, loss=0.00893]

Epoch 17 | Batch 2550/3125 | Loss: 0.0190

Epoch 17/30:  83%|████████▎ | 2601/3125 [05:29<01:00,  8.61it/s, loss=0.0349]

Epoch 17 | Batch 2600/3125 | Loss: 0.0258

Epoch 17/30:  85%|████████▍ | 2651/3125 [05:35<01:00,  7.81it/s, loss=0.00928]

Epoch 17 | Batch 2650/3125 | Loss: 0.0029

Epoch 17/30:  86%|████████▋ | 2701/3125 [05:42<00:54,  7.71it/s, loss=0.0214]

Epoch 17 | Batch 2700/3125 | Loss: 0.0437

Epoch 17/30:  88%|████████▊ | 2751/3125 [05:48<00:46,  8.12it/s, loss=0.00461]

Epoch 17 | Batch 2750/3125 | Loss: 0.0213

Epoch 17/30:  90%|████████▉ | 2801/3125 [05:54<00:43,  7.43it/s, loss=0.0255]

Epoch 17 | Batch 2800/3125 | Loss: 0.0146

Epoch 17/30:  91%|█████████ | 2851/3125 [06:01<00:33,  8.27it/s, loss=0.00231]

Epoch 17 | Batch 2850/3125 | Loss: 0.0113

Epoch 17/30:  93%|█████████▎| 2901/3125 [06:07<00:26,  8.43it/s, loss=0.00696]

Epoch 17 | Batch 2900/3125 | Loss: 0.0093

Epoch 17/30:  94%|█████████▍| 2951/3125 [06:14<00:22,  7.79it/s, loss=0.0143]

Epoch 17 | Batch 2950/3125 | Loss: 0.0141

Epoch 17/30:  96%|█████████▌| 3001/3125 [06:20<00:15,  7.92it/s, loss=0.00435]

Epoch 17 | Batch 3000/3125 | Loss: 0.0105

Epoch 17/30:  98%|█████████▊| 3051/3125 [06:26<00:08,  8.26it/s, loss=0.0166]

Epoch 17 | Batch 3050/3125 | Loss: 0.0284

Epoch 17/30:  99%|█████████▉| 3101/3125 [06:33<00:03,  7.02it/s, loss=0.0101]

Epoch 17 | Batch 3100/3125 | Loss: 0.0456

Epoch 17/30: 100%|██████████| 3125/3125 [06:36<00:00,  7.88it/s, loss=0.0117]

Epoch [17/30] - Avg Loss: 0.0142

Epoch 18/30:   0%|          | 1/3125 [00:00<14:15,  3.65it/s, loss=0.00526]

Epoch 18 | Batch 0/3125 | Loss: 0.0024

Epoch 18/30:   2%|▏         | 51/3125 [00:06<06:42,  7.65it/s, loss=0.0119]

Epoch 18 | Batch 50/3125 | Loss: 0.0171

Epoch 18/30:   3%|▎         | 101/3125 [00:12<06:23,  7.88it/s, loss=0.0223]

Epoch 18 | Batch 100/3125 | Loss: 0.0100

Epoch 18/30:   5%|▍         | 151/3125 [00:18<05:55,  8.36it/s, loss=0.00371]

Epoch 18 | Batch 150/3125 | Loss: 0.0038

Epoch 18/30:   6%|▋         | 201/3125 [00:24<06:06,  7.98it/s, loss=0.0132]

Epoch 18 | Batch 200/3125 | Loss: 0.0015

Epoch 18/30:   8%|▊         | 251/3125 [00:31<07:00,  6.83it/s, loss=0.00378]

Epoch 18 | Batch 250/3125 | Loss: 0.0126

Epoch 18/30:  10%|▉         | 301/3125 [00:38<05:59,  7.86it/s, loss=0.0151]

Epoch 18 | Batch 300/3125 | Loss: 0.0195

Epoch 18/30:  11%|█         | 351/3125 [00:44<05:46,  8.01it/s, loss=0.00533]

Epoch 18 | Batch 350/3125 | Loss: 0.0079

Epoch 18/30:  13%|█▎        | 401/3125 [00:50<05:22,  8.44it/s, loss=0.00899]

Epoch 18 | Batch 400/3125 | Loss: 0.0170

Epoch 18/30:  14%|█▍        | 451/3125 [00:56<06:10,  7.22it/s, loss=0.0403]

Epoch 18 | Batch 450/3125 | Loss: 0.0057

Epoch 18/30:  16%|█▌        | 501/3125 [01:02<05:06,  8.55it/s, loss=0.0138]

Epoch 18 | Batch 500/3125 | Loss: 0.0067

Epoch 18/30:  18%|█▊        | 551/3125 [01:10<05:44,  7.47it/s, loss=0.0046]

Epoch 18 | Batch 550/3125 | Loss: 0.0058

Epoch 18/30:  19%|█▉        | 601/3125 [01:16<05:30,  7.63it/s, loss=0.00686]

Epoch 18 | Batch 600/3125 | Loss: 0.0401

Epoch 18/30:  21%|██        | 651/3125 [01:22<05:20,  7.73it/s, loss=0.0231]

Epoch 18 | Batch 650/3125 | Loss: 0.0102

Epoch 18/30:  22%|██▏       | 701/3125 [01:28<05:01,  8.03it/s, loss=0.041]

Epoch 18 | Batch 700/3125 | Loss: 0.0108

Epoch 18/30:  24%|██▍       | 751/3125 [01:35<04:51,  8.14it/s, loss=0.0136]

Epoch 18 | Batch 750/3125 | Loss: 0.0045

Epoch 18/30:  26%|██▌       | 801/3125 [01:41<05:17,  7.33it/s, loss=0.00903]

Epoch 18 | Batch 800/3125 | Loss: 0.0227

Epoch 18/30:  27%|██▋       | 851/3125 [01:48<04:57,  7.66it/s, loss=0.0155]

Epoch 18 | Batch 850/3125 | Loss: 0.0548

Epoch 18/30:  29%|██▉       | 901/3125 [01:54<04:23,  8.43it/s, loss=0.00355]

Epoch 18 | Batch 900/3125 | Loss: 0.0110

Epoch 18/30:  30%|███       | 951/3125 [02:01<04:25,  8.19it/s, loss=0.00469]

Epoch 18 | Batch 950/3125 | Loss: 0.0059

Epoch 18/30:  32%|███▏      | 1001/3125 [02:07<04:24,  8.04it/s, loss=0.0107]

Epoch 18 | Batch 1000/3125 | Loss: 0.0078

Epoch 18/30:  34%|███▎      | 1051/3125 [02:13<04:25,  7.81it/s, loss=0.00609]

Epoch 18 | Batch 1050/3125 | Loss: 0.0544

Epoch 18/30:  35%|███▌      | 1101/3125 [02:20<04:15,  7.91it/s, loss=0.014]

Epoch 18 | Batch 1100/3125 | Loss: 0.0018

Epoch 18/30:  37%|███▋      | 1151/3125 [02:26<04:24,  7.47it/s, loss=0.0387]

Epoch 18 | Batch 1150/3125 | Loss: 0.0120

Epoch 18/30:  38%|███▊      | 1201/3125 [02:33<03:58,  8.06it/s, loss=0.00978]

Epoch 18 | Batch 1200/3125 | Loss: 0.0132

Epoch 18/30:  40%|████      | 1251/3125 [02:39<03:51,  8.09it/s, loss=0.00461]

Epoch 18 | Batch 1250/3125 | Loss: 0.0315

Epoch 18/30:  42%|████▏     | 1301/3125 [02:45<03:47,  8.00it/s, loss=0.0057]

Epoch 18 | Batch 1300/3125 | Loss: 0.0025

Epoch 18/30:  43%|████▎     | 1351/3125 [02:51<04:12,  7.01it/s, loss=0.003]

Epoch 18 | Batch 1350/3125 | Loss: 0.0069

Epoch 18/30:  45%|████▍     | 1401/3125 [02:58<03:30,  8.19it/s, loss=0.0129]

Epoch 18 | Batch 1400/3125 | Loss: 0.0121

Epoch 18/30:  46%|████▋     | 1451/3125 [03:04<03:36,  7.74it/s, loss=0.0206]

Epoch 18 | Batch 1450/3125 | Loss: 0.0114

Epoch 18/30:  48%|████▊     | 1501/3125 [03:10<03:20,  8.09it/s, loss=0.00838]

Epoch 18 | Batch 1500/3125 | Loss: 0.0060

Epoch 18/30:  50%|████▉     | 1551/3125 [03:17<03:17,  7.97it/s, loss=0.0206]

Epoch 18 | Batch 1550/3125 | Loss: 0.0043

Epoch 18/30:  51%|█████     | 1601/3125 [03:23<03:02,  8.37it/s, loss=0.0049]

Epoch 18 | Batch 1600/3125 | Loss: 0.0090

Epoch 18/30:  53%|█████▎    | 1651/3125 [03:30<03:39,  6.73it/s, loss=0.0124]

Epoch 18 | Batch 1650/3125 | Loss: 0.0171

Epoch 18/30:  54%|█████▍    | 1701/3125 [03:36<02:58,  7.99it/s, loss=0.00579]

Epoch 18 | Batch 1700/3125 | Loss: 0.0154

Epoch 18/30:  56%|█████▌    | 1751/3125 [03:42<02:52,  7.95it/s, loss=0.00748]

Epoch 18 | Batch 1750/3125 | Loss: 0.0029

Epoch 18/30:  58%|█████▊    | 1801/3125 [03:49<02:46,  7.96it/s, loss=0.0193]

Epoch 18 | Batch 1800/3125 | Loss: 0.0049

Epoch 18/30:  59%|█████▉    | 1851/3125 [03:55<02:31,  8.41it/s, loss=0.00599]

Epoch 18 | Batch 1850/3125 | Loss: 0.0165

Epoch 18/30:  61%|██████    | 1901/3125 [04:01<02:47,  7.32it/s, loss=0.00814]

Epoch 18 | Batch 1900/3125 | Loss: 0.0410

Epoch 18/30:  62%|██████▏   | 1951/3125 [04:08<02:22,  8.24it/s, loss=0.00975]

Epoch 18 | Batch 1950/3125 | Loss: 0.0094

Epoch 18/30:  64%|██████▍   | 2001/3125 [04:14<02:26,  7.65it/s, loss=0.00327]

Epoch 18 | Batch 2000/3125 | Loss: 0.0032

Epoch 18/30:  66%|██████▌   | 2051/3125 [04:21<02:20,  7.66it/s, loss=0.0127]

Epoch 18 | Batch 2050/3125 | Loss: 0.0055

Epoch 18/30:  67%|██████▋   | 2101/3125 [04:27<02:13,  7.65it/s, loss=0.045]

Epoch 18 | Batch 2100/3125 | Loss: 0.0101

Epoch 18/30:  69%|██████▉   | 2151/3125 [04:33<02:01,  8.02it/s, loss=0.00766]

Epoch 18 | Batch 2150/3125 | Loss: 0.0127

Epoch 18/30:  70%|███████   | 2201/3125 [04:40<02:24,  6.38it/s, loss=0.0046]

Epoch 18 | Batch 2200/3125 | Loss: 0.0135

Epoch 18/30:  72%|███████▏  | 2251/3125 [04:46<01:53,  7.70it/s, loss=0.00628]

Epoch 18 | Batch 2250/3125 | Loss: 0.0101

Epoch 18/30:  74%|███████▎  | 2301/3125 [04:53<01:40,  8.20it/s, loss=0.0394]

Epoch 18 | Batch 2300/3125 | Loss: 0.0032

Epoch 18/30:  75%|███████▌  | 2351/3125 [04:59<01:35,  8.09it/s, loss=0.00237]

Epoch 18 | Batch 2350/3125 | Loss: 0.0075

Epoch 18/30:  77%|███████▋  | 2401/3125 [05:05<01:31,  7.93it/s, loss=0.00255]

Epoch 18 | Batch 2400/3125 | Loss: 0.0057

Epoch 18/30:  78%|███████▊  | 2451/3125 [05:12<01:38,  6.83it/s, loss=0.0225]

Epoch 18 | Batch 2450/3125 | Loss: 0.0207

Epoch 18/30:  80%|████████  | 2502/3125 [05:19<01:18,  7.89it/s, loss=0.00767]

Epoch 18 | Batch 2500/3125 | Loss: 0.0138

Epoch 18/30:  82%|████████▏ | 2552/3125 [05:25<01:11,  8.00it/s, loss=0.00873]

Epoch 18 | Batch 2550/3125 | Loss: 0.0082

Epoch 18/30:  83%|████████▎ | 2600/3125 [05:31<01:05,  7.96it/s, loss=0.0031]

Epoch 18 | Batch 2600/3125 | Loss: 0.0031

Epoch 18/30:  85%|████████▍ | 2652/3125 [05:38<00:59,  7.99it/s, loss=0.0414]

Epoch 18 | Batch 2650/3125 | Loss: 0.0139

Epoch 18/30:  86%|████████▋ | 2702/3125 [05:44<00:53,  7.87it/s, loss=0.0105]

Epoch 18 | Batch 2700/3125 | Loss: 0.0103

Epoch 18/30:  88%|████████▊ | 2752/3125 [05:52<00:49,  7.48it/s, loss=0.0195]

Epoch 18 | Batch 2750/3125 | Loss: 0.0054

Epoch 18/30:  90%|████████▉ | 2800/3125 [05:58<00:40,  8.01it/s, loss=0.01]

Epoch 18 | Batch 2800/3125 | Loss: 0.0100

Epoch 18/30:  91%|█████████▏| 2852/3125 [06:04<00:33,  8.15it/s, loss=0.0279]

Epoch 18 | Batch 2850/3125 | Loss: 0.0131

Epoch 18/30:  93%|█████████▎| 2902/3125 [06:10<00:26,  8.30it/s, loss=0.00761]

Epoch 18 | Batch 2900/3125 | Loss: 0.0096

Epoch 18/30:  94%|█████████▍| 2952/3125 [06:16<00:21,  8.14it/s, loss=0.0139]

Epoch 18 | Batch 2950/3125 | Loss: 0.0247

Epoch 18/30:  96%|█████████▌| 3000/3125 [06:23<00:18,  6.76it/s, loss=0.00449]

Epoch 18 | Batch 3000/3125 | Loss: 0.0045

Epoch 18/30:  98%|█████████▊| 3052/3125 [06:29<00:08,  8.17it/s, loss=0.00646]

Epoch 18 | Batch 3050/3125 | Loss: 0.0081

Epoch 18/30:  99%|█████████▉| 3102/3125 [06:36<00:02,  7.74it/s, loss=0.00387]

Epoch 18 | Batch 3100/3125 | Loss: 0.0139

Epoch 18/30: 100%|██████████| 3125/3125 [06:38<00:00,  7.83it/s, loss=0.00374]

Epoch [18/30] - Avg Loss: 0.0127

Epoch 19/30:   0%|          | 1/3125 [00:00<14:53,  3.50it/s, loss=0.00957]

Epoch 19 | Batch 0/3125 | Loss: 0.0141

Epoch 19/30:   2%|▏         | 51/3125 [00:06<06:20,  8.08it/s, loss=0.00368]

Epoch 19 | Batch 50/3125 | Loss: 0.0123

Epoch 19/30:   3%|▎         | 101/3125 [00:12<05:58,  8.43it/s, loss=0.00591]

Epoch 19 | Batch 100/3125 | Loss: 0.0089

Epoch 19/30:   5%|▍         | 151/3125 [00:18<06:50,  7.24it/s, loss=0.0222]

Epoch 19 | Batch 150/3125 | Loss: 0.0034

Epoch 19/30:   6%|▋         | 201/3125 [00:25<05:49,  8.36it/s, loss=0.0134]

Epoch 19 | Batch 200/3125 | Loss: 0.0053

Epoch 19/30:   8%|▊         | 251/3125 [00:32<05:48,  8.24it/s, loss=0.00396]

Epoch 19 | Batch 250/3125 | Loss: 0.0329

Epoch 19/30:  10%|▉         | 301/3125 [00:38<06:19,  7.45it/s, loss=0.00614]

Epoch 19 | Batch 300/3125 | Loss: 0.0198

Epoch 19/30:  11%|█▏        | 352/3125 [00:44<05:32,  8.34it/s, loss=0.00421]

Epoch 19 | Batch 350/3125 | Loss: 0.0107

Epoch 19/30:  13%|█▎        | 402/3125 [00:50<05:28,  8.28it/s, loss=0.000883]

Epoch 19 | Batch 400/3125 | Loss: 0.0072

Epoch 19/30:  14%|█▍        | 452/3125 [00:57<06:01,  7.40it/s, loss=0.0401]

Epoch 19 | Batch 450/3125 | Loss: 0.0102

Epoch 19/30:  16%|█▌        | 502/3125 [01:04<05:37,  7.78it/s, loss=0.0145]

Epoch 19 | Batch 500/3125 | Loss: 0.0039

Epoch 19/30:  18%|█▊        | 552/3125 [01:10<05:11,  8.27it/s, loss=0.00385]

Epoch 19 | Batch 550/3125 | Loss: 0.0052

Epoch 19/30:  19%|█▉        | 602/3125 [01:16<05:16,  7.96it/s, loss=0.00288]

Epoch 19 | Batch 600/3125 | Loss: 0.0309

Epoch 19/30:  21%|██        | 652/3125 [01:23<04:59,  8.26it/s, loss=0.0132]

Epoch 19 | Batch 650/3125 | Loss: 0.0242

Epoch 19/30:  22%|██▏       | 700/3125 [01:29<05:03,  8.00it/s, loss=0.00654]

Epoch 19 | Batch 700/3125 | Loss: 0.0065

Epoch 19/30:  24%|██▍       | 751/3125 [01:36<05:03,  7.82it/s, loss=0.0129]

Epoch 19 | Batch 750/3125 | Loss: 0.0110

Epoch 19/30:  26%|██▌       | 801/3125 [01:42<04:37,  8.38it/s, loss=0.00334]

Epoch 19 | Batch 800/3125 | Loss: 0.0356

Epoch 19/30:  27%|██▋       | 852/3125 [01:48<04:35,  8.24it/s, loss=0.00332]

Epoch 19 | Batch 850/3125 | Loss: 0.0166

Epoch 19/30:  29%|██▉       | 901/3125 [01:55<04:36,  8.05it/s, loss=0.0053]

Epoch 19 | Batch 900/3125 | Loss: 0.0031

Epoch 19/30:  30%|███       | 951/3125 [02:01<04:29,  8.08it/s, loss=0.00575]

Epoch 19 | Batch 950/3125 | Loss: 0.0156

Epoch 19/30:  32%|███▏      | 1001/3125 [02:07<04:55,  7.20it/s, loss=0.00226]

Epoch 19 | Batch 1000/3125 | Loss: 0.0058

Epoch 19/30:  34%|███▎      | 1051/3125 [02:14<04:07,  8.38it/s, loss=0.00584]

Epoch 19 | Batch 1050/3125 | Loss: 0.0145

Epoch 19/30:  35%|███▌      | 1101/3125 [02:20<04:16,  7.88it/s, loss=0.00147]

Epoch 19 | Batch 1100/3125 | Loss: 0.0122

Epoch 19/30:  37%|███▋      | 1151/3125 [02:26<03:46,  8.70it/s, loss=0.0119]

Epoch 19 | Batch 1150/3125 | Loss: 0.0063

Epoch 19/30:  38%|███▊      | 1201/3125 [02:33<04:19,  7.42it/s, loss=0.00576]

Epoch 19 | Batch 1200/3125 | Loss: 0.0014

Epoch 19/30:  40%|████      | 1251/3125 [02:39<03:51,  8.11it/s, loss=0.0169]

Epoch 19 | Batch 1250/3125 | Loss: 0.0286

Epoch 19/30:  42%|████▏     | 1302/3125 [02:46<03:53,  7.79it/s, loss=0.00864]

Epoch 19 | Batch 1300/3125 | Loss: 0.0045

Epoch 19/30:  43%|████▎     | 1352/3125 [02:52<03:37,  8.16it/s, loss=0.0446]

Epoch 19 | Batch 1350/3125 | Loss: 0.0036

Epoch 19/30:  45%|████▍     | 1402/3125 [02:59<03:36,  7.97it/s, loss=0.00364]

Epoch 19 | Batch 1400/3125 | Loss: 0.0525

Epoch 19/30:  46%|████▋     | 1450/3125 [03:05<03:43,  7.49it/s, loss=0.0107]

Epoch 19 | Batch 1450/3125 | Loss: 0.0107

Epoch 19/30:  48%|████▊     | 1502/3125 [03:11<03:18,  8.16it/s, loss=0.028]

Epoch 19 | Batch 1500/3125 | Loss: 0.0123

Epoch 19/30:  50%|████▉     | 1551/3125 [03:18<04:08,  6.33it/s, loss=0.00567]

Epoch 19 | Batch 1550/3125 | Loss: 0.0027

Epoch 19/30:  51%|█████▏    | 1602/3125 [03:25<03:09,  8.06it/s, loss=0.00832]

Epoch 19 | Batch 1600/3125 | Loss: 0.0033

Epoch 19/30:  53%|█████▎    | 1652/3125 [03:31<02:54,  8.43it/s, loss=0.00388]

Epoch 19 | Batch 1650/3125 | Loss: 0.0040

Epoch 19/30:  54%|█████▍    | 1702/3125 [03:37<03:09,  7.50it/s, loss=0.0287]

Epoch 19 | Batch 1700/3125 | Loss: 0.0125

Epoch 19/30:  56%|█████▌    | 1751/3125 [03:43<02:48,  8.17it/s, loss=0.0113]

Epoch 19 | Batch 1750/3125 | Loss: 0.0105

Epoch 19/30:  58%|█████▊    | 1801/3125 [03:49<02:43,  8.12it/s, loss=0.00287]

Epoch 19 | Batch 1800/3125 | Loss: 0.0145

Epoch 19/30:  59%|█████▉    | 1851/3125 [03:57<03:05,  6.86it/s, loss=0.0396]

Epoch 19 | Batch 1850/3125 | Loss: 0.0023

Epoch 19/30:  61%|██████    | 1901/3125 [04:03<02:33,  7.95it/s, loss=0.0185]

Epoch 19 | Batch 1900/3125 | Loss: 0.0049

Epoch 19/30:  62%|██████▏   | 1951/3125 [04:09<02:22,  8.22it/s, loss=0.00632]

Epoch 19 | Batch 1950/3125 | Loss: 0.0313

Epoch 19/30:  64%|██████▍   | 2001/3125 [04:15<02:26,  7.67it/s, loss=0.00785]

Epoch 19 | Batch 2000/3125 | Loss: 0.0083

Epoch 19/30:  66%|██████▌   | 2051/3125 [04:22<02:07,  8.43it/s, loss=0.00393]

Epoch 19 | Batch 2050/3125 | Loss: 0.0229

Epoch 19/30:  67%|██████▋   | 2101/3125 [04:28<02:46,  6.16it/s, loss=0.00456]

Epoch 19 | Batch 2100/3125 | Loss: 0.0115

Epoch 19/30:  69%|██████▉   | 2151/3125 [04:35<02:10,  7.48it/s, loss=0.00552]

Epoch 19 | Batch 2150/3125 | Loss: 0.0048

Epoch 19/30:  70%|███████   | 2201/3125 [04:41<01:55,  7.97it/s, loss=0.00353]

Epoch 19 | Batch 2200/3125 | Loss: 0.0161

Epoch 19/30:  72%|███████▏  | 2251/3125 [04:48<01:59,  7.33it/s, loss=0.00772]

Epoch 19 | Batch 2250/3125 | Loss: 0.0047

Epoch 19/30:  74%|███████▎  | 2301/3125 [04:54<01:50,  7.49it/s, loss=0.00313]

Epoch 19 | Batch 2300/3125 | Loss: 0.0053

Epoch 19/30:  75%|███████▌  | 2351/3125 [05:00<01:35,  8.12it/s, loss=0.00277]

Epoch 19 | Batch 2350/3125 | Loss: 0.0045

Epoch 19/30:  77%|███████▋  | 2401/3125 [05:07<01:49,  6.64it/s, loss=0.00628]

Epoch 19 | Batch 2400/3125 | Loss: 0.0030

Epoch 19/30:  78%|███████▊  | 2451/3125 [05:14<01:25,  7.84it/s, loss=0.0053]

Epoch 19 | Batch 2450/3125 | Loss: 0.0024

Epoch 19/30:  80%|████████  | 2501/3125 [05:20<01:14,  8.34it/s, loss=0.0116]

Epoch 19 | Batch 2500/3125 | Loss: 0.0407

Epoch 19/30:  82%|████████▏ | 2551/3125 [05:26<01:14,  7.72it/s, loss=0.00435]

Epoch 19 | Batch 2550/3125 | Loss: 0.0026

Epoch 19/30:  83%|████████▎ | 2602/3125 [05:33<01:03,  8.22it/s, loss=0.00248]

Epoch 19 | Batch 2600/3125 | Loss: 0.0055

Epoch 19/30:  85%|████████▍ | 2651/3125 [05:39<01:05,  7.20it/s, loss=0.00998]

Epoch 19 | Batch 2650/3125 | Loss: 0.0016

Epoch 19/30:  86%|████████▋ | 2701/3125 [05:46<00:58,  7.29it/s, loss=0.00752]

Epoch 19 | Batch 2700/3125 | Loss: 0.0030

Epoch 19/30:  88%|████████▊ | 2751/3125 [05:52<00:46,  8.09it/s, loss=0.0174]

Epoch 19 | Batch 2750/3125 | Loss: 0.0034

Epoch 19/30:  90%|████████▉ | 2801/3125 [05:58<00:40,  7.93it/s, loss=0.00771]

Epoch 19 | Batch 2800/3125 | Loss: 0.0164

Epoch 19/30:  91%|█████████ | 2851/3125 [06:05<00:35,  7.78it/s, loss=0.00911]

Epoch 19 | Batch 2850/3125 | Loss: 0.0038

Epoch 19/30:  93%|█████████▎| 2901/3125 [06:11<00:29,  7.47it/s, loss=0.00519]

Epoch 19 | Batch 2900/3125 | Loss: 0.0072

Epoch 19/30:  94%|█████████▍| 2951/3125 [06:18<00:25,  6.73it/s, loss=0.00527]

Epoch 19 | Batch 2950/3125 | Loss: 0.0062

Epoch 19/30:  96%|█████████▌| 3001/3125 [06:24<00:14,  8.37it/s, loss=0.00244]

Epoch 19 | Batch 3000/3125 | Loss: 0.0037

Epoch 19/30:  98%|█████████▊| 3051/3125 [06:31<00:09,  8.20it/s, loss=0.00998]

Epoch 19 | Batch 3050/3125 | Loss: 0.0203

Epoch 19/30:  99%|█████████▉| 3101/3125 [06:37<00:02,  8.10it/s, loss=0.00836]

Epoch 19 | Batch 3100/3125 | Loss: 0.0402

Epoch 19/30: 100%|██████████| 3125/3125 [06:40<00:00,  7.80it/s, loss=0.00332]

Epoch [19/30] - Avg Loss: 0.0113

Epoch 20/30:   0%|          | 1/3125 [00:00<16:26,  3.17it/s, loss=0.0117]

Epoch 20 | Batch 0/3125 | Loss: 0.0039

Epoch 20/30:   2%|▏         | 51/3125 [00:06<06:22,  8.03it/s, loss=0.00679]

Epoch 20 | Batch 50/3125 | Loss: 0.0067

Epoch 20/30:   3%|▎         | 101/3125 [00:13<07:31,  6.70it/s, loss=0.00373]

Epoch 20 | Batch 100/3125 | Loss: 0.0163

Epoch 20/30:   5%|▍         | 151/3125 [00:19<06:26,  7.70it/s, loss=0.0059]

Epoch 20 | Batch 150/3125 | Loss: 0.0259

Epoch 20/30:   6%|▋         | 201/3125 [00:25<05:48,  8.39it/s, loss=0.00387]

Epoch 20 | Batch 200/3125 | Loss: 0.0081

Epoch 20/30:   8%|▊         | 251/3125 [00:32<06:02,  7.94it/s, loss=0.00521]

Epoch 20 | Batch 250/3125 | Loss: 0.0038

Epoch 20/30:  10%|▉         | 301/3125 [00:38<06:13,  7.56it/s, loss=0.00436]

Epoch 20 | Batch 300/3125 | Loss: 0.0085

Epoch 20/30:  11%|█         | 351/3125 [00:44<05:45,  8.02it/s, loss=0.00539]

Epoch 20 | Batch 350/3125 | Loss: 0.0213

Epoch 20/30:  13%|█▎        | 401/3125 [00:51<05:28,  8.30it/s, loss=0.00258]

Epoch 20 | Batch 400/3125 | Loss: 0.0060

Epoch 20/30:  14%|█▍        | 451/3125 [00:58<05:19,  8.36it/s, loss=0.00697]

Epoch 20 | Batch 450/3125 | Loss: 0.0061

Epoch 20/30:  16%|█▌        | 501/3125 [01:04<05:30,  7.93it/s, loss=0.00953]

Epoch 20 | Batch 500/3125 | Loss: 0.0056

Epoch 20/30:  18%|█▊        | 551/3125 [01:10<05:25,  7.90it/s, loss=0.0072]

Epoch 20 | Batch 550/3125 | Loss: 0.0065

Epoch 20/30:  19%|█▉        | 601/3125 [01:17<05:11,  8.11it/s, loss=0.0117]

Epoch 20 | Batch 600/3125 | Loss: 0.0189

Epoch 20/30:  21%|██        | 652/3125 [01:23<05:48,  7.10it/s, loss=0.00452]

Epoch 20 | Batch 650/3125 | Loss: 0.0054

Epoch 20/30:  22%|██▏       | 700/3125 [01:30<04:59,  8.10it/s, loss=0.00408]

Epoch 20 | Batch 700/3125 | Loss: 0.0041

Epoch 20/30:  24%|██▍       | 752/3125 [01:36<04:53,  8.08it/s, loss=0.00845]

Epoch 20 | Batch 750/3125 | Loss: 0.0096

Epoch 20/30:  26%|██▌       | 802/3125 [01:43<04:31,  8.54it/s, loss=0.00457]

Epoch 20 | Batch 800/3125 | Loss: 0.0524

Epoch 20/30:  27%|██▋       | 852/3125 [01:49<04:43,  8.02it/s, loss=0.00631]

Epoch 20 | Batch 850/3125 | Loss: 0.0044

Epoch 20/30:  29%|██▉       | 900/3125 [01:56<05:13,  7.09it/s, loss=0.00887]

Epoch 20 | Batch 900/3125 | Loss: 0.0354

Epoch 20/30:  30%|███       | 951/3125 [02:03<04:40,  7.75it/s, loss=0.0206]

Epoch 20 | Batch 950/3125 | Loss: 0.0111

Epoch 20/30:  32%|███▏      | 1001/3125 [02:09<04:28,  7.90it/s, loss=0.00717]

Epoch 20 | Batch 1000/3125 | Loss: 0.0063

Epoch 20/30:  34%|███▎      | 1051/3125 [02:15<04:10,  8.28it/s, loss=0.00227]

Epoch 20 | Batch 1050/3125 | Loss: 0.0043

Epoch 20/30:  35%|███▌      | 1101/3125 [02:21<04:23,  7.68it/s, loss=0.0316]

Epoch 20 | Batch 1100/3125 | Loss: 0.0038

Epoch 20/30:  37%|███▋      | 1151/3125 [02:28<04:01,  8.16it/s, loss=0.0182]

Epoch 20 | Batch 1150/3125 | Loss: 0.0072

Epoch 20/30:  38%|███▊      | 1201/3125 [02:35<05:05,  6.29it/s, loss=0.00353]

Epoch 20 | Batch 1200/3125 | Loss: 0.0019

Epoch 20/30:  40%|████      | 1251/3125 [02:42<03:53,  8.02it/s, loss=0.011]

Epoch 20 | Batch 1250/3125 | Loss: 0.0095

Epoch 20/30:  42%|████▏     | 1301/3125 [02:48<03:57,  7.67it/s, loss=0.0104]

Epoch 20 | Batch 1300/3125 | Loss: 0.0099

Epoch 20/30:  43%|████▎     | 1351/3125 [02:54<03:33,  8.29it/s, loss=0.0203]

Epoch 20 | Batch 1350/3125 | Loss: 0.0042

Epoch 20/30:  45%|████▍     | 1401/3125 [03:00<03:41,  7.77it/s, loss=0.0106]

Epoch 20 | Batch 1400/3125 | Loss: 0.0029

Epoch 20/30:  46%|████▋     | 1451/3125 [03:07<03:28,  8.02it/s, loss=0.00608]

Epoch 20 | Batch 1450/3125 | Loss: 0.0095

Epoch 20/30:  48%|████▊     | 1501/3125 [03:14<03:23,  7.98it/s, loss=0.00157]

Epoch 20 | Batch 1500/3125 | Loss: 0.0032

Epoch 20/30:  50%|████▉     | 1551/3125 [03:21<03:27,  7.57it/s, loss=0.00616]

Epoch 20 | Batch 1550/3125 | Loss: 0.0034

Epoch 20/30:  51%|█████     | 1601/3125 [03:27<03:11,  7.96it/s, loss=0.00403]

Epoch 20 | Batch 1600/3125 | Loss: 0.0109

Epoch 20/30:  53%|█████▎    | 1651/3125 [03:33<02:56,  8.34it/s, loss=0.00722]

Epoch 20 | Batch 1650/3125 | Loss: 0.0037

Epoch 20/30:  54%|█████▍    | 1700/3125 [03:40<03:06,  7.64it/s, loss=0.00131]

Epoch 20 | Batch 1700/3125 | Loss: 0.0013

Epoch 20/30:  56%|█████▌    | 1752/3125 [03:47<03:23,  6.75it/s, loss=0.00889]

Epoch 20 | Batch 1750/3125 | Loss: 0.0066

Epoch 20/30:  58%|█████▊    | 1802/3125 [03:54<02:48,  7.87it/s, loss=0.0166]

Epoch 20 | Batch 1800/3125 | Loss: 0.0030

Epoch 20/30:  59%|█████▉    | 1852/3125 [04:00<02:41,  7.87it/s, loss=0.0178]

Epoch 20 | Batch 1850/3125 | Loss: 0.0351

Epoch 20/30:  61%|██████    | 1900/3125 [04:06<02:31,  8.07it/s, loss=0.00249]

Epoch 20 | Batch 1900/3125 | Loss: 0.0025

Epoch 20/30:  62%|██████▏   | 1952/3125 [04:13<02:33,  7.66it/s, loss=0.0039]

Epoch 20 | Batch 1950/3125 | Loss: 0.0039

Epoch 20/30:  64%|██████▍   | 2000/3125 [04:20<02:37,  7.14it/s, loss=0.0143]

Epoch 20 | Batch 2000/3125 | Loss: 0.0143

Epoch 20/30:  66%|██████▌   | 2050/3125 [04:27<02:22,  7.57it/s, loss=0.00488]

Epoch 20 | Batch 2050/3125 | Loss: 0.0049

Epoch 20/30:  67%|██████▋   | 2100/3125 [04:33<02:20,  7.27it/s, loss=0.00502]

Epoch 20 | Batch 2100/3125 | Loss: 0.0050

Epoch 20/30:  69%|██████▉   | 2150/3125 [04:40<02:11,  7.44it/s, loss=0.0104]

Epoch 20 | Batch 2150/3125 | Loss: 0.0104

Epoch 20/30:  70%|███████   | 2202/3125 [04:47<01:52,  8.24it/s, loss=0.00708]

Epoch 20 | Batch 2200/3125 | Loss: 0.0126

Epoch 20/30:  72%|███████▏  | 2252/3125 [04:53<01:56,  7.52it/s, loss=0.00443]

Epoch 20 | Batch 2250/3125 | Loss: 0.0054

Epoch 20/30:  74%|███████▎  | 2300/3125 [05:01<01:57,  7.05it/s, loss=0.00447]

Epoch 20 | Batch 2300/3125 | Loss: 0.0045

Epoch 20/30:  75%|███████▌  | 2350/3125 [05:07<01:39,  7.83it/s, loss=0.00399]

Epoch 20 | Batch 2350/3125 | Loss: 0.0040

Epoch 20/30:  77%|███████▋  | 2402/3125 [05:14<01:34,  7.67it/s, loss=0.00318]

Epoch 20 | Batch 2400/3125 | Loss: 0.0083

Epoch 20/30:  78%|███████▊  | 2452/3125 [05:20<01:23,  8.10it/s, loss=0.00717]

Epoch 20 | Batch 2450/3125 | Loss: 0.0164

Epoch 20/30:  80%|████████  | 2502/3125 [05:27<01:21,  7.68it/s, loss=0.00788]

Epoch 20 | Batch 2500/3125 | Loss: 0.0065

Epoch 20/30:  82%|████████▏ | 2552/3125 [05:34<01:20,  7.14it/s, loss=0.00239]

Epoch 20 | Batch 2550/3125 | Loss: 0.0038

Epoch 20/30:  83%|████████▎ | 2601/3125 [05:40<01:03,  8.19it/s, loss=0.00324]

Epoch 20 | Batch 2600/3125 | Loss: 0.0088

Epoch 20/30:  85%|████████▍ | 2650/3125 [05:47<01:05,  7.30it/s, loss=0.0118]

Epoch 20 | Batch 2650/3125 | Loss: 0.0118

Epoch 20/30:  86%|████████▋ | 2702/3125 [05:54<00:54,  7.72it/s, loss=0.00156]

Epoch 20 | Batch 2700/3125 | Loss: 0.0038

Epoch 20/30:  88%|████████▊ | 2752/3125 [06:00<00:48,  7.69it/s, loss=0.00314]

Epoch 20 | Batch 2750/3125 | Loss: 0.0244

Epoch 20/30:  90%|████████▉ | 2802/3125 [06:07<00:43,  7.45it/s, loss=0.00452]

Epoch 20 | Batch 2800/3125 | Loss: 0.0110

Epoch 20/30:  91%|█████████▏| 2852/3125 [06:14<00:37,  7.37it/s, loss=0.00673]

Epoch 20 | Batch 2850/3125 | Loss: 0.0257

Epoch 20/30:  93%|█████████▎| 2902/3125 [06:20<00:28,  7.88it/s, loss=0.0321]

Epoch 20 | Batch 2900/3125 | Loss: 0.0132

Epoch 20/30:  94%|█████████▍| 2952/3125 [06:27<00:21,  7.86it/s, loss=0.0414]

Epoch 20 | Batch 2950/3125 | Loss: 0.0353

Epoch 20/30:  96%|█████████▌| 3002/3125 [06:33<00:15,  8.02it/s, loss=0.0122]

Epoch 20 | Batch 3000/3125 | Loss: 0.0185

Epoch 20/30:  98%|█████████▊| 3052/3125 [06:40<00:09,  7.75it/s, loss=0.0171]

Epoch 20 | Batch 3050/3125 | Loss: 0.0084

Epoch 20/30:  99%|█████████▉| 3102/3125 [06:46<00:02,  7.74it/s, loss=0.0168]

Epoch 20 | Batch 3100/3125 | Loss: 0.0016

Epoch 20/30: 100%|██████████| 3125/3125 [06:50<00:00,  7.62it/s, loss=0.00485]

Epoch [20/30] - Avg Loss: 0.0109

Epoch 21/30:   0%|          | 1/3125 [00:00<14:45,  3.53it/s, loss=0.00695]

Epoch 21 | Batch 0/3125 | Loss: 0.0041

Epoch 21/30:   2%|▏         | 52/3125 [00:06<06:53,  7.43it/s, loss=0.017]

Epoch 21 | Batch 50/3125 | Loss: 0.0083

Epoch 21/30:   3%|▎         | 102/3125 [00:13<06:34,  7.65it/s, loss=0.00248]

Epoch 21 | Batch 100/3125 | Loss: 0.0061

Epoch 21/30:   5%|▍         | 152/3125 [00:19<05:49,  8.49it/s, loss=0.00794]

Epoch 21 | Batch 150/3125 | Loss: 0.0032

Epoch 21/30:   6%|▋         | 200/3125 [00:25<06:18,  7.74it/s, loss=0.0077]

Epoch 21 | Batch 200/3125 | Loss: 0.0077

Epoch 21/30:   8%|▊         | 250/3125 [00:32<07:20,  6.52it/s, loss=0.00598]

Epoch 21 | Batch 250/3125 | Loss: 0.0060

Epoch 21/30:  10%|▉         | 302/3125 [00:39<05:49,  8.09it/s, loss=0.00516]

Epoch 21 | Batch 300/3125 | Loss: 0.0047

Epoch 21/30:  11%|█         | 351/3125 [00:45<05:38,  8.18it/s, loss=0.00198]

Epoch 21 | Batch 350/3125 | Loss: 0.0026

Epoch 21/30:  13%|█▎        | 401/3125 [00:52<06:05,  7.46it/s, loss=0.00315]

Epoch 21 | Batch 400/3125 | Loss: 0.0122

Epoch 21/30:  14%|█▍        | 451/3125 [00:58<05:22,  8.28it/s, loss=0.00624]

Epoch 21 | Batch 450/3125 | Loss: 0.0028

Epoch 21/30:  16%|█▌        | 501/3125 [01:04<05:27,  8.01it/s, loss=0.00297]

Epoch 21 | Batch 500/3125 | Loss: 0.0191

Epoch 21/30:  18%|█▊        | 552/3125 [01:12<06:22,  6.73it/s, loss=0.00276]

Epoch 21 | Batch 550/3125 | Loss: 0.0034

Epoch 21/30:  19%|█▉        | 602/3125 [01:18<05:33,  7.56it/s, loss=0.0113]

Epoch 21 | Batch 600/3125 | Loss: 0.0340

Epoch 21/30:  21%|██        | 651/3125 [01:24<05:31,  7.45it/s, loss=0.0324]

Epoch 21 | Batch 650/3125 | Loss: 0.0132

Epoch 21/30:  22%|██▏       | 701/3125 [01:30<05:25,  7.44it/s, loss=0.0168]

Epoch 21 | Batch 700/3125 | Loss: 0.0058

Epoch 21/30:  24%|██▍       | 751/3125 [01:37<04:55,  8.05it/s, loss=0.0101]

Epoch 21 | Batch 750/3125 | Loss: 0.0096

Epoch 21/30:  26%|██▌       | 801/3125 [01:43<05:44,  6.75it/s, loss=0.00409]

Epoch 21 | Batch 800/3125 | Loss: 0.0072

Epoch 21/30:  27%|██▋       | 851/3125 [01:50<04:46,  7.95it/s, loss=0.037]

Epoch 21 | Batch 850/3125 | Loss: 0.0067

Epoch 21/30:  29%|██▉       | 901/3125 [01:57<05:08,  7.22it/s, loss=0.00246]

Epoch 21 | Batch 900/3125 | Loss: 0.0051

Epoch 21/30:  30%|███       | 951/3125 [02:03<04:35,  7.88it/s, loss=0.0214]

Epoch 21 | Batch 950/3125 | Loss: 0.0038

Epoch 21/30:  32%|███▏      | 1001/3125 [02:10<04:57,  7.13it/s, loss=0.00717]

Epoch 21 | Batch 1000/3125 | Loss: 0.0037

Epoch 21/30:  34%|███▎      | 1051/3125 [02:16<04:39,  7.43it/s, loss=0.0132]

Epoch 21 | Batch 1050/3125 | Loss: 0.0045

Epoch 21/30:  35%|███▌      | 1101/3125 [02:24<05:08,  6.56it/s, loss=0.0079]

Epoch 21 | Batch 1100/3125 | Loss: 0.0044

Epoch 21/30:  37%|███▋      | 1151/3125 [02:30<04:18,  7.62it/s, loss=0.0318]

Epoch 21 | Batch 1150/3125 | Loss: 0.0462

Epoch 21/30:  38%|███▊      | 1201/3125 [02:37<04:01,  7.96it/s, loss=0.00327]

Epoch 21 | Batch 1200/3125 | Loss: 0.0031

Epoch 21/30:  40%|████      | 1251/3125 [02:43<03:57,  7.89it/s, loss=0.0496]

Epoch 21 | Batch 1250/3125 | Loss: 0.0048

Epoch 21/30:  42%|████▏     | 1301/3125 [02:50<03:43,  8.15it/s, loss=0.0149]

Epoch 21 | Batch 1300/3125 | Loss: 0.0887

Epoch 21/30:  43%|████▎     | 1351/3125 [02:56<04:18,  6.86it/s, loss=0.00366]

Epoch 21 | Batch 1350/3125 | Loss: 0.0051

Epoch 21/30:  45%|████▍     | 1402/3125 [03:03<03:40,  7.80it/s, loss=0.0101]

Epoch 21 | Batch 1400/3125 | Loss: 0.0041

Epoch 21/30:  46%|████▋     | 1451/3125 [03:10<03:50,  7.25it/s, loss=0.00876]

Epoch 21 | Batch 1450/3125 | Loss: 0.0073

Epoch 21/30:  48%|████▊     | 1501/3125 [03:16<03:23,  7.98it/s, loss=0.021]

Epoch 21 | Batch 1500/3125 | Loss: 0.0118

Epoch 21/30:  50%|████▉     | 1552/3125 [03:23<03:03,  8.59it/s, loss=0.00365]

Epoch 21 | Batch 1550/3125 | Loss: 0.0057

Epoch 21/30:  51%|█████▏    | 1602/3125 [03:29<03:14,  7.84it/s, loss=0.0041]

Epoch 21 | Batch 1600/3125 | Loss: 0.0083

Epoch 21/30:  53%|█████▎    | 1652/3125 [03:36<03:21,  7.32it/s, loss=0.0417]

Epoch 21 | Batch 1650/3125 | Loss: 0.0066

Epoch 21/30:  54%|█████▍    | 1700/3125 [03:43<03:03,  7.78it/s, loss=0.00556]

Epoch 21 | Batch 1700/3125 | Loss: 0.0056

Epoch 21/30:  56%|█████▌    | 1752/3125 [03:50<02:46,  8.22it/s, loss=0.00404]

Epoch 21 | Batch 1750/3125 | Loss: 0.0124

Epoch 21/30:  58%|█████▊    | 1802/3125 [03:56<02:45,  8.02it/s, loss=0.00967]

Epoch 21 | Batch 1800/3125 | Loss: 0.0101

Epoch 21/30:  59%|█████▉    | 1852/3125 [04:02<02:51,  7.43it/s, loss=0.0392]

Epoch 21 | Batch 1850/3125 | Loss: 0.0053

Epoch 21/30:  61%|██████    | 1900/3125 [04:09<02:56,  6.96it/s, loss=0.00646]

Epoch 21 | Batch 1900/3125 | Loss: 0.0065

Epoch 21/30:  62%|██████▏   | 1950/3125 [04:16<02:42,  7.25it/s, loss=0.00302]

Epoch 21 | Batch 1950/3125 | Loss: 0.0030

Epoch 21/30:  64%|██████▍   | 2002/3125 [04:22<02:23,  7.84it/s, loss=0.00151]

Epoch 21 | Batch 2000/3125 | Loss: 0.0047

Epoch 21/30:  66%|██████▌   | 2052/3125 [04:29<02:13,  8.06it/s, loss=0.0025]

Epoch 21 | Batch 2050/3125 | Loss: 0.0022

Epoch 21/30:  67%|██████▋   | 2102/3125 [04:35<02:14,  7.58it/s, loss=0.0078]

Epoch 21 | Batch 2100/3125 | Loss: 0.0070

Epoch 21/30:  69%|██████▉   | 2151/3125 [04:42<02:16,  7.14it/s, loss=0.00472]

Epoch 21 | Batch 2150/3125 | Loss: 0.0178

Epoch 21/30:  70%|███████   | 2202/3125 [04:49<02:02,  7.51it/s, loss=0.0401]

Epoch 21 | Batch 2200/3125 | Loss: 0.0045

Epoch 21/30:  72%|███████▏  | 2252/3125 [04:56<01:53,  7.70it/s, loss=0.00562]

Epoch 21 | Batch 2250/3125 | Loss: 0.0046

Epoch 21/30:  74%|███████▎  | 2302/3125 [05:02<01:39,  8.27it/s, loss=0.00902]

Epoch 21 | Batch 2300/3125 | Loss: 0.0068

Epoch 21/30:  75%|███████▌  | 2352/3125 [05:08<01:33,  8.30it/s, loss=0.0029]

Epoch 21 | Batch 2350/3125 | Loss: 0.0034

Epoch 21/30:  77%|███████▋  | 2402/3125 [05:14<01:28,  8.16it/s, loss=0.00975]

Epoch 21 | Batch 2400/3125 | Loss: 0.0041

Epoch 21/30:  78%|███████▊  | 2452/3125 [05:21<01:30,  7.40it/s, loss=0.00834]

Epoch 21 | Batch 2450/3125 | Loss: 0.0051

Epoch 21/30:  80%|████████  | 2502/3125 [05:28<01:14,  8.35it/s, loss=0.00739]

Epoch 21 | Batch 2500/3125 | Loss: 0.0047

Epoch 21/30:  82%|████████▏ | 2552/3125 [05:34<01:12,  7.92it/s, loss=0.00347]

Epoch 21 | Batch 2550/3125 | Loss: 0.0101

Epoch 21/30:  83%|████████▎ | 2602/3125 [05:40<01:01,  8.55it/s, loss=0.00445]

Epoch 21 | Batch 2600/3125 | Loss: 0.0161

Epoch 21/30:  85%|████████▍ | 2650/3125 [05:46<00:58,  8.16it/s, loss=0.00129]

Epoch 21 | Batch 2650/3125 | Loss: 0.0013

Epoch 21/30:  86%|████████▋ | 2702/3125 [05:52<00:51,  8.25it/s, loss=0.00278]

Epoch 21 | Batch 2700/3125 | Loss: 0.0025

Epoch 21/30:  88%|████████▊ | 2750/3125 [05:59<00:54,  6.87it/s, loss=0.0257]

Epoch 21 | Batch 2750/3125 | Loss: 0.0257

Epoch 21/30:  90%|████████▉ | 2800/3125 [06:06<00:40,  8.11it/s, loss=0.0103]

Epoch 21 | Batch 2800/3125 | Loss: 0.0103

Epoch 21/30:  91%|█████████▏| 2852/3125 [06:12<00:34,  7.83it/s, loss=0.00559]

Epoch 21 | Batch 2850/3125 | Loss: 0.0075

Epoch 21/30:  93%|█████████▎| 2901/3125 [06:18<00:27,  8.06it/s, loss=0.0075]

Epoch 21 | Batch 2900/3125 | Loss: 0.0267

Epoch 21/30:  94%|█████████▍| 2951/3125 [06:24<00:21,  8.07it/s, loss=0.00222]

Epoch 21 | Batch 2950/3125 | Loss: 0.0048

Epoch 21/30:  96%|█████████▌| 3001/3125 [06:31<00:15,  8.13it/s, loss=0.0191]

Epoch 21 | Batch 3000/3125 | Loss: 0.0132

Epoch 21/30:  98%|█████████▊| 3051/3125 [06:38<00:10,  7.13it/s, loss=0.0163]

Epoch 21 | Batch 3050/3125 | Loss: 0.0073

Epoch 21/30:  99%|█████████▉| 3101/3125 [06:44<00:02,  8.43it/s, loss=0.00797]

Epoch 21 | Batch 3100/3125 | Loss: 0.0206

Epoch 21/30: 100%|██████████| 3125/3125 [06:47<00:00,  7.67it/s, loss=0.00463]

Epoch [21/30] - Avg Loss: 0.0095

Epoch 22/30:   0%|          | 1/3125 [00:00<15:12,  3.42it/s, loss=0.00716]

Epoch 22 | Batch 0/3125 | Loss: 0.0049

Epoch 22/30:   2%|▏         | 51/3125 [00:06<05:52,  8.73it/s, loss=0.0036]

Epoch 22 | Batch 50/3125 | Loss: 0.0036

Epoch 22/30:   3%|▎         | 101/3125 [00:12<06:04,  8.30it/s, loss=0.00172]

Epoch 22 | Batch 100/3125 | Loss: 0.0139

Epoch 22/30:   5%|▍         | 151/3125 [00:18<05:46,  8.59it/s, loss=0.00215]

Epoch 22 | Batch 150/3125 | Loss: 0.0021

Epoch 22/30:   6%|▋         | 201/3125 [00:25<07:27,  6.54it/s, loss=0.0578]

Epoch 22 | Batch 200/3125 | Loss: 0.0035

Epoch 22/30:   8%|▊         | 251/3125 [00:32<06:01,  7.95it/s, loss=0.00247]

Epoch 22 | Batch 250/3125 | Loss: 0.0032

Epoch 22/30:  10%|▉         | 301/3125 [00:38<05:33,  8.47it/s, loss=0.00801]

Epoch 22 | Batch 300/3125 | Loss: 0.0028

Epoch 22/30:  11%|█         | 351/3125 [00:44<05:53,  7.85it/s, loss=0.00211]

Epoch 22 | Batch 350/3125 | Loss: 0.0096

Epoch 22/30:  13%|█▎        | 401/3125 [00:50<05:40,  7.99it/s, loss=0.00475]

Epoch 22 | Batch 400/3125 | Loss: 0.0063

Epoch 22/30:  14%|█▍        | 451/3125 [00:56<05:33,  8.01it/s, loss=0.0139]

Epoch 22 | Batch 450/3125 | Loss: 0.0068

Epoch 22/30:  16%|█▌        | 501/3125 [01:03<05:31,  7.91it/s, loss=0.0105]

Epoch 22 | Batch 500/3125 | Loss: 0.0079

Epoch 22/30:  18%|█▊        | 551/3125 [01:09<05:23,  7.97it/s, loss=0.00309]

Epoch 22 | Batch 550/3125 | Loss: 0.0040

Epoch 22/30:  19%|█▉        | 601/3125 [01:16<05:06,  8.25it/s, loss=0.00585]

Epoch 22 | Batch 600/3125 | Loss: 0.0080

Epoch 22/30:  21%|██        | 651/3125 [01:22<05:22,  7.68it/s, loss=0.00817]

Epoch 22 | Batch 650/3125 | Loss: 0.0108

Epoch 22/30:  22%|██▏       | 701/3125 [01:28<04:41,  8.62it/s, loss=0.00262]

Epoch 22 | Batch 700/3125 | Loss: 0.0065

Epoch 22/30:  24%|██▍       | 750/3125 [01:34<05:59,  6.60it/s, loss=0.00104]

Epoch 22 | Batch 750/3125 | Loss: 0.0010

Epoch 22/30:  26%|██▌       | 802/3125 [01:41<05:06,  7.59it/s, loss=0.0046]

Epoch 22 | Batch 800/3125 | Loss: 0.0077

Epoch 22/30:  27%|██▋       | 852/3125 [01:47<04:30,  8.40it/s, loss=0.00664]

Epoch 22 | Batch 850/3125 | Loss: 0.0111

Epoch 22/30:  29%|██▉       | 902/3125 [01:53<04:30,  8.22it/s, loss=0.00496]

Epoch 22 | Batch 900/3125 | Loss: 0.0176

Epoch 22/30:  30%|███       | 952/3125 [02:00<04:23,  8.26it/s, loss=0.00578]

Epoch 22 | Batch 950/3125 | Loss: 0.0021

Epoch 22/30:  32%|███▏      | 1002/3125 [02:06<04:19,  8.17it/s, loss=0.00529]

Epoch 22 | Batch 1000/3125 | Loss: 0.0044

Epoch 22/30:  34%|███▎      | 1051/3125 [02:12<04:51,  7.11it/s, loss=0.00567]

Epoch 22 | Batch 1050/3125 | Loss: 0.0109

Epoch 22/30:  35%|███▌      | 1101/3125 [02:19<04:13,  7.97it/s, loss=0.0152]

Epoch 22 | Batch 1100/3125 | Loss: 0.0029

Epoch 22/30:  37%|███▋      | 1151/3125 [02:25<03:58,  8.26it/s, loss=0.00213]

Epoch 22 | Batch 1150/3125 | Loss: 0.0100

Epoch 22/30:  38%|███▊      | 1201/3125 [02:31<03:56,  8.13it/s, loss=0.0659]

Epoch 22 | Batch 1200/3125 | Loss: 0.0028

Epoch 22/30:  40%|████      | 1251/3125 [02:37<03:43,  8.39it/s, loss=0.0331]

Epoch 22 | Batch 1250/3125 | Loss: 0.0067

Epoch 22/30:  42%|████▏     | 1301/3125 [02:43<03:51,  7.89it/s, loss=0.00986]

Epoch 22 | Batch 1300/3125 | Loss: 0.0067

Epoch 22/30:  43%|████▎     | 1352/3125 [02:50<04:15,  6.95it/s, loss=0.00503]

Epoch 22 | Batch 1350/3125 | Loss: 0.0053

Epoch 22/30:  45%|████▍     | 1401/3125 [02:57<03:44,  7.68it/s, loss=0.0132]

Epoch 22 | Batch 1400/3125 | Loss: 0.0045

Epoch 22/30:  46%|████▋     | 1451/3125 [03:03<03:17,  8.49it/s, loss=0.00289]

Epoch 22 | Batch 1450/3125 | Loss: 0.0207

Epoch 22/30:  48%|████▊     | 1501/3125 [03:09<03:33,  7.60it/s, loss=0.00875]

Epoch 22 | Batch 1500/3125 | Loss: 0.0295

Epoch 22/30:  50%|████▉     | 1551/3125 [03:15<03:08,  8.35it/s, loss=0.00412]

Epoch 22 | Batch 1550/3125 | Loss: 0.0029

Epoch 22/30:  51%|█████     | 1601/3125 [03:22<03:05,  8.21it/s, loss=0.00345]

Epoch 22 | Batch 1600/3125 | Loss: 0.0027

Epoch 22/30:  53%|█████▎    | 1651/3125 [03:29<03:24,  7.19it/s, loss=0.00226]

Epoch 22 | Batch 1650/3125 | Loss: 0.0122

Epoch 22/30:  54%|█████▍    | 1701/3125 [03:35<02:49,  8.42it/s, loss=0.00279]

Epoch 22 | Batch 1700/3125 | Loss: 0.0027

Epoch 22/30:  56%|█████▌    | 1751/3125 [03:41<02:46,  8.26it/s, loss=0.00833]

Epoch 22 | Batch 1750/3125 | Loss: 0.0067

Epoch 22/30:  58%|█████▊    | 1802/3125 [03:48<02:47,  7.92it/s, loss=0.00408]

Epoch 22 | Batch 1800/3125 | Loss: 0.0071

Epoch 22/30:  59%|█████▉    | 1852/3125 [03:54<02:34,  8.26it/s, loss=0.0203]

Epoch 22 | Batch 1850/3125 | Loss: 0.0048

Epoch 22/30:  61%|██████    | 1901/3125 [04:00<03:06,  6.57it/s, loss=0.0021]

Epoch 22 | Batch 1900/3125 | Loss: 0.0091

Epoch 22/30:  62%|██████▏   | 1951/3125 [04:07<02:26,  7.99it/s, loss=0.00197]

Epoch 22 | Batch 1950/3125 | Loss: 0.0028

Epoch 22/30:  64%|██████▍   | 2001/3125 [04:14<02:17,  8.15it/s, loss=0.00418]

Epoch 22 | Batch 2000/3125 | Loss: 0.0002

Epoch 22/30:  66%|██████▌   | 2051/3125 [04:20<02:11,  8.19it/s, loss=0.0371]

Epoch 22 | Batch 2050/3125 | Loss: 0.0074

Epoch 22/30:  67%|██████▋   | 2101/3125 [04:26<02:06,  8.10it/s, loss=0.00755]

Epoch 22 | Batch 2100/3125 | Loss: 0.0017

Epoch 22/30:  69%|██████▉   | 2151/3125 [04:33<02:06,  7.70it/s, loss=0.0507]

Epoch 22 | Batch 2150/3125 | Loss: 0.0081

Epoch 22/30:  70%|███████   | 2201/3125 [04:39<02:20,  6.57it/s, loss=0.0417]

Epoch 22 | Batch 2200/3125 | Loss: 0.0256

Epoch 22/30:  72%|███████▏  | 2251/3125 [04:46<01:51,  7.84it/s, loss=0.0164]

Epoch 22 | Batch 2250/3125 | Loss: 0.0096

Epoch 22/30:  74%|███████▎  | 2301/3125 [04:52<01:44,  7.90it/s, loss=0.00211]

Epoch 22 | Batch 2300/3125 | Loss: 0.0119

Epoch 22/30:  75%|███████▌  | 2351/3125 [04:59<01:39,  7.75it/s, loss=0.0089]

Epoch 22 | Batch 2350/3125 | Loss: 0.0093

Epoch 22/30:  77%|███████▋  | 2401/3125 [05:05<01:26,  8.33it/s, loss=0.021]

Epoch 22 | Batch 2400/3125 | Loss: 0.0035

Epoch 22/30:  78%|███████▊  | 2451/3125 [05:11<01:25,  7.88it/s, loss=0.00593]

Epoch 22 | Batch 2450/3125 | Loss: 0.0054

Epoch 22/30:  80%|████████  | 2501/3125 [05:19<01:37,  6.40it/s, loss=0.0105]

Epoch 22 | Batch 2500/3125 | Loss: 0.0143

Epoch 22/30:  82%|████████▏ | 2551/3125 [05:25<01:12,  7.92it/s, loss=0.00337]

Epoch 22 | Batch 2550/3125 | Loss: 0.0112

Epoch 22/30:  83%|████████▎ | 2601/3125 [05:31<01:03,  8.31it/s, loss=0.00434]

Epoch 22 | Batch 2600/3125 | Loss: 0.0091

Epoch 22/30:  85%|████████▍ | 2651/3125 [05:37<00:59,  8.01it/s, loss=0.00438]

Epoch 22 | Batch 2650/3125 | Loss: 0.0274

Epoch 22/30:  86%|████████▋ | 2701/3125 [05:44<00:52,  8.14it/s, loss=0.00917]

Epoch 22 | Batch 2700/3125 | Loss: 0.0087

Epoch 22/30:  88%|████████▊ | 2751/3125 [05:50<00:52,  7.17it/s, loss=0.00214]

Epoch 22 | Batch 2750/3125 | Loss: 0.0043

Epoch 22/30:  90%|████████▉ | 2802/3125 [05:57<00:42,  7.60it/s, loss=0.00587]

Epoch 22 | Batch 2800/3125 | Loss: 0.0122

Epoch 22/30:  91%|█████████ | 2851/3125 [06:04<00:34,  8.02it/s, loss=0.0342]

Epoch 22 | Batch 2850/3125 | Loss: 0.0013

Epoch 22/30:  93%|█████████▎| 2901/3125 [06:10<00:29,  7.53it/s, loss=0.00227]

Epoch 22 | Batch 2900/3125 | Loss: 0.0157

Epoch 22/30:  94%|█████████▍| 2951/3125 [06:16<00:21,  8.01it/s, loss=0.0142]

Epoch 22 | Batch 2950/3125 | Loss: 0.0657

Epoch 22/30:  96%|█████████▌| 3001/3125 [06:22<00:16,  7.62it/s, loss=0.0124]

Epoch 22 | Batch 3000/3125 | Loss: 0.0033

Epoch 22/30:  98%|█████████▊| 3051/3125 [06:29<00:11,  6.28it/s, loss=0.0108]

Epoch 22 | Batch 3050/3125 | Loss: 0.0027

Epoch 22/30:  99%|█████████▉| 3101/3125 [06:36<00:03,  7.70it/s, loss=0.00322]

Epoch 22 | Batch 3100/3125 | Loss: 0.0060

Epoch 22/30: 100%|██████████| 3125/3125 [06:39<00:00,  7.83it/s, loss=0.00259]

Epoch [22/30] - Avg Loss: 0.0096

Epoch 23/30:   0%|          | 1/3125 [00:00<15:22,  3.39it/s, loss=0.00251]

Epoch 23 | Batch 0/3125 | Loss: 0.0033

Epoch 23/30:   2%|▏         | 51/3125 [00:06<06:27,  7.94it/s, loss=0.0235]

Epoch 23 | Batch 50/3125 | Loss: 0.0040

Epoch 23/30:   3%|▎         | 101/3125 [00:12<06:02,  8.34it/s, loss=0.0143]

Epoch 23 | Batch 100/3125 | Loss: 0.0260

Epoch 23/30:   5%|▍         | 151/3125 [00:18<06:20,  7.82it/s, loss=0.00439]

Epoch 23 | Batch 150/3125 | Loss: 0.0052

Epoch 23/30:   6%|▋         | 202/3125 [00:25<06:58,  6.99it/s, loss=0.00964]

Epoch 23 | Batch 200/3125 | Loss: 0.0063

Epoch 23/30:   8%|▊         | 251/3125 [00:32<05:48,  8.25it/s, loss=0.0539]

Epoch 23 | Batch 250/3125 | Loss: 0.0067

Epoch 23/30:  10%|▉         | 301/3125 [00:38<05:50,  8.06it/s, loss=0.014]

Epoch 23 | Batch 300/3125 | Loss: 0.0024

Epoch 23/30:  11%|█         | 351/3125 [00:45<05:49,  7.94it/s, loss=0.00609]

Epoch 23 | Batch 350/3125 | Loss: 0.0111

Epoch 23/30:  13%|█▎        | 401/3125 [00:51<05:23,  8.41it/s, loss=0.016]

Epoch 23 | Batch 400/3125 | Loss: 0.0065

Epoch 23/30:  14%|█▍        | 451/3125 [00:57<05:33,  8.01it/s, loss=0.00472]

Epoch 23 | Batch 450/3125 | Loss: 0.0031

Epoch 23/30:  16%|█▌        | 500/3125 [01:04<07:51,  5.57it/s, loss=0.00538]

Epoch 23 | Batch 500/3125 | Loss: 0.0054

Epoch 23/30:  18%|█▊        | 552/3125 [01:11<05:30,  7.78it/s, loss=0.00546]

Epoch 23 | Batch 550/3125 | Loss: 0.0032

Epoch 23/30:  19%|█▉        | 600/3125 [01:17<05:18,  7.94it/s, loss=0.00671]

Epoch 23 | Batch 600/3125 | Loss: 0.0067

Epoch 23/30:  21%|██        | 652/3125 [01:23<05:03,  8.16it/s, loss=0.0071]

Epoch 23 | Batch 650/3125 | Loss: 0.0020

Epoch 23/30:  22%|██▏       | 702/3125 [01:29<04:58,  8.12it/s, loss=0.00221]

Epoch 23 | Batch 700/3125 | Loss: 0.0055

Epoch 23/30:  24%|██▍       | 752/3125 [01:36<04:53,  8.10it/s, loss=0.0136]

Epoch 23 | Batch 750/3125 | Loss: 0.0234

Epoch 23/30:  26%|██▌       | 800/3125 [01:43<06:01,  6.43it/s, loss=0.00685]

Epoch 23 | Batch 800/3125 | Loss: 0.0068

Epoch 23/30:  27%|██▋       | 852/3125 [01:49<04:31,  8.37it/s, loss=0.0153]

Epoch 23 | Batch 850/3125 | Loss: 0.0062

Epoch 23/30:  29%|██▉       | 901/3125 [01:55<04:38,  7.97it/s, loss=0.00796]

Epoch 23 | Batch 900/3125 | Loss: 0.0123

Epoch 23/30:  30%|███       | 952/3125 [02:02<04:28,  8.10it/s, loss=0.00256]

Epoch 23 | Batch 950/3125 | Loss: 0.0059

Epoch 23/30:  32%|███▏      | 1002/3125 [02:08<04:34,  7.73it/s, loss=0.00549]

Epoch 23 | Batch 1000/3125 | Loss: 0.0048

Epoch 23/30:  34%|███▎      | 1052/3125 [02:14<04:42,  7.34it/s, loss=0.00356]

Epoch 23 | Batch 1050/3125 | Loss: 0.0047

Epoch 23/30:  35%|███▌      | 1102/3125 [02:21<04:19,  7.80it/s, loss=0.00616]

Epoch 23 | Batch 1100/3125 | Loss: 0.0087

Epoch 23/30:  37%|███▋      | 1151/3125 [02:28<04:01,  8.18it/s, loss=0.00432]

Epoch 23 | Batch 1150/3125 | Loss: 0.0312

Epoch 23/30:  38%|███▊      | 1201/3125 [02:34<04:03,  7.91it/s, loss=0.0121]

Epoch 23 | Batch 1200/3125 | Loss: 0.0033

Epoch 23/30:  40%|████      | 1251/3125 [02:40<04:01,  7.77it/s, loss=0.0262]

Epoch 23 | Batch 1250/3125 | Loss: 0.0034

Epoch 23/30:  42%|████▏     | 1301/3125 [02:47<03:59,  7.61it/s, loss=0.00434]

Epoch 23 | Batch 1300/3125 | Loss: 0.0057

Epoch 23/30:  43%|████▎     | 1350/3125 [02:53<04:32,  6.52it/s, loss=0.00812]

Epoch 23 | Batch 1350/3125 | Loss: 0.0081

Epoch 23/30:  45%|████▍     | 1402/3125 [03:00<04:01,  7.15it/s, loss=0.0017]

Epoch 23 | Batch 1400/3125 | Loss: 0.0057

Epoch 23/30:  46%|████▋     | 1450/3125 [03:06<03:50,  7.27it/s, loss=0.0301]

Epoch 23 | Batch 1450/3125 | Loss: 0.0301

Epoch 23/30:  48%|████▊     | 1502/3125 [03:13<03:34,  7.57it/s, loss=0.0018]

Epoch 23 | Batch 1500/3125 | Loss: 0.0024

Epoch 23/30:  50%|████▉     | 1552/3125 [03:19<03:08,  8.36it/s, loss=0.00644]

Epoch 23 | Batch 1550/3125 | Loss: 0.0023

Epoch 23/30:  51%|█████     | 1601/3125 [03:25<03:12,  7.94it/s, loss=0.0016]

Epoch 23 | Batch 1600/3125 | Loss: 0.0021

Epoch 23/30:  53%|█████▎    | 1652/3125 [03:32<03:20,  7.35it/s, loss=0.00303]

Epoch 23 | Batch 1650/3125 | Loss: 0.0030

Epoch 23/30:  54%|█████▍    | 1702/3125 [03:39<02:55,  8.12it/s, loss=0.00471]

Epoch 23 | Batch 1700/3125 | Loss: 0.0019

Epoch 23/30:  56%|█████▌    | 1752/3125 [03:45<02:54,  7.85it/s, loss=0.0118]

Epoch 23 | Batch 1750/3125 | Loss: 0.0019

Epoch 23/30:  58%|█████▊    | 1802/3125 [03:52<02:53,  7.63it/s, loss=0.00499]

Epoch 23 | Batch 1800/3125 | Loss: 0.0019

Epoch 23/30:  59%|█████▉    | 1852/3125 [03:58<02:37,  8.07it/s, loss=0.00453]

Epoch 23 | Batch 1850/3125 | Loss: 0.0066

Epoch 23/30:  61%|██████    | 1902/3125 [04:04<02:31,  8.08it/s, loss=0.00551]

Epoch 23 | Batch 1900/3125 | Loss: 0.0120

Epoch 23/30:  62%|██████▏   | 1950/3125 [04:11<02:47,  7.02it/s, loss=0.00246]

Epoch 23 | Batch 1950/3125 | Loss: 0.0025

Epoch 23/30:  64%|██████▍   | 2002/3125 [04:18<02:19,  8.06it/s, loss=0.00886]

Epoch 23 | Batch 2000/3125 | Loss: 0.0085

Epoch 23/30:  66%|██████▌   | 2052/3125 [04:24<02:15,  7.93it/s, loss=0.00528]

Epoch 23 | Batch 2050/3125 | Loss: 0.0021

Epoch 23/30:  67%|██████▋   | 2100/3125 [04:30<02:13,  7.70it/s, loss=0.00208]

Epoch 23 | Batch 2100/3125 | Loss: 0.0021

Epoch 23/30:  69%|██████▉   | 2152/3125 [04:37<01:56,  8.38it/s, loss=0.00746]

Epoch 23 | Batch 2150/3125 | Loss: 0.0037

Epoch 23/30:  70%|███████   | 2201/3125 [04:43<02:11,  7.03it/s, loss=0.00235]

Epoch 23 | Batch 2200/3125 | Loss: 0.0020

Epoch 23/30:  72%|███████▏  | 2251/3125 [04:50<02:00,  7.26it/s, loss=0.00459]

Epoch 23 | Batch 2250/3125 | Loss: 0.0027

Epoch 23/30:  74%|███████▎  | 2301/3125 [04:57<01:43,  7.99it/s, loss=0.00379]

Epoch 23 | Batch 2300/3125 | Loss: 0.0026

Epoch 23/30:  75%|███████▌  | 2351/3125 [05:03<01:38,  7.86it/s, loss=0.00411]

Epoch 23 | Batch 2350/3125 | Loss: 0.0024

Epoch 23/30:  77%|███████▋  | 2401/3125 [05:10<01:34,  7.68it/s, loss=0.00778]

Epoch 23 | Batch 2400/3125 | Loss: 0.0036

Epoch 23/30:  78%|███████▊  | 2451/3125 [05:16<01:29,  7.56it/s, loss=0.00895]

Epoch 23 | Batch 2450/3125 | Loss: 0.0039

Epoch 23/30:  80%|████████  | 2501/3125 [05:23<01:34,  6.60it/s, loss=0.00464]

Epoch 23 | Batch 2500/3125 | Loss: 0.0066

Epoch 23/30:  82%|████████▏ | 2551/3125 [05:30<01:15,  7.65it/s, loss=0.00212]

Epoch 23 | Batch 2550/3125 | Loss: 0.0107

Epoch 23/30:  83%|████████▎ | 2601/3125 [05:36<01:08,  7.65it/s, loss=0.00914]

Epoch 23 | Batch 2600/3125 | Loss: 0.0171

Epoch 23/30:  85%|████████▍ | 2651/3125 [05:43<01:00,  7.77it/s, loss=0.00252]

Epoch 23 | Batch 2650/3125 | Loss: 0.0248

Epoch 23/30:  86%|████████▋ | 2701/3125 [05:49<00:48,  8.71it/s, loss=0.00642]

Epoch 23 | Batch 2700/3125 | Loss: 0.0083

Epoch 23/30:  88%|████████▊ | 2752/3125 [05:55<00:46,  8.01it/s, loss=0.00462]

Epoch 23 | Batch 2750/3125 | Loss: 0.0034

Epoch 23/30:  90%|████████▉ | 2801/3125 [06:02<00:42,  7.59it/s, loss=0.00405]

Epoch 23 | Batch 2800/3125 | Loss: 0.0041

Epoch 23/30:  91%|█████████▏| 2852/3125 [06:08<00:33,  8.03it/s, loss=0.011]

Epoch 23 | Batch 2850/3125 | Loss: 0.0029

Epoch 23/30:  93%|█████████▎| 2901/3125 [06:15<00:27,  8.09it/s, loss=0.00314]

Epoch 23 | Batch 2900/3125 | Loss: 0.0026

Epoch 23/30:  94%|█████████▍| 2951/3125 [06:21<00:21,  8.04it/s, loss=0.0169]

Epoch 23 | Batch 2950/3125 | Loss: 0.0079

Epoch 23/30:  96%|█████████▌| 3001/3125 [06:27<00:15,  8.12it/s, loss=0.00506]

Epoch 23 | Batch 3000/3125 | Loss: 0.0046

Epoch 23/30:  98%|█████████▊| 3051/3125 [06:33<00:08,  8.37it/s, loss=0.00219]

Epoch 23 | Batch 3050/3125 | Loss: 0.0034

Epoch 23/30:  99%|█████████▉| 3101/3125 [06:41<00:03,  7.05it/s, loss=0.00203]

Epoch 23 | Batch 3100/3125 | Loss: 0.0098

Epoch 23/30: 100%|██████████| 3125/3125 [06:43<00:00,  7.74it/s, loss=0.00577]

Epoch [23/30] - Avg Loss: 0.0083

Epoch 24/30:   0%|          | 1/3125 [00:00<15:27,  3.37it/s, loss=0.00114]

Epoch 24 | Batch 0/3125 | Loss: 0.0074

Epoch 24/30:   2%|▏         | 51/3125 [00:06<06:14,  8.20it/s, loss=0.00249]

Epoch 24 | Batch 50/3125 | Loss: 0.0038

Epoch 24/30:   3%|▎         | 101/3125 [00:12<06:17,  8.01it/s, loss=0.00351]

Epoch 24 | Batch 100/3125 | Loss: 0.0089

Epoch 24/30:   5%|▍         | 151/3125 [00:18<06:46,  7.32it/s, loss=0.00454]

Epoch 24 | Batch 150/3125 | Loss: 0.0056

Epoch 24/30:   6%|▋         | 201/3125 [00:25<06:08,  7.94it/s, loss=0.0253]

Epoch 24 | Batch 200/3125 | Loss: 0.0037

Epoch 24/30:   8%|▊         | 251/3125 [00:32<06:42,  7.14it/s, loss=0.00253]

Epoch 24 | Batch 250/3125 | Loss: 0.0251

Epoch 24/30:  10%|▉         | 302/3125 [00:38<06:00,  7.83it/s, loss=0.0499]

Epoch 24 | Batch 300/3125 | Loss: 0.0270

Epoch 24/30:  11%|█▏        | 352/3125 [00:45<05:45,  8.02it/s, loss=0.00386]

Epoch 24 | Batch 350/3125 | Loss: 0.0131

Epoch 24/30:  13%|█▎        | 402/3125 [00:51<05:39,  8.03it/s, loss=0.00259]

Epoch 24 | Batch 400/3125 | Loss: 0.0045

Epoch 24/30:  14%|█▍        | 452/3125 [00:57<05:30,  8.10it/s, loss=0.0233]

Epoch 24 | Batch 450/3125 | Loss: 0.0022

Epoch 24/30:  16%|█▌        | 502/3125 [01:03<05:26,  8.04it/s, loss=0.0112]

Epoch 24 | Batch 500/3125 | Loss: 0.0012

Epoch 24/30:  18%|█▊        | 550/3125 [01:10<05:57,  7.21it/s, loss=0.00858]

Epoch 24 | Batch 550/3125 | Loss: 0.0086

Epoch 24/30:  19%|█▉        | 602/3125 [01:17<05:17,  7.94it/s, loss=0.0103]

Epoch 24 | Batch 600/3125 | Loss: 0.0165

Epoch 24/30:  21%|██        | 652/3125 [01:23<05:11,  7.93it/s, loss=0.0116]

Epoch 24 | Batch 650/3125 | Loss: 0.0051

Epoch 24/30:  22%|██▏       | 702/3125 [01:29<05:01,  8.03it/s, loss=0.00474]

Epoch 24 | Batch 700/3125 | Loss: 0.0021

Epoch 24/30:  24%|██▍       | 752/3125 [01:36<04:43,  8.37it/s, loss=0.00631]

Epoch 24 | Batch 750/3125 | Loss: 0.0035

Epoch 24/30:  26%|██▌       | 800/3125 [01:42<05:15,  7.37it/s, loss=0.00101]

Epoch 24 | Batch 800/3125 | Loss: 0.0010

Epoch 24/30:  27%|██▋       | 852/3125 [01:49<05:01,  7.54it/s, loss=0.001]

Epoch 24 | Batch 850/3125 | Loss: 0.0022

Epoch 24/30:  29%|██▉       | 902/3125 [01:56<04:43,  7.84it/s, loss=0.0026]

Epoch 24 | Batch 900/3125 | Loss: 0.0054

Epoch 24/30:  30%|███       | 952/3125 [02:02<04:30,  8.04it/s, loss=0.0179]

Epoch 24 | Batch 950/3125 | Loss: 0.0141

Epoch 24/30:  32%|███▏      | 1002/3125 [02:08<04:20,  8.15it/s, loss=0.00169]

Epoch 24 | Batch 1000/3125 | Loss: 0.0019

Epoch 24/30:  34%|███▎      | 1051/3125 [02:14<04:10,  8.27it/s, loss=0.00498]

Epoch 24 | Batch 1050/3125 | Loss: 0.0026

Epoch 24/30:  35%|███▌      | 1100/3125 [02:21<05:10,  6.52it/s, loss=0.00306]

Epoch 24 | Batch 1100/3125 | Loss: 0.0031

Epoch 24/30:  37%|███▋      | 1152/3125 [02:28<04:13,  7.78it/s, loss=0.00256]

Epoch 24 | Batch 1150/3125 | Loss: 0.0026

Epoch 24/30:  38%|███▊      | 1202/3125 [02:34<04:21,  7.35it/s, loss=0.00347]

Epoch 24 | Batch 1200/3125 | Loss: 0.0018

Epoch 24/30:  40%|████      | 1251/3125 [02:40<04:01,  7.77it/s, loss=0.0171]

Epoch 24 | Batch 1250/3125 | Loss: 0.0061

Epoch 24/30:  42%|████▏     | 1301/3125 [02:47<03:57,  7.69it/s, loss=0.0167]

Epoch 24 | Batch 1300/3125 | Loss: 0.0558

Epoch 24/30:  43%|████▎     | 1351/3125 [02:53<03:51,  7.65it/s, loss=0.0131]

Epoch 24 | Batch 1350/3125 | Loss: 0.0355

Epoch 24/30:  45%|████▍     | 1401/3125 [03:01<03:55,  7.33it/s, loss=0.00774]

Epoch 24 | Batch 1400/3125 | Loss: 0.0036

Epoch 24/30:  46%|████▋     | 1451/3125 [03:07<03:23,  8.22it/s, loss=0.00781]

Epoch 24 | Batch 1450/3125 | Loss: 0.0057

Epoch 24/30:  48%|████▊     | 1501/3125 [03:13<03:27,  7.84it/s, loss=0.0117]

Epoch 24 | Batch 1500/3125 | Loss: 0.0071

Epoch 24/30:  50%|████▉     | 1551/3125 [03:20<03:29,  7.52it/s, loss=0.00265]

Epoch 24 | Batch 1550/3125 | Loss: 0.0039

Epoch 24/30:  51%|█████     | 1601/3125 [03:26<03:13,  7.89it/s, loss=0.0168]

Epoch 24 | Batch 1600/3125 | Loss: 0.0040

Epoch 24/30:  53%|█████▎    | 1652/3125 [03:33<03:16,  7.49it/s, loss=0.008]

Epoch 24 | Batch 1650/3125 | Loss: 0.0046

Epoch 24/30:  54%|█████▍    | 1701/3125 [03:40<03:03,  7.76it/s, loss=0.00519]

Epoch 24 | Batch 1700/3125 | Loss: 0.0184

Epoch 24/30:  56%|█████▌    | 1752/3125 [03:46<02:52,  7.94it/s, loss=0.00232]

Epoch 24 | Batch 1750/3125 | Loss: 0.0263

Epoch 24/30:  58%|█████▊    | 1801/3125 [03:52<02:35,  8.52it/s, loss=0.0028]

Epoch 24 | Batch 1800/3125 | Loss: 0.0242

Epoch 24/30:  59%|█████▉    | 1852/3125 [03:58<02:37,  8.08it/s, loss=0.00239]

Epoch 24 | Batch 1850/3125 | Loss: 0.0060

Epoch 24/30:  61%|██████    | 1902/3125 [04:05<02:26,  8.32it/s, loss=0.00493]

Epoch 24 | Batch 1900/3125 | Loss: 0.0429

Epoch 24/30:  62%|██████▏   | 1950/3125 [04:11<02:49,  6.95it/s, loss=0.00175]

Epoch 24 | Batch 1950/3125 | Loss: 0.0018

Epoch 24/30:  64%|██████▍   | 2002/3125 [04:18<02:26,  7.64it/s, loss=0.00168]

Epoch 24 | Batch 2000/3125 | Loss: 0.0093

Epoch 24/30:  66%|██████▌   | 2052/3125 [04:25<02:11,  8.16it/s, loss=0.0491]

Epoch 24 | Batch 2050/3125 | Loss: 0.0003

Epoch 24/30:  67%|██████▋   | 2102/3125 [04:31<02:04,  8.23it/s, loss=0.00696]

Epoch 24 | Batch 2100/3125 | Loss: 0.0040

Epoch 24/30:  69%|██████▉   | 2152/3125 [04:37<02:00,  8.04it/s, loss=0.00495]

Epoch 24 | Batch 2150/3125 | Loss: 0.0312

Epoch 24/30:  70%|███████   | 2202/3125 [04:44<01:53,  8.12it/s, loss=0.00682]

Epoch 24 | Batch 2200/3125 | Loss: 0.0124

Epoch 24/30:  72%|███████▏  | 2250/3125 [04:50<01:52,  7.77it/s, loss=0.0058]

Epoch 24 | Batch 2250/3125 | Loss: 0.0058

Epoch 24/30:  74%|███████▎  | 2302/3125 [04:57<01:43,  7.98it/s, loss=0.00508]

Epoch 24 | Batch 2300/3125 | Loss: 0.0025

Epoch 24/30:  75%|███████▌  | 2352/3125 [05:03<01:36,  7.98it/s, loss=0.00373]

Epoch 24 | Batch 2350/3125 | Loss: 0.0064

Epoch 24/30:  77%|███████▋  | 2402/3125 [05:10<01:28,  8.19it/s, loss=0.00248]

Epoch 24 | Batch 2400/3125 | Loss: 0.0039

Epoch 24/30:  78%|███████▊  | 2452/3125 [05:16<01:28,  7.59it/s, loss=0.00341]

Epoch 24 | Batch 2450/3125 | Loss: 0.0111

Epoch 24/30:  80%|████████  | 2501/3125 [05:22<01:15,  8.24it/s, loss=0.0201]

Epoch 24 | Batch 2500/3125 | Loss: 0.0041

Epoch 24/30:  82%|████████▏ | 2550/3125 [05:29<01:23,  6.85it/s, loss=0.00782]

Epoch 24 | Batch 2550/3125 | Loss: 0.0078

Epoch 24/30:  83%|████████▎ | 2602/3125 [05:36<01:05,  8.02it/s, loss=0.0051]

Epoch 24 | Batch 2600/3125 | Loss: 0.0031

Epoch 24/30:  85%|████████▍ | 2651/3125 [05:42<01:02,  7.54it/s, loss=0.00402]

Epoch 24 | Batch 2650/3125 | Loss: 0.0036

Epoch 24/30:  86%|████████▋ | 2702/3125 [05:49<00:53,  7.89it/s, loss=0.00843]

Epoch 24 | Batch 2700/3125 | Loss: 0.0014

Epoch 24/30:  88%|████████▊ | 2752/3125 [05:55<00:44,  8.41it/s, loss=0.00657]

Epoch 24 | Batch 2750/3125 | Loss: 0.0035

Epoch 24/30:  90%|████████▉ | 2802/3125 [06:01<00:47,  6.75it/s, loss=0.00152]

Epoch 24 | Batch 2800/3125 | Loss: 0.0024

Epoch 24/30:  91%|█████████ | 2851/3125 [06:08<00:34,  7.99it/s, loss=0.00198]

Epoch 24 | Batch 2850/3125 | Loss: 0.0023

Epoch 24/30:  93%|█████████▎| 2901/3125 [06:15<00:31,  7.19it/s, loss=0.00876]

Epoch 24 | Batch 2900/3125 | Loss: 0.0041

Epoch 24/30:  94%|█████████▍| 2951/3125 [06:21<00:21,  8.15it/s, loss=0.00298]

Epoch 24 | Batch 2950/3125 | Loss: 0.0032

Epoch 24/30:  96%|█████████▌| 3001/3125 [06:27<00:15,  8.05it/s, loss=0.00145]

Epoch 24 | Batch 3000/3125 | Loss: 0.0045

Epoch 24/30:  98%|█████████▊| 3052/3125 [06:34<00:09,  7.76it/s, loss=0.00593]

Epoch 24 | Batch 3050/3125 | Loss: 0.0025

Epoch 24/30:  99%|█████████▉| 3102/3125 [06:40<00:03,  6.96it/s, loss=0.00779]

Epoch 24 | Batch 3100/3125 | Loss: 0.0095

Epoch 24/30: 100%|██████████| 3125/3125 [06:44<00:00,  7.73it/s, loss=0.00698]

Epoch [24/30] - Avg Loss: 0.0082

Epoch 25/30:   0%|          | 1/3125 [00:00<16:53,  3.08it/s, loss=0.00649]

Epoch 25 | Batch 0/3125 | Loss: 0.0061

Epoch 25/30:   2%|▏         | 51/3125 [00:06<06:27,  7.93it/s, loss=0.0017]

Epoch 25 | Batch 50/3125 | Loss: 0.0033

Epoch 25/30:   3%|▎         | 101/3125 [00:13<06:30,  7.75it/s, loss=0.00581]

Epoch 25 | Batch 100/3125 | Loss: 0.0030

Epoch 25/30:   5%|▍         | 151/3125 [00:19<06:04,  8.15it/s, loss=0.034]

Epoch 25 | Batch 150/3125 | Loss: 0.0296

Epoch 25/30:   6%|▋         | 201/3125 [00:25<05:52,  8.29it/s, loss=0.0271]

Epoch 25 | Batch 200/3125 | Loss: 0.0130

Epoch 25/30:   8%|▊         | 251/3125 [00:32<07:19,  6.54it/s, loss=0.00271]

Epoch 25 | Batch 250/3125 | Loss: 0.0027

Epoch 25/30:  10%|▉         | 301/3125 [00:39<06:14,  7.55it/s, loss=0.00264]

Epoch 25 | Batch 300/3125 | Loss: 0.0013

Epoch 25/30:  11%|█         | 351/3125 [00:45<05:47,  7.98it/s, loss=0.0045]

Epoch 25 | Batch 350/3125 | Loss: 0.0029

Epoch 25/30:  13%|█▎        | 401/3125 [00:52<05:54,  7.69it/s, loss=0.0109]

Epoch 25 | Batch 400/3125 | Loss: 0.0019

Epoch 25/30:  14%|█▍        | 451/3125 [00:58<05:37,  7.93it/s, loss=0.00556]

Epoch 25 | Batch 450/3125 | Loss: 0.0043

Epoch 25/30:  16%|█▌        | 501/3125 [01:05<05:48,  7.54it/s, loss=0.00145]

Epoch 25 | Batch 500/3125 | Loss: 0.0084

Epoch 25/30:  18%|█▊        | 551/3125 [01:12<05:48,  7.40it/s, loss=0.00319]

Epoch 25 | Batch 550/3125 | Loss: 0.0314

Epoch 25/30:  19%|█▉        | 601/3125 [01:19<05:43,  7.36it/s, loss=0.00366]

Epoch 25 | Batch 600/3125 | Loss: 0.0023

Epoch 25/30:  21%|██        | 652/3125 [01:25<05:32,  7.43it/s, loss=0.00298]

Epoch 25 | Batch 650/3125 | Loss: 0.0019

Epoch 25/30:  22%|██▏       | 702/3125 [01:31<05:07,  7.89it/s, loss=0.000882]

Epoch 25 | Batch 700/3125 | Loss: 0.0054

Epoch 25/30:  24%|██▍       | 751/3125 [01:38<04:58,  7.94it/s, loss=0.00988]

Epoch 25 | Batch 750/3125 | Loss: 0.0121

Epoch 25/30:  26%|██▌       | 801/3125 [01:44<04:39,  8.31it/s, loss=0.00446]

Epoch 25 | Batch 800/3125 | Loss: 0.0055

Epoch 25/30:  27%|██▋       | 851/3125 [01:51<05:59,  6.32it/s, loss=0.00685]

Epoch 25 | Batch 850/3125 | Loss: 0.0449

Epoch 25/30:  29%|██▉       | 901/3125 [01:58<04:47,  7.74it/s, loss=0.00558]

Epoch 25 | Batch 900/3125 | Loss: 0.0122

Epoch 25/30:  30%|███       | 952/3125 [02:04<04:31,  8.02it/s, loss=0.00474]

Epoch 25 | Batch 950/3125 | Loss: 0.0044

Epoch 25/30:  32%|███▏      | 1002/3125 [02:11<04:25,  8.01it/s, loss=0.00479]

Epoch 25 | Batch 1000/3125 | Loss: 0.0365

Epoch 25/30:  34%|███▎      | 1052/3125 [02:17<04:29,  7.69it/s, loss=0.00418]

Epoch 25 | Batch 1050/3125 | Loss: 0.0061

Epoch 25/30:  35%|███▌      | 1100/3125 [02:24<05:06,  6.62it/s, loss=0.00981]

Epoch 25 | Batch 1100/3125 | Loss: 0.0098

Epoch 25/30:  37%|███▋      | 1152/3125 [02:31<04:03,  8.11it/s, loss=0.00787]

Epoch 25 | Batch 1150/3125 | Loss: 0.0037

Epoch 25/30:  38%|███▊      | 1201/3125 [02:37<04:19,  7.40it/s, loss=0.0103]

Epoch 25 | Batch 1200/3125 | Loss: 0.0028

Epoch 25/30:  40%|████      | 1251/3125 [02:44<04:07,  7.57it/s, loss=0.0446]

Epoch 25 | Batch 1250/3125 | Loss: 0.0057

Epoch 25/30:  42%|████▏     | 1301/3125 [02:50<04:01,  7.56it/s, loss=0.00215]

Epoch 25 | Batch 1300/3125 | Loss: 0.0109

Epoch 25/30:  43%|████▎     | 1351/3125 [02:56<03:37,  8.16it/s, loss=0.00811]

Epoch 25 | Batch 1350/3125 | Loss: 0.0540

Epoch 25/30:  45%|████▍     | 1401/3125 [03:03<04:30,  6.37it/s, loss=0.00652]

Epoch 25 | Batch 1400/3125 | Loss: 0.0022

Epoch 25/30:  46%|████▋     | 1451/3125 [03:10<03:28,  8.03it/s, loss=0.00317]

Epoch 25 | Batch 1450/3125 | Loss: 0.0076

Epoch 25/30:  48%|████▊     | 1501/3125 [03:16<03:27,  7.82it/s, loss=0.0117]

Epoch 25 | Batch 1500/3125 | Loss: 0.0024

Epoch 25/30:  50%|████▉     | 1551/3125 [03:22<03:15,  8.06it/s, loss=0.0155]

Epoch 25 | Batch 1550/3125 | Loss: 0.0025

Epoch 25/30:  51%|█████     | 1601/3125 [03:29<03:15,  7.79it/s, loss=0.00171]

Epoch 25 | Batch 1600/3125 | Loss: 0.0069

Epoch 25/30:  53%|█████▎    | 1652/3125 [03:35<03:11,  7.71it/s, loss=0.00571]

Epoch 25 | Batch 1650/3125 | Loss: 0.0033

Epoch 25/30:  54%|█████▍    | 1702/3125 [03:43<03:43,  6.37it/s, loss=0.0035]

Epoch 25 | Batch 1700/3125 | Loss: 0.0035

Epoch 25/30:  56%|█████▌    | 1752/3125 [03:49<02:46,  8.27it/s, loss=0.00225]

Epoch 25 | Batch 1750/3125 | Loss: 0.0068

Epoch 25/30:  58%|█████▊    | 1802/3125 [03:55<03:06,  7.09it/s, loss=0.002]

Epoch 25 | Batch 1800/3125 | Loss: 0.0121

Epoch 25/30:  59%|█████▉    | 1852/3125 [04:02<02:36,  8.12it/s, loss=0.00481]

Epoch 25 | Batch 1850/3125 | Loss: 0.0037

Epoch 25/30:  61%|██████    | 1901/3125 [04:08<02:28,  8.23it/s, loss=0.00432]

Epoch 25 | Batch 1900/3125 | Loss: 0.0017

Epoch 25/30:  62%|██████▏   | 1951/3125 [04:14<02:38,  7.42it/s, loss=0.00217]

Epoch 25 | Batch 1950/3125 | Loss: 0.0010

Epoch 25/30:  64%|██████▍   | 2002/3125 [04:21<02:33,  7.29it/s, loss=0.00401]

Epoch 25 | Batch 2000/3125 | Loss: 0.0039

Epoch 25/30:  66%|██████▌   | 2052/3125 [04:28<02:16,  7.87it/s, loss=0.0127]

Epoch 25 | Batch 2050/3125 | Loss: 0.0021

Epoch 25/30:  67%|██████▋   | 2102/3125 [04:34<02:10,  7.84it/s, loss=0.00384]

Epoch 25 | Batch 2100/3125 | Loss: 0.0018

Epoch 25/30:  69%|██████▉   | 2152/3125 [04:40<01:58,  8.19it/s, loss=0.00239]

Epoch 25 | Batch 2150/3125 | Loss: 0.0027

Epoch 25/30:  70%|███████   | 2200/3125 [04:46<01:47,  8.58it/s, loss=0.0063]

Epoch 25 | Batch 2200/3125 | Loss: 0.0063

Epoch 25/30:  72%|███████▏  | 2252/3125 [04:53<01:48,  8.08it/s, loss=0.00413]

Epoch 25 | Batch 2250/3125 | Loss: 0.0022

Epoch 25/30:  74%|███████▎  | 2301/3125 [04:59<01:41,  8.10it/s, loss=0.00382]

Epoch 25 | Batch 2300/3125 | Loss: 0.0050

Epoch 25/30:  75%|███████▌  | 2351/3125 [05:05<01:41,  7.61it/s, loss=0.00562]

Epoch 25 | Batch 2350/3125 | Loss: 0.0076

Epoch 25/30:  77%|███████▋  | 2402/3125 [05:12<01:33,  7.73it/s, loss=0.0104]

Epoch 25 | Batch 2400/3125 | Loss: 0.0018

Epoch 25/30:  78%|███████▊  | 2452/3125 [05:18<01:23,  8.06it/s, loss=0.00135]

Epoch 25 | Batch 2450/3125 | Loss: 0.0044

Epoch 25/30:  80%|████████  | 2502/3125 [05:25<01:30,  6.86it/s, loss=0.00329]

Epoch 25 | Batch 2500/3125 | Loss: 0.0025

Epoch 25/30:  82%|████████▏ | 2551/3125 [05:32<01:09,  8.22it/s, loss=0.0039]

Epoch 25 | Batch 2550/3125 | Loss: 0.0016

Epoch 25/30:  83%|████████▎ | 2601/3125 [05:38<01:04,  8.13it/s, loss=0.0121]

Epoch 25 | Batch 2600/3125 | Loss: 0.0480

Epoch 25/30:  85%|████████▍ | 2652/3125 [05:44<00:54,  8.69it/s, loss=0.00304]

Epoch 25 | Batch 2650/3125 | Loss: 0.0030

Epoch 25/30:  86%|████████▋ | 2701/3125 [05:51<00:51,  8.27it/s, loss=0.00255]

Epoch 25 | Batch 2700/3125 | Loss: 0.0018

Epoch 25/30:  88%|████████▊ | 2752/3125 [05:57<00:47,  7.86it/s, loss=0.0227]

Epoch 25 | Batch 2750/3125 | Loss: 0.0024

Epoch 25/30:  90%|████████▉ | 2802/3125 [06:04<00:43,  7.50it/s, loss=0.00181]

Epoch 25 | Batch 2800/3125 | Loss: 0.0010

Epoch 25/30:  91%|█████████▏| 2852/3125 [06:10<00:35,  7.76it/s, loss=0.0438]

Epoch 25 | Batch 2850/3125 | Loss: 0.0031

Epoch 25/30:  93%|█████████▎| 2902/3125 [06:16<00:26,  8.42it/s, loss=0.0021]

Epoch 25 | Batch 2900/3125 | Loss: 0.0502

Epoch 25/30:  94%|█████████▍| 2952/3125 [06:22<00:22,  7.58it/s, loss=0.0079]

Epoch 25 | Batch 2950/3125 | Loss: 0.0198

Epoch 25/30:  96%|█████████▌| 3000/3125 [06:29<00:16,  7.69it/s, loss=0.00239]

Epoch 25 | Batch 3000/3125 | Loss: 0.0024

Epoch 25/30:  98%|█████████▊| 3052/3125 [06:36<00:09,  7.98it/s, loss=0.00835]

Epoch 25 | Batch 3050/3125 | Loss: 0.0042

Epoch 25/30:  99%|█████████▉| 3102/3125 [06:43<00:03,  7.50it/s, loss=0.00422]

Epoch 25 | Batch 3100/3125 | Loss: 0.0023

Epoch 25/30: 100%|██████████| 3125/3125 [06:46<00:00,  7.69it/s, loss=0.0221]

Epoch [25/30] - Avg Loss: 0.0072

Epoch 26/30:   0%|          | 1/3125 [00:00<14:59,  3.47it/s, loss=0.00843]

Epoch 26 | Batch 0/3125 | Loss: 0.0041

Epoch 26/30:   2%|▏         | 52/3125 [00:06<06:35,  7.77it/s, loss=0.0163]

Epoch 26 | Batch 50/3125 | Loss: 0.0206

Epoch 26/30:   3%|▎         | 102/3125 [00:13<06:18,  7.98it/s, loss=0.0143]

Epoch 26 | Batch 100/3125 | Loss: 0.0068

Epoch 26/30:   5%|▍         | 152/3125 [00:19<05:57,  8.32it/s, loss=0.0225]

Epoch 26 | Batch 150/3125 | Loss: 0.0083

Epoch 26/30:   6%|▋         | 201/3125 [00:25<06:08,  7.94it/s, loss=0.00601]

Epoch 26 | Batch 200/3125 | Loss: 0.0159

Epoch 26/30:   8%|▊         | 251/3125 [00:31<05:46,  8.29it/s, loss=0.00279]

Epoch 26 | Batch 250/3125 | Loss: 0.0104

Epoch 26/30:  10%|▉         | 301/3125 [00:37<05:47,  8.12it/s, loss=0.00629]

Epoch 26 | Batch 300/3125 | Loss: 0.0035

Epoch 26/30:  11%|█         | 351/3125 [00:43<05:42,  8.09it/s, loss=0.00506]

Epoch 26 | Batch 350/3125 | Loss: 0.0028

Epoch 26/30:  13%|█▎        | 402/3125 [00:50<06:04,  7.46it/s, loss=0.00248]

Epoch 26 | Batch 400/3125 | Loss: 0.0034

Epoch 26/30:  14%|█▍        | 451/3125 [00:57<06:03,  7.37it/s, loss=0.00596]

Epoch 26 | Batch 450/3125 | Loss: 0.0030

Epoch 26/30:  16%|█▌        | 501/3125 [01:03<05:24,  8.07it/s, loss=0.00525]

Epoch 26 | Batch 500/3125 | Loss: 0.0065

Epoch 26/30:  18%|█▊        | 551/3125 [01:10<05:05,  8.43it/s, loss=0.00137]

Epoch 26 | Batch 550/3125 | Loss: 0.0055

Epoch 26/30:  19%|█▉        | 601/3125 [01:16<05:38,  7.46it/s, loss=0.00664]

Epoch 26 | Batch 600/3125 | Loss: 0.0015

Epoch 26/30:  21%|██        | 651/3125 [01:22<04:55,  8.37it/s, loss=0.00479]

Epoch 26 | Batch 650/3125 | Loss: 0.0032

Epoch 26/30:  22%|██▏       | 702/3125 [01:28<05:05,  7.92it/s, loss=0.00205]

Epoch 26 | Batch 700/3125 | Loss: 0.0020

Epoch 26/30:  24%|██▍       | 752/3125 [01:34<04:54,  8.05it/s, loss=0.005]

Epoch 26 | Batch 750/3125 | Loss: 0.0029

Epoch 26/30:  26%|██▌       | 802/3125 [01:41<04:56,  7.84it/s, loss=0.00349]

Epoch 26 | Batch 800/3125 | Loss: 0.0067

Epoch 26/30:  27%|██▋       | 852/3125 [01:47<04:49,  7.86it/s, loss=0.00402]

Epoch 26 | Batch 850/3125 | Loss: 0.0024

Epoch 26/30:  29%|██▉       | 901/3125 [01:53<04:41,  7.91it/s, loss=0.00146]

Epoch 26 | Batch 900/3125 | Loss: 0.0025

Epoch 26/30:  30%|███       | 952/3125 [02:00<05:30,  6.57it/s, loss=0.00359]

Epoch 26 | Batch 950/3125 | Loss: 0.0018

Epoch 26/30:  32%|███▏      | 1002/3125 [02:07<04:21,  8.12it/s, loss=0.003]

Epoch 26 | Batch 1000/3125 | Loss: 0.0052

Epoch 26/30:  34%|███▎      | 1052/3125 [02:13<04:03,  8.50it/s, loss=0.00146]

Epoch 26 | Batch 1050/3125 | Loss: 0.0014

Epoch 26/30:  35%|███▌      | 1100/3125 [02:19<04:06,  8.22it/s, loss=0.00295]

Epoch 26 | Batch 1100/3125 | Loss: 0.0029

Epoch 26/30:  37%|███▋      | 1152/3125 [02:26<04:14,  7.74it/s, loss=0.00159]

Epoch 26 | Batch 1150/3125 | Loss: 0.0056

Epoch 26/30:  38%|███▊      | 1202/3125 [02:32<04:04,  7.87it/s, loss=0.00708]

Epoch 26 | Batch 1200/3125 | Loss: 0.0024

Epoch 26/30:  40%|████      | 1252/3125 [02:38<03:46,  8.26it/s, loss=0.0013]

Epoch 26 | Batch 1250/3125 | Loss: 0.0026

Epoch 26/30:  42%|████▏     | 1302/3125 [02:44<03:39,  8.29it/s, loss=0.00209]

Epoch 26 | Batch 1300/3125 | Loss: 0.0032

Epoch 26/30:  43%|████▎     | 1352/3125 [02:50<03:40,  8.04it/s, loss=0.00225]

Epoch 26 | Batch 1350/3125 | Loss: 0.0014

Epoch 26/30:  45%|████▍     | 1402/3125 [02:57<03:38,  7.90it/s, loss=0.00198]

Epoch 26 | Batch 1400/3125 | Loss: 0.0035

Epoch 26/30:  46%|████▋     | 1452/3125 [03:03<03:33,  7.83it/s, loss=0.00746]

Epoch 26 | Batch 1450/3125 | Loss: 0.0030

Epoch 26/30:  48%|████▊     | 1500/3125 [03:10<04:02,  6.69it/s, loss=0.00383]

Epoch 26 | Batch 1500/3125 | Loss: 0.0038

Epoch 26/30:  50%|████▉     | 1552/3125 [03:17<03:25,  7.64it/s, loss=0.00265]

Epoch 26 | Batch 1550/3125 | Loss: 0.0014

Epoch 26/30:  51%|█████▏    | 1602/3125 [03:23<03:02,  8.34it/s, loss=0.00703]

Epoch 26 | Batch 1600/3125 | Loss: 0.0044

Epoch 26/30:  53%|█████▎    | 1650/3125 [03:29<03:00,  8.16it/s, loss=0.00166]

Epoch 26 | Batch 1650/3125 | Loss: 0.0017

Epoch 26/30:  54%|█████▍    | 1702/3125 [03:36<02:59,  7.94it/s, loss=0.00572]

Epoch 26 | Batch 1700/3125 | Loss: 0.0043

Epoch 26/30:  56%|█████▌    | 1752/3125 [03:42<02:54,  7.88it/s, loss=0.00238]

Epoch 26 | Batch 1750/3125 | Loss: 0.0056

Epoch 26/30:  58%|█████▊    | 1802/3125 [03:48<02:48,  7.86it/s, loss=0.0373]

Epoch 26 | Batch 1800/3125 | Loss: 0.0031

Epoch 26/30:  59%|█████▉    | 1850/3125 [03:55<02:40,  7.93it/s, loss=0.00393]

Epoch 26 | Batch 1850/3125 | Loss: 0.0039

Epoch 26/30:  61%|██████    | 1902/3125 [04:01<02:38,  7.73it/s, loss=0.0141]

Epoch 26 | Batch 1900/3125 | Loss: 0.0055

Epoch 26/30:  62%|██████▏   | 1952/3125 [04:07<02:28,  7.90it/s, loss=0.00364]

Epoch 26 | Batch 1950/3125 | Loss: 0.0016

Epoch 26/30:  64%|██████▍   | 2000/3125 [04:14<02:36,  7.19it/s, loss=0.0184]

Epoch 26 | Batch 2000/3125 | Loss: 0.0184

Epoch 26/30:  66%|██████▌   | 2050/3125 [04:21<02:14,  7.97it/s, loss=0.017]

Epoch 26 | Batch 2050/3125 | Loss: 0.0170

Epoch 26/30:  67%|██████▋   | 2100/3125 [04:27<02:05,  8.20it/s, loss=0.00154]

Epoch 26 | Batch 2100/3125 | Loss: 0.0015

Epoch 26/30:  69%|██████▉   | 2152/3125 [04:33<02:03,  7.89it/s, loss=0.00291]

Epoch 26 | Batch 2150/3125 | Loss: 0.0494

Epoch 26/30:  70%|███████   | 2202/3125 [04:40<01:48,  8.51it/s, loss=0.00534]

Epoch 26 | Batch 2200/3125 | Loss: 0.0174

Epoch 26/30:  72%|███████▏  | 2252/3125 [04:46<01:48,  8.04it/s, loss=0.00549]

Epoch 26 | Batch 2250/3125 | Loss: 0.0125

Epoch 26/30:  74%|███████▎  | 2302/3125 [04:52<01:38,  8.32it/s, loss=0.0125]

Epoch 26 | Batch 2300/3125 | Loss: 0.0218

Epoch 26/30:  75%|███████▌  | 2352/3125 [04:58<01:30,  8.57it/s, loss=0.00229]

Epoch 26 | Batch 2350/3125 | Loss: 0.0122

Epoch 26/30:  77%|███████▋  | 2400/3125 [05:04<01:30,  7.99it/s, loss=0.0033]

Epoch 26 | Batch 2400/3125 | Loss: 0.0033

Epoch 26/30:  78%|███████▊  | 2450/3125 [05:11<01:24,  8.00it/s, loss=0.00435]

Epoch 26 | Batch 2450/3125 | Loss: 0.0044

Epoch 26/30:  80%|████████  | 2502/3125 [05:17<01:17,  8.08it/s, loss=0.00433]

Epoch 26 | Batch 2500/3125 | Loss: 0.0162

Epoch 26/30:  82%|████████▏ | 2551/3125 [05:23<01:16,  7.46it/s, loss=0.00456]

Epoch 26 | Batch 2550/3125 | Loss: 0.0014

Epoch 26/30:  83%|████████▎ | 2601/3125 [05:30<01:01,  8.58it/s, loss=0.00761]

Epoch 26 | Batch 2600/3125 | Loss: 0.0024

Epoch 26/30:  85%|████████▍ | 2651/3125 [05:36<00:59,  8.01it/s, loss=0.00205]

Epoch 26 | Batch 2650/3125 | Loss: 0.0023

Epoch 26/30:  86%|████████▋ | 2701/3125 [05:43<00:52,  8.14it/s, loss=0.00625]

Epoch 26 | Batch 2700/3125 | Loss: 0.0043

Epoch 26/30:  88%|████████▊ | 2751/3125 [05:49<00:48,  7.67it/s, loss=0.00594]

Epoch 26 | Batch 2750/3125 | Loss: 0.0052

Epoch 26/30:  90%|████████▉ | 2801/3125 [05:56<00:40,  8.02it/s, loss=0.00747]

Epoch 26 | Batch 2800/3125 | Loss: 0.0010

Epoch 26/30:  91%|█████████ | 2851/3125 [06:02<00:35,  7.76it/s, loss=0.00274]

Epoch 26 | Batch 2850/3125 | Loss: 0.0768

Epoch 26/30:  93%|█████████▎| 2901/3125 [06:08<00:27,  8.16it/s, loss=0.00159]

Epoch 26 | Batch 2900/3125 | Loss: 0.0068

Epoch 26/30:  94%|█████████▍| 2951/3125 [06:15<00:24,  7.19it/s, loss=0.0638]

Epoch 26 | Batch 2950/3125 | Loss: 0.0090

Epoch 26/30:  96%|█████████▌| 3001/3125 [06:21<00:15,  7.85it/s, loss=0.00545]

Epoch 26 | Batch 3000/3125 | Loss: 0.0082

Epoch 26/30:  98%|█████████▊| 3051/3125 [06:27<00:10,  7.12it/s, loss=0.0112]

Epoch 26 | Batch 3050/3125 | Loss: 0.0070

Epoch 26/30:  99%|█████████▉| 3101/3125 [06:35<00:03,  6.97it/s, loss=0.0044]

Epoch 26 | Batch 3100/3125 | Loss: 0.0032

Epoch 26/30: 100%|██████████| 3125/3125 [06:38<00:00,  7.85it/s, loss=0.00148]

Epoch [26/30] - Avg Loss: 0.0075

Epoch 27/30:   0%|          | 1/3125 [00:00<16:37,  3.13it/s, loss=0.00183]

Epoch 27 | Batch 0/3125 | Loss: 0.0071

Epoch 27/30:   2%|▏         | 51/3125 [00:06<06:34,  7.78it/s, loss=0.0243]

Epoch 27 | Batch 50/3125 | Loss: 0.0029

Epoch 27/30:   3%|▎         | 101/3125 [00:13<06:41,  7.54it/s, loss=0.0106]

Epoch 27 | Batch 100/3125 | Loss: 0.0048

Epoch 27/30:   5%|▍         | 151/3125 [00:19<06:47,  7.29it/s, loss=0.00485]

Epoch 27 | Batch 150/3125 | Loss: 0.0017

Epoch 27/30:   6%|▋         | 201/3125 [00:26<06:09,  7.92it/s, loss=0.01]

Epoch 27 | Batch 200/3125 | Loss: 0.0028

Epoch 27/30:   8%|▊         | 251/3125 [00:32<06:18,  7.58it/s, loss=0.01]

Epoch 27 | Batch 250/3125 | Loss: 0.0029

Epoch 27/30:  10%|▉         | 301/3125 [00:38<05:53,  7.99it/s, loss=0.0078]

Epoch 27 | Batch 300/3125 | Loss: 0.0016

Epoch 27/30:  11%|█▏        | 352/3125 [00:45<05:53,  7.84it/s, loss=0.00307]

Epoch 27 | Batch 350/3125 | Loss: 0.0050

Epoch 27/30:  13%|█▎        | 401/3125 [00:51<05:36,  8.10it/s, loss=0.00358]

Epoch 27 | Batch 400/3125 | Loss: 0.0024

Epoch 27/30:  14%|█▍        | 452/3125 [00:57<05:24,  8.23it/s, loss=0.00187]

Epoch 27 | Batch 450/3125 | Loss: 0.0040

Epoch 27/30:  16%|█▌        | 500/3125 [01:05<06:14,  7.02it/s, loss=0.000725]

Epoch 27 | Batch 500/3125 | Loss: 0.0007

Epoch 27/30:  18%|█▊        | 550/3125 [01:11<05:38,  7.61it/s, loss=0.00346]

Epoch 27 | Batch 550/3125 | Loss: 0.0035

Epoch 27/30:  19%|█▉        | 600/3125 [01:18<05:27,  7.72it/s, loss=0.00183]

Epoch 27 | Batch 600/3125 | Loss: 0.0018

Epoch 27/30:  21%|██        | 650/3125 [01:24<05:27,  7.56it/s, loss=0.00238]

Epoch 27 | Batch 650/3125 | Loss: 0.0024

Epoch 27/30:  22%|██▏       | 700/3125 [01:30<05:08,  7.86it/s, loss=0.00115]

Epoch 27 | Batch 700/3125 | Loss: 0.0011

Epoch 27/30:  24%|██▍       | 750/3125 [01:37<05:20,  7.40it/s, loss=0.00211]

Epoch 27 | Batch 750/3125 | Loss: 0.0021

Epoch 27/30:  26%|██▌       | 800/3125 [01:44<04:54,  7.90it/s, loss=0.00342]

Epoch 27 | Batch 800/3125 | Loss: 0.0034

Epoch 27/30:  27%|██▋       | 852/3125 [01:50<05:06,  7.42it/s, loss=0.00495]

Epoch 27 | Batch 850/3125 | Loss: 0.0035

Epoch 27/30:  29%|██▉       | 902/3125 [01:57<04:40,  7.94it/s, loss=0.00458]

Epoch 27 | Batch 900/3125 | Loss: 0.0037

Epoch 27/30:  30%|███       | 952/3125 [02:03<04:30,  8.04it/s, loss=0.00882]

Epoch 27 | Batch 950/3125 | Loss: 0.0035

Epoch 27/30:  32%|███▏      | 1001/3125 [02:10<05:31,  6.41it/s, loss=0.00194]

Epoch 27 | Batch 1000/3125 | Loss: 0.0057

Epoch 27/30:  34%|███▎      | 1051/3125 [02:17<04:34,  7.56it/s, loss=0.00355]

Epoch 27 | Batch 1050/3125 | Loss: 0.0018

Epoch 27/30:  35%|███▌      | 1101/3125 [02:23<04:23,  7.69it/s, loss=0.00238]

Epoch 27 | Batch 1100/3125 | Loss: 0.0019

Epoch 27/30:  37%|███▋      | 1151/3125 [02:30<04:09,  7.91it/s, loss=0.0338]

Epoch 27 | Batch 1150/3125 | Loss: 0.0014

Epoch 27/30:  38%|███▊      | 1201/3125 [02:37<04:06,  7.79it/s, loss=0.00441]

Epoch 27 | Batch 1200/3125 | Loss: 0.0084

Epoch 27/30:  40%|████      | 1251/3125 [02:43<03:59,  7.83it/s, loss=0.00162]

Epoch 27 | Batch 1250/3125 | Loss: 0.0014

Epoch 27/30:  42%|████▏     | 1301/3125 [02:50<03:57,  7.69it/s, loss=0.00367]

Epoch 27 | Batch 1300/3125 | Loss: 0.0440

Epoch 27/30:  43%|████▎     | 1351/3125 [02:57<04:14,  6.96it/s, loss=0.00366]

Epoch 27 | Batch 1350/3125 | Loss: 0.0007

Epoch 27/30:  45%|████▍     | 1401/3125 [03:03<03:39,  7.86it/s, loss=0.0159]

Epoch 27 | Batch 1400/3125 | Loss: 0.0056

Epoch 27/30:  46%|████▋     | 1451/3125 [03:10<03:43,  7.48it/s, loss=0.00658]

Epoch 27 | Batch 1450/3125 | Loss: 0.0177

Epoch 27/30:  48%|████▊     | 1501/3125 [03:17<04:03,  6.67it/s, loss=0.00181]

Epoch 27 | Batch 1500/3125 | Loss: 0.0019

Epoch 27/30:  50%|████▉     | 1551/3125 [03:24<03:40,  7.14it/s, loss=0.00173]

Epoch 27 | Batch 1550/3125 | Loss: 0.0069

Epoch 27/30:  51%|█████     | 1601/3125 [03:30<03:23,  7.48it/s, loss=0.00196]

Epoch 27 | Batch 1600/3125 | Loss: 0.0054

Epoch 27/30:  53%|█████▎    | 1652/3125 [03:36<02:54,  8.42it/s, loss=0.00162]

Epoch 27 | Batch 1650/3125 | Loss: 0.0026

Epoch 27/30:  54%|█████▍    | 1702/3125 [03:43<02:52,  8.23it/s, loss=0.00128]

Epoch 27 | Batch 1700/3125 | Loss: 0.0108

Epoch 27/30:  56%|█████▌    | 1752/3125 [03:49<02:59,  7.66it/s, loss=0.00394]

Epoch 27 | Batch 1750/3125 | Loss: 0.0087

Epoch 27/30:  58%|█████▊    | 1802/3125 [03:56<02:47,  7.91it/s, loss=0.00129]

Epoch 27 | Batch 1800/3125 | Loss: 0.0019

Epoch 27/30:  59%|█████▉    | 1852/3125 [04:02<02:36,  8.15it/s, loss=0.00251]

Epoch 27 | Batch 1850/3125 | Loss: 0.0066

Epoch 27/30:  61%|██████    | 1902/3125 [04:08<02:27,  8.26it/s, loss=0.00159]

Epoch 27 | Batch 1900/3125 | Loss: 0.0022

Epoch 27/30:  62%|██████▏   | 1950/3125 [04:15<02:32,  7.69it/s, loss=0.00201]

Epoch 27 | Batch 1950/3125 | Loss: 0.0020

Epoch 27/30:  64%|██████▍   | 2001/3125 [04:21<02:20,  7.98it/s, loss=0.0126]

Epoch 27 | Batch 2000/3125 | Loss: 0.0018

Epoch 27/30:  66%|██████▌   | 2050/3125 [04:28<02:44,  6.53it/s, loss=0.00804]

Epoch 27 | Batch 2050/3125 | Loss: 0.0080

Epoch 27/30:  67%|██████▋   | 2102/3125 [04:35<02:02,  8.34it/s, loss=0.0097]

Epoch 27 | Batch 2100/3125 | Loss: 0.0059

Epoch 27/30:  69%|██████▉   | 2152/3125 [04:41<02:03,  7.90it/s, loss=0.00483]

Epoch 27 | Batch 2150/3125 | Loss: 0.0042

Epoch 27/30:  70%|███████   | 2202/3125 [04:47<01:56,  7.92it/s, loss=0.00336]

Epoch 27 | Batch 2200/3125 | Loss: 0.0027

Epoch 27/30:  72%|███████▏  | 2251/3125 [04:53<01:47,  8.13it/s, loss=0.00464]

Epoch 27 | Batch 2250/3125 | Loss: 0.0084

Epoch 27/30:  74%|███████▎  | 2301/3125 [05:00<01:41,  8.16it/s, loss=0.00164]

Epoch 27 | Batch 2300/3125 | Loss: 0.0022

Epoch 27/30:  75%|███████▌  | 2351/3125 [05:06<01:38,  7.88it/s, loss=0.0211]

Epoch 27 | Batch 2350/3125 | Loss: 0.0046

Epoch 27/30:  77%|███████▋  | 2401/3125 [05:12<01:30,  7.96it/s, loss=0.0103]

Epoch 27 | Batch 2400/3125 | Loss: 0.0054

Epoch 27/30:  78%|███████▊  | 2451/3125 [05:19<01:24,  7.97it/s, loss=0.00151]

Epoch 27 | Batch 2450/3125 | Loss: 0.0139

Epoch 27/30:  80%|████████  | 2501/3125 [05:25<01:13,  8.44it/s, loss=0.021]

Epoch 27 | Batch 2500/3125 | Loss: 0.0168

Epoch 27/30:  82%|████████▏ | 2551/3125 [05:31<01:16,  7.46it/s, loss=0.00425]

Epoch 27 | Batch 2550/3125 | Loss: 0.0199

Epoch 27/30:  83%|████████▎ | 2600/3125 [05:38<01:08,  7.67it/s, loss=0.00314]

Epoch 27 | Batch 2600/3125 | Loss: 0.0031

Epoch 27/30:  85%|████████▍ | 2652/3125 [05:45<01:00,  7.75it/s, loss=0.00256]

Epoch 27 | Batch 2650/3125 | Loss: 0.0205

Epoch 27/30:  86%|████████▋ | 2700/3125 [05:51<00:52,  8.07it/s, loss=0.00309]

Epoch 27 | Batch 2700/3125 | Loss: 0.0031

Epoch 27/30:  88%|████████▊ | 2752/3125 [05:58<00:47,  7.78it/s, loss=0.018]

Epoch 27 | Batch 2750/3125 | Loss: 0.0060

Epoch 27/30:  90%|████████▉ | 2800/3125 [06:04<00:38,  8.35it/s, loss=0.00316]

Epoch 27 | Batch 2800/3125 | Loss: 0.0032

Epoch 27/30:  91%|█████████ | 2850/3125 [06:10<00:34,  8.06it/s, loss=0.0173]

Epoch 27 | Batch 2850/3125 | Loss: 0.0027

Epoch 27/30:  93%|█████████▎| 2902/3125 [06:16<00:27,  8.18it/s, loss=0.00283]

Epoch 27 | Batch 2900/3125 | Loss: 0.0068

Epoch 27/30:  94%|█████████▍| 2952/3125 [06:22<00:20,  8.43it/s, loss=0.00248]

Epoch 27 | Batch 2950/3125 | Loss: 0.0021

Epoch 27/30:  96%|█████████▌| 3002/3125 [06:28<00:16,  7.66it/s, loss=0.000983]

Epoch 27 | Batch 3000/3125 | Loss: 0.0042

Epoch 27/30:  98%|█████████▊| 3052/3125 [06:35<00:08,  8.47it/s, loss=0.00376]

Epoch 27 | Batch 3050/3125 | Loss: 0.0024

Epoch 27/30:  99%|█████████▉| 3101/3125 [06:41<00:03,  6.84it/s, loss=0.00506]

Epoch 27 | Batch 3100/3125 | Loss: 0.0081

Epoch 27/30: 100%|██████████| 3125/3125 [06:45<00:00,  7.71it/s, loss=0.00211]

Epoch [27/30] - Avg Loss: 0.0070

Epoch 28/30:   0%|          | 2/3125 [00:00<09:09,  5.68it/s, loss=0.00336]

Epoch 28 | Batch 0/3125 | Loss: 0.0016

Epoch 28/30:   2%|▏         | 51/3125 [00:06<06:08,  8.35it/s, loss=0.00329]

Epoch 28 | Batch 50/3125 | Loss: 0.0029

Epoch 28/30:   3%|▎         | 101/3125 [00:13<06:52,  7.33it/s, loss=0.00623]

Epoch 28 | Batch 100/3125 | Loss: 0.0029

Epoch 28/30:   5%|▍         | 151/3125 [00:19<06:05,  8.13it/s, loss=0.00245]

Epoch 28 | Batch 150/3125 | Loss: 0.0033

Epoch 28/30:   6%|▋         | 201/3125 [00:25<05:41,  8.56it/s, loss=0.00343]

Epoch 28 | Batch 200/3125 | Loss: 0.0023

Epoch 28/30:   8%|▊         | 251/3125 [00:31<05:55,  8.09it/s, loss=0.00177]

Epoch 28 | Batch 250/3125 | Loss: 0.0016

Epoch 28/30:  10%|▉         | 301/3125 [00:37<06:06,  7.70it/s, loss=0.0161]

Epoch 28 | Batch 300/3125 | Loss: 0.0028

Epoch 28/30:  11%|█         | 351/3125 [00:43<06:08,  7.52it/s, loss=0.00184]

Epoch 28 | Batch 350/3125 | Loss: 0.0146

Epoch 28/30:  13%|█▎        | 401/3125 [00:50<05:34,  8.15it/s, loss=0.00149]

Epoch 28 | Batch 400/3125 | Loss: 0.0017

Epoch 28/30:  14%|█▍        | 451/3125 [00:56<05:31,  8.07it/s, loss=0.000985]

Epoch 28 | Batch 450/3125 | Loss: 0.0323

Epoch 28/30:  16%|█▌        | 501/3125 [01:02<06:29,  6.74it/s, loss=0.027]

Epoch 28 | Batch 500/3125 | Loss: 0.0026

Epoch 28/30:  18%|█▊        | 551/3125 [01:10<05:25,  7.90it/s, loss=0.00343]

Epoch 28 | Batch 550/3125 | Loss: 0.0030

Epoch 28/30:  19%|█▉        | 601/3125 [01:16<04:59,  8.42it/s, loss=0.00318]

Epoch 28 | Batch 600/3125 | Loss: 0.0019

Epoch 28/30:  21%|██        | 651/3125 [01:22<05:22,  7.66it/s, loss=0.00575]

Epoch 28 | Batch 650/3125 | Loss: 0.0055

Epoch 28/30:  22%|██▏       | 701/3125 [01:28<04:54,  8.22it/s, loss=0.00924]

Epoch 28 | Batch 700/3125 | Loss: 0.0037

Epoch 28/30:  24%|██▍       | 751/3125 [01:34<05:18,  7.44it/s, loss=0.00301]

Epoch 28 | Batch 750/3125 | Loss: 0.0027

Epoch 28/30:  26%|██▌       | 801/3125 [01:41<04:35,  8.42it/s, loss=0.00174]

Epoch 28 | Batch 800/3125 | Loss: 0.0018

Epoch 28/30:  27%|██▋       | 852/3125 [01:47<04:33,  8.30it/s, loss=0.0011]

Epoch 28 | Batch 850/3125 | Loss: 0.0029

Epoch 28/30:  29%|██▉       | 902/3125 [01:53<04:42,  7.88it/s, loss=0.00169]

Epoch 28 | Batch 900/3125 | Loss: 0.0016

Epoch 28/30:  30%|███       | 952/3125 [01:59<04:15,  8.49it/s, loss=0.00122]

Epoch 28 | Batch 950/3125 | Loss: 0.0017

Epoch 28/30:  32%|███▏      | 1001/3125 [02:05<04:28,  7.92it/s, loss=0.00262]

Epoch 28 | Batch 1000/3125 | Loss: 0.0021

Epoch 28/30:  34%|███▎      | 1051/3125 [02:11<04:31,  7.65it/s, loss=0.00138]

Epoch 28 | Batch 1050/3125 | Loss: 0.0031

Epoch 28/30:  35%|███▌      | 1102/3125 [02:19<04:38,  7.27it/s, loss=0.0155]

Epoch 28 | Batch 1100/3125 | Loss: 0.0017

Epoch 28/30:  37%|███▋      | 1152/3125 [02:25<03:53,  8.45it/s, loss=0.000456]

Epoch 28 | Batch 1150/3125 | Loss: 0.0083

Epoch 28/30:  38%|███▊      | 1202/3125 [02:31<03:50,  8.33it/s, loss=0.00311]

Epoch 28 | Batch 1200/3125 | Loss: 0.0008

Epoch 28/30:  40%|████      | 1252/3125 [02:37<03:52,  8.04it/s, loss=0.0023]

Epoch 28 | Batch 1250/3125 | Loss: 0.0020

Epoch 28/30:  42%|████▏     | 1302/3125 [02:43<03:40,  8.27it/s, loss=0.00326]

Epoch 28 | Batch 1300/3125 | Loss: 0.0034

Epoch 28/30:  43%|████▎     | 1350/3125 [02:49<03:41,  8.00it/s, loss=0.00502]

Epoch 28 | Batch 1350/3125 | Loss: 0.0050

Epoch 28/30:  45%|████▍     | 1402/3125 [02:56<03:36,  7.97it/s, loss=0.00388]

Epoch 28 | Batch 1400/3125 | Loss: 0.0016

Epoch 28/30:  46%|████▋     | 1452/3125 [03:02<03:25,  8.15it/s, loss=0.00322]

Epoch 28 | Batch 1450/3125 | Loss: 0.0027

Epoch 28/30:  48%|████▊     | 1502/3125 [03:08<03:12,  8.43it/s, loss=0.00244]

Epoch 28 | Batch 1500/3125 | Loss: 0.0022

Epoch 28/30:  50%|████▉     | 1552/3125 [03:14<03:15,  8.06it/s, loss=0.00244]

Epoch 28 | Batch 1550/3125 | Loss: 0.0015

Epoch 28/30:  51%|█████     | 1601/3125 [03:20<03:28,  7.32it/s, loss=0.00416]

Epoch 28 | Batch 1600/3125 | Loss: 0.0041

Epoch 28/30:  53%|█████▎    | 1651/3125 [03:28<03:07,  7.86it/s, loss=0.0044]

Epoch 28 | Batch 1650/3125 | Loss: 0.0025

Epoch 28/30:  54%|█████▍    | 1701/3125 [03:34<02:52,  8.23it/s, loss=0.00403]

Epoch 28 | Batch 1700/3125 | Loss: 0.0017

Epoch 28/30:  56%|█████▌    | 1751/3125 [03:40<02:42,  8.45it/s, loss=0.00619]

Epoch 28 | Batch 1750/3125 | Loss: 0.0024

Epoch 28/30:  58%|█████▊    | 1802/3125 [03:46<02:44,  8.05it/s, loss=0.00621]

Epoch 28 | Batch 1800/3125 | Loss: 0.0025

Epoch 28/30:  59%|█████▉    | 1852/3125 [03:52<02:25,  8.73it/s, loss=0.0061]

Epoch 28 | Batch 1850/3125 | Loss: 0.0014

Epoch 28/30:  61%|██████    | 1900/3125 [03:58<02:21,  8.66it/s, loss=0.00369]

Epoch 28 | Batch 1900/3125 | Loss: 0.0037

Epoch 28/30:  62%|██████▏   | 1950/3125 [04:04<02:31,  7.76it/s, loss=0.00417]

Epoch 28 | Batch 1950/3125 | Loss: 0.0042

Epoch 28/30:  64%|██████▍   | 2000/3125 [04:11<02:15,  8.27it/s, loss=0.00239]

Epoch 28 | Batch 2000/3125 | Loss: 0.0024

Epoch 28/30:  66%|██████▌   | 2052/3125 [04:17<02:10,  8.24it/s, loss=0.00146]

Epoch 28 | Batch 2050/3125 | Loss: 0.0053

Epoch 28/30:  67%|██████▋   | 2102/3125 [04:23<01:59,  8.56it/s, loss=0.00135]

Epoch 28 | Batch 2100/3125 | Loss: 0.0024

Epoch 28/30:  69%|██████▉   | 2150/3125 [04:29<02:25,  6.71it/s, loss=0.00214]

Epoch 28 | Batch 2150/3125 | Loss: 0.0021

Epoch 28/30:  70%|███████   | 2201/3125 [04:36<01:59,  7.73it/s, loss=0.00192]

Epoch 28 | Batch 2200/3125 | Loss: 0.0022

Epoch 28/30:  72%|███████▏  | 2251/3125 [04:43<01:51,  7.85it/s, loss=0.00729]

Epoch 28 | Batch 2250/3125 | Loss: 0.0161

Epoch 28/30:  74%|███████▎  | 2301/3125 [04:49<01:48,  7.59it/s, loss=0.0211]

Epoch 28 | Batch 2300/3125 | Loss: 0.0050

Epoch 28/30:  75%|███████▌  | 2351/3125 [04:56<01:40,  7.70it/s, loss=0.00217]

Epoch 28 | Batch 2350/3125 | Loss: 0.0082

Epoch 28/30:  77%|███████▋  | 2401/3125 [05:02<01:30,  8.01it/s, loss=0.00218]

Epoch 28 | Batch 2400/3125 | Loss: 0.0069

Epoch 28/30:  78%|███████▊  | 2451/3125 [05:08<01:27,  7.67it/s, loss=0.00194]

Epoch 28 | Batch 2450/3125 | Loss: 0.0097

Epoch 28/30:  80%|████████  | 2501/3125 [05:15<01:20,  7.75it/s, loss=0.00854]

Epoch 28 | Batch 2500/3125 | Loss: 0.0035

Epoch 28/30:  82%|████████▏ | 2551/3125 [05:21<01:11,  8.08it/s, loss=0.00127]

Epoch 28 | Batch 2550/3125 | Loss: 0.0016

Epoch 28/30:  83%|████████▎ | 2602/3125 [05:27<01:21,  6.40it/s, loss=0.00209]

Epoch 28 | Batch 2600/3125 | Loss: 0.0026

Epoch 28/30:  85%|████████▍ | 2652/3125 [05:34<01:02,  7.59it/s, loss=0.00846]

Epoch 28 | Batch 2650/3125 | Loss: 0.0022

Epoch 28/30:  86%|████████▋ | 2702/3125 [05:41<00:57,  7.37it/s, loss=0.00213]

Epoch 28 | Batch 2700/3125 | Loss: 0.0033

Epoch 28/30:  88%|████████▊ | 2752/3125 [05:48<00:45,  8.15it/s, loss=0.0186]

Epoch 28 | Batch 2750/3125 | Loss: 0.0066

Epoch 28/30:  90%|████████▉ | 2802/3125 [05:55<00:43,  7.46it/s, loss=0.00262]

Epoch 28 | Batch 2800/3125 | Loss: 0.0024

Epoch 28/30:  91%|█████████▏| 2852/3125 [06:01<00:33,  8.10it/s, loss=0.00416]

Epoch 28 | Batch 2850/3125 | Loss: 0.0013

Epoch 28/30:  93%|█████████▎| 2900/3125 [06:07<00:27,  8.24it/s, loss=0.00584]

Epoch 28 | Batch 2900/3125 | Loss: 0.0046

Epoch 28/30:  94%|█████████▍| 2950/3125 [06:14<00:23,  7.47it/s, loss=0.00179]

Epoch 28 | Batch 2950/3125 | Loss: 0.0018

Epoch 28/30:  96%|█████████▌| 3002/3125 [06:20<00:15,  7.93it/s, loss=0.00276]

Epoch 28 | Batch 3000/3125 | Loss: 0.0008

Epoch 28/30:  98%|█████████▊| 3052/3125 [06:27<00:08,  8.24it/s, loss=0.0363]

Epoch 28 | Batch 3050/3125 | Loss: 0.0050

Epoch 28/30:  99%|█████████▉| 3100/3125 [06:33<00:03,  6.59it/s, loss=0.00335]

Epoch 28 | Batch 3100/3125 | Loss: 0.0034

Epoch 28/30: 100%|██████████| 3125/3125 [06:36<00:00,  7.87it/s, loss=0.0457]

Epoch [28/30] - Avg Loss: 0.0052

Epoch 29/30:   0%|          | 1/3125 [00:00<16:08,  3.23it/s, loss=0.026]

Epoch 29 | Batch 0/3125 | Loss: 0.0078

Epoch 29/30:   2%|▏         | 52/3125 [00:06<06:37,  7.73it/s, loss=0.00343]

Epoch 29 | Batch 50/3125 | Loss: 0.0016

Epoch 29/30:   3%|▎         | 101/3125 [00:14<06:57,  7.24it/s, loss=0.00105]

Epoch 29 | Batch 100/3125 | Loss: 0.0030

Epoch 29/30:   5%|▍         | 152/3125 [00:20<06:14,  7.94it/s, loss=0.00585]

Epoch 29 | Batch 150/3125 | Loss: 0.0038

Epoch 29/30:   6%|▋         | 202/3125 [00:27<06:12,  7.85it/s, loss=0.00992]

Epoch 29 | Batch 200/3125 | Loss: 0.0021

Epoch 29/30:   8%|▊         | 252/3125 [00:33<05:32,  8.64it/s, loss=0.0248]

Epoch 29 | Batch 250/3125 | Loss: 0.0144

Epoch 29/30:  10%|▉         | 302/3125 [00:39<06:04,  7.74it/s, loss=0.00156]

Epoch 29 | Batch 300/3125 | Loss: 0.0045

Epoch 29/30:  11%|█▏        | 352/3125 [00:45<05:38,  8.19it/s, loss=0.000858]

Epoch 29 | Batch 350/3125 | Loss: 0.0062

Epoch 29/30:  13%|█▎        | 402/3125 [00:52<05:40,  7.99it/s, loss=0.00552]

Epoch 29 | Batch 400/3125 | Loss: 0.0087

Epoch 29/30:  14%|█▍        | 452/3125 [00:58<05:14,  8.51it/s, loss=0.00396]

Epoch 29 | Batch 450/3125 | Loss: 0.0014

Epoch 29/30:  16%|█▌        | 502/3125 [01:04<05:24,  8.10it/s, loss=0.00302]

Epoch 29 | Batch 500/3125 | Loss: 0.0014

Epoch 29/30:  18%|█▊        | 550/3125 [01:10<05:25,  7.92it/s, loss=0.00111]

Epoch 29 | Batch 550/3125 | Loss: 0.0011

Epoch 29/30:  19%|█▉        | 602/3125 [01:16<05:49,  7.23it/s, loss=0.0113]

Epoch 29 | Batch 600/3125 | Loss: 0.0009

Epoch 29/30:  21%|██        | 651/3125 [01:24<06:00,  6.85it/s, loss=0.000443]

Epoch 29 | Batch 650/3125 | Loss: 0.0013

Epoch 29/30:  22%|██▏       | 701/3125 [01:30<04:54,  8.24it/s, loss=0.00393]

Epoch 29 | Batch 700/3125 | Loss: 0.0010

Epoch 29/30:  24%|██▍       | 751/3125 [01:36<05:04,  7.79it/s, loss=0.00558]

Epoch 29 | Batch 750/3125 | Loss: 0.0025

Epoch 29/30:  26%|██▌       | 801/3125 [01:42<04:33,  8.51it/s, loss=0.00231]

Epoch 29 | Batch 800/3125 | Loss: 0.0027

Epoch 29/30:  27%|██▋       | 851/3125 [01:49<04:54,  7.73it/s, loss=0.00415]

Epoch 29 | Batch 850/3125 | Loss: 0.0039

Epoch 29/30:  29%|██▉       | 901/3125 [01:58<04:31,  8.18it/s, loss=0.0025]

Epoch 29 | Batch 900/3125 | Loss: 0.0009

Epoch 29/30:  30%|███       | 951/3125 [02:05<04:23,  8.26it/s, loss=0.00227]

Epoch 29 | Batch 950/3125 | Loss: 0.0215

Epoch 29/30:  32%|███▏      | 1001/3125 [02:11<04:20,  8.16it/s, loss=0.00314]

Epoch 29 | Batch 1000/3125 | Loss: 0.0032

Epoch 29/30:  34%|███▎      | 1051/3125 [02:17<04:26,  7.78it/s, loss=0.00542]

Epoch 29 | Batch 1050/3125 | Loss: 0.0023

Epoch 29/30:  35%|███▌      | 1101/3125 [02:24<04:26,  7.60it/s, loss=0.0011]

Epoch 29 | Batch 1100/3125 | Loss: 0.0071

Epoch 29/30:  37%|███▋      | 1150/3125 [02:31<04:45,  6.91it/s, loss=0.00212]

Epoch 29 | Batch 1150/3125 | Loss: 0.0021

Epoch 29/30:  38%|███▊      | 1202/3125 [02:38<03:51,  8.30it/s, loss=0.00199]

Epoch 29 | Batch 1200/3125 | Loss: 0.0028

Epoch 29/30:  40%|████      | 1252/3125 [02:44<04:02,  7.71it/s, loss=0.00191]

Epoch 29 | Batch 1250/3125 | Loss: 0.0017

Epoch 29/30:  42%|████▏     | 1302/3125 [02:50<03:40,  8.27it/s, loss=0.00383]

Epoch 29 | Batch 1300/3125 | Loss: 0.0408

Epoch 29/30:  43%|████▎     | 1352/3125 [02:56<03:47,  7.79it/s, loss=0.00192]

Epoch 29 | Batch 1350/3125 | Loss: 0.0108

Epoch 29/30:  45%|████▍     | 1402/3125 [03:03<03:37,  7.94it/s, loss=0.006]

Epoch 29 | Batch 1400/3125 | Loss: 0.0022

Epoch 29/30:  46%|████▋     | 1452/3125 [03:09<03:31,  7.90it/s, loss=0.00916]

Epoch 29 | Batch 1450/3125 | Loss: 0.0043

Epoch 29/30:  48%|████▊     | 1502/3125 [03:15<03:18,  8.17it/s, loss=0.0012]

Epoch 29 | Batch 1500/3125 | Loss: 0.0030

Epoch 29/30:  50%|████▉     | 1552/3125 [03:21<03:05,  8.47it/s, loss=0.0081]

Epoch 29 | Batch 1550/3125 | Loss: 0.0010

Epoch 29/30:  51%|█████▏    | 1602/3125 [03:28<03:06,  8.16it/s, loss=0.00753]

Epoch 29 | Batch 1600/3125 | Loss: 0.0016

Epoch 29/30:  53%|█████▎    | 1652/3125 [03:34<03:15,  7.54it/s, loss=0.00259]

Epoch 29 | Batch 1650/3125 | Loss: 0.0020

Epoch 29/30:  54%|█████▍    | 1700/3125 [03:41<03:31,  6.75it/s, loss=0.00748]

Epoch 29 | Batch 1700/3125 | Loss: 0.0075

Epoch 29/30:  56%|█████▌    | 1750/3125 [03:48<02:55,  7.82it/s, loss=0.00714]

Epoch 29 | Batch 1750/3125 | Loss: 0.0071

Epoch 29/30:  58%|█████▊    | 1802/3125 [03:54<02:42,  8.14it/s, loss=0.0022]

Epoch 29 | Batch 1800/3125 | Loss: 0.0018

Epoch 29/30:  59%|█████▉    | 1852/3125 [04:00<02:30,  8.49it/s, loss=0.00091]

Epoch 29 | Batch 1850/3125 | Loss: 0.0013

Epoch 29/30:  61%|██████    | 1902/3125 [04:06<02:25,  8.40it/s, loss=0.00147]

Epoch 29 | Batch 1900/3125 | Loss: 0.0038

Epoch 29/30:  62%|██████▏   | 1952/3125 [04:13<02:27,  7.97it/s, loss=0.000928]

Epoch 29 | Batch 1950/3125 | Loss: 0.0026

Epoch 29/30:  64%|██████▍   | 2002/3125 [04:19<02:27,  7.61it/s, loss=0.00433]

Epoch 29 | Batch 2000/3125 | Loss: 0.0129

Epoch 29/30:  66%|██████▌   | 2052/3125 [04:25<02:21,  7.59it/s, loss=0.00402]

Epoch 29 | Batch 2050/3125 | Loss: 0.0044

Epoch 29/30:  67%|██████▋   | 2101/3125 [04:31<02:07,  8.00it/s, loss=0.00346]

Epoch 29 | Batch 2100/3125 | Loss: 0.0037

Epoch 29/30:  69%|██████▉   | 2151/3125 [04:38<02:02,  7.96it/s, loss=0.00348]

Epoch 29 | Batch 2150/3125 | Loss: 0.0036

Epoch 29/30:  70%|███████   | 2201/3125 [04:44<02:16,  6.79it/s, loss=0.00171]

Epoch 29 | Batch 2200/3125 | Loss: 0.0024

Epoch 29/30:  72%|███████▏  | 2252/3125 [04:52<01:46,  8.18it/s, loss=0.00157]

Epoch 29 | Batch 2250/3125 | Loss: 0.0027

Epoch 29/30:  74%|███████▎  | 2302/3125 [04:58<01:39,  8.28it/s, loss=0.00144]

Epoch 29 | Batch 2300/3125 | Loss: 0.0025

Epoch 29/30:  75%|███████▌  | 2352/3125 [05:04<01:35,  8.12it/s, loss=0.00977]

Epoch 29 | Batch 2350/3125 | Loss: 0.0014

Epoch 29/30:  77%|███████▋  | 2402/3125 [05:10<01:27,  8.24it/s, loss=0.00117]

Epoch 29 | Batch 2400/3125 | Loss: 0.0021

Epoch 29/30:  78%|███████▊  | 2451/3125 [05:16<01:26,  7.77it/s, loss=0.00195]

Epoch 29 | Batch 2450/3125 | Loss: 0.0144

Epoch 29/30:  80%|████████  | 2501/3125 [05:23<01:16,  8.11it/s, loss=0.00444]

Epoch 29 | Batch 2500/3125 | Loss: 0.0907

Epoch 29/30:  82%|████████▏ | 2552/3125 [05:29<01:10,  8.09it/s, loss=0.0028]

Epoch 29 | Batch 2550/3125 | Loss: 0.0020

Epoch 29/30:  83%|████████▎ | 2602/3125 [05:35<01:04,  8.15it/s, loss=0.00174]

Epoch 29 | Batch 2600/3125 | Loss: 0.0019

Epoch 29/30:  85%|████████▍ | 2651/3125 [05:41<00:58,  8.14it/s, loss=0.00498]

Epoch 29 | Batch 2650/3125 | Loss: 0.0023

Epoch 29/30:  86%|████████▋ | 2701/3125 [05:48<00:55,  7.69it/s, loss=0.00394]

Epoch 29 | Batch 2700/3125 | Loss: 0.0025

Epoch 29/30:  88%|████████▊ | 2752/3125 [05:55<00:53,  7.03it/s, loss=0.00603]

Epoch 29 | Batch 2750/3125 | Loss: 0.0061

Epoch 29/30:  90%|████████▉ | 2801/3125 [06:02<00:41,  7.82it/s, loss=0.00102]

Epoch 29 | Batch 2800/3125 | Loss: 0.0053

Epoch 29/30:  91%|█████████ | 2851/3125 [06:08<00:33,  8.18it/s, loss=0.00299]

Epoch 29 | Batch 2850/3125 | Loss: 0.0028

Epoch 29/30:  93%|█████████▎| 2901/3125 [06:14<00:27,  8.06it/s, loss=0.00131]

Epoch 29 | Batch 2900/3125 | Loss: 0.0112

Epoch 29/30:  94%|█████████▍| 2951/3125 [06:21<00:21,  8.13it/s, loss=0.00174]

Epoch 29 | Batch 2950/3125 | Loss: 0.0049

Epoch 29/30:  96%|█████████▌| 3001/3125 [06:27<00:15,  8.06it/s, loss=0.00216]

Epoch 29 | Batch 3000/3125 | Loss: 0.0023

Epoch 29/30:  98%|█████████▊| 3051/3125 [06:33<00:09,  7.86it/s, loss=0.00267]

Epoch 29 | Batch 3050/3125 | Loss: 0.0012

Epoch 29/30:  99%|█████████▉| 3101/3125 [06:39<00:03,  7.54it/s, loss=0.0485]

Epoch 29 | Batch 3100/3125 | Loss: 0.0011

Epoch 29/30: 100%|██████████| 3125/3125 [06:42<00:00,  7.76it/s, loss=0.00215]

Epoch [29/30] - Avg Loss: 0.0056

Epoch 30/30:   0%|          | 1/3125 [00:00<14:38,  3.56it/s, loss=0.000954]

Epoch 30 | Batch 0/3125 | Loss: 0.0029

Epoch 30/30:   2%|▏         | 51/3125 [00:06<06:03,  8.46it/s, loss=0.0019]

Epoch 30 | Batch 50/3125 | Loss: 0.0012

Epoch 30/30:   3%|▎         | 101/3125 [00:13<06:46,  7.43it/s, loss=0.00242]

Epoch 30 | Batch 100/3125 | Loss: 0.0027

Epoch 30/30:   5%|▍         | 151/3125 [00:19<06:56,  7.14it/s, loss=0.00119]

Epoch 30 | Batch 150/3125 | Loss: 0.0014

Epoch 30/30:   6%|▋         | 201/3125 [00:27<06:31,  7.46it/s, loss=0.00171]

Epoch 30 | Batch 200/3125 | Loss: 0.0018

Epoch 30/30:   8%|▊         | 251/3125 [00:33<06:05,  7.87it/s, loss=0.0014]

Epoch 30 | Batch 250/3125 | Loss: 0.0010

Epoch 30/30:  10%|▉         | 301/3125 [00:39<05:47,  8.14it/s, loss=0.00117]

Epoch 30 | Batch 300/3125 | Loss: 0.0074

Epoch 30/30:  11%|█         | 351/3125 [00:45<05:38,  8.20it/s, loss=0.00427]

Epoch 30 | Batch 350/3125 | Loss: 0.0034

Epoch 30/30:  13%|█▎        | 401/3125 [00:51<05:47,  7.83it/s, loss=0.000743]

Epoch 30 | Batch 400/3125 | Loss: 0.0010

Epoch 30/30:  14%|█▍        | 451/3125 [00:57<05:24,  8.24it/s, loss=0.00193]

Epoch 30 | Batch 450/3125 | Loss: 0.0013

Epoch 30/30:  16%|█▌        | 501/3125 [01:04<05:34,  7.85it/s, loss=0.00163]

Epoch 30 | Batch 500/3125 | Loss: 0.0013

Epoch 30/30:  18%|█▊        | 551/3125 [01:10<05:05,  8.43it/s, loss=0.00617]

Epoch 30 | Batch 550/3125 | Loss: 0.0022

Epoch 30/30:  19%|█▉        | 601/3125 [01:16<05:19,  7.89it/s, loss=0.00176]

Epoch 30 | Batch 600/3125 | Loss: 0.0191

Epoch 30/30:  21%|██        | 651/3125 [01:22<05:12,  7.92it/s, loss=0.00305]

Epoch 30 | Batch 650/3125 | Loss: 0.0047

Epoch 30/30:  22%|██▏       | 701/3125 [01:29<05:53,  6.87it/s, loss=0.00893]

Epoch 30 | Batch 700/3125 | Loss: 0.0052

Epoch 30/30:  24%|██▍       | 751/3125 [01:36<04:42,  8.39it/s, loss=0.00142]

Epoch 30 | Batch 750/3125 | Loss: 0.0063

Epoch 30/30:  26%|██▌       | 801/3125 [01:42<04:59,  7.76it/s, loss=0.00365]

Epoch 30 | Batch 800/3125 | Loss: 0.0013

Epoch 30/30:  27%|██▋       | 851/3125 [01:49<04:54,  7.73it/s, loss=0.00831]

Epoch 30 | Batch 850/3125 | Loss: 0.0046

Epoch 30/30:  29%|██▉       | 901/3125 [01:55<04:27,  8.33it/s, loss=0.00426]

Epoch 30 | Batch 900/3125 | Loss: 0.0014

Epoch 30/30:  30%|███       | 951/3125 [02:01<04:37,  7.83it/s, loss=0.00693]

Epoch 30 | Batch 950/3125 | Loss: 0.0014

Epoch 30/30:  32%|███▏      | 1001/3125 [02:07<04:18,  8.21it/s, loss=0.0031]

Epoch 30 | Batch 1000/3125 | Loss: 0.0007

Epoch 30/30:  34%|███▎      | 1051/3125 [02:14<04:29,  7.68it/s, loss=0.00205]

Epoch 30 | Batch 1050/3125 | Loss: 0.0046

Epoch 30/30:  35%|███▌      | 1101/3125 [02:20<04:27,  7.56it/s, loss=0.00234]

Epoch 30 | Batch 1100/3125 | Loss: 0.0016

Epoch 30/30:  37%|███▋      | 1151/3125 [02:27<04:06,  8.00it/s, loss=0.00163]

Epoch 30 | Batch 1150/3125 | Loss: 0.0038

Epoch 30/30:  38%|███▊      | 1201/3125 [02:33<04:25,  7.24it/s, loss=0.00466]

Epoch 30 | Batch 1200/3125 | Loss: 0.0027

Epoch 30/30:  40%|████      | 1251/3125 [02:41<04:49,  6.48it/s, loss=0.00125]

Epoch 30 | Batch 1250/3125 | Loss: 0.0026

Epoch 30/30:  42%|████▏     | 1301/3125 [02:47<03:44,  8.11it/s, loss=0.00616]

Epoch 30 | Batch 1300/3125 | Loss: 0.0208

Epoch 30/30:  43%|████▎     | 1351/3125 [02:54<03:48,  7.77it/s, loss=0.0025]

Epoch 30 | Batch 1350/3125 | Loss: 0.0072

Epoch 30/30:  45%|████▍     | 1401/3125 [03:00<03:33,  8.06it/s, loss=0.00107]

Epoch 30 | Batch 1400/3125 | Loss: 0.0020

Epoch 30/30:  46%|████▋     | 1451/3125 [03:06<03:21,  8.32it/s, loss=0.00584]

Epoch 30 | Batch 1450/3125 | Loss: 0.0016

Epoch 30/30:  48%|████▊     | 1501/3125 [03:12<03:19,  8.13it/s, loss=0.00455]

Epoch 30 | Batch 1500/3125 | Loss: 0.0039

Epoch 30/30:  50%|████▉     | 1551/3125 [03:18<03:11,  8.23it/s, loss=0.00196]

Epoch 30 | Batch 1550/3125 | Loss: 0.0061

Epoch 30/30:  51%|█████     | 1601/3125 [03:25<03:22,  7.53it/s, loss=0.00312]

Epoch 30 | Batch 1600/3125 | Loss: 0.0079

Epoch 30/30:  53%|█████▎    | 1651/3125 [03:31<03:03,  8.02it/s, loss=0.0129]

Epoch 30 | Batch 1650/3125 | Loss: 0.0089

Epoch 30/30:  54%|█████▍    | 1701/3125 [03:37<03:03,  7.78it/s, loss=0.00209]

Epoch 30 | Batch 1700/3125 | Loss: 0.0042

Epoch 30/30:  56%|█████▌    | 1751/3125 [03:44<03:14,  7.07it/s, loss=0.00223]

Epoch 30 | Batch 1750/3125 | Loss: 0.0082

Epoch 30/30:  58%|█████▊    | 1801/3125 [03:51<02:45,  7.98it/s, loss=0.00279]

Epoch 30 | Batch 1800/3125 | Loss: 0.0056

Epoch 30/30:  59%|█████▉    | 1851/3125 [03:58<02:42,  7.83it/s, loss=0.00071]

Epoch 30 | Batch 1850/3125 | Loss: 0.0055

Epoch 30/30:  61%|██████    | 1901/3125 [04:04<02:29,  8.20it/s, loss=0.0157]

Epoch 30 | Batch 1900/3125 | Loss: 0.0099

Epoch 30/30:  62%|██████▏   | 1951/3125 [04:10<02:22,  8.21it/s, loss=0.00156]

Epoch 30 | Batch 1950/3125 | Loss: 0.0031

Epoch 30/30:  64%|██████▍   | 2001/3125 [04:17<02:13,  8.44it/s, loss=0.00876]

Epoch 30 | Batch 2000/3125 | Loss: 0.0007

Epoch 30/30:  66%|██████▌   | 2052/3125 [04:23<02:07,  8.39it/s, loss=0.00219]

Epoch 30 | Batch 2050/3125 | Loss: 0.0067

Epoch 30/30:  67%|██████▋   | 2102/3125 [04:29<02:02,  8.32it/s, loss=0.00283]

Epoch 30 | Batch 2100/3125 | Loss: 0.0022

Epoch 30/30:  69%|██████▉   | 2152/3125 [04:35<01:58,  8.21it/s, loss=0.00244]

Epoch 30 | Batch 2150/3125 | Loss: 0.0178

Epoch 30/30:  70%|███████   | 2202/3125 [04:41<01:51,  8.26it/s, loss=0.00408]

Epoch 30 | Batch 2200/3125 | Loss: 0.0035

Epoch 30/30:  72%|███████▏  | 2252/3125 [04:48<01:47,  8.09it/s, loss=0.0027]

Epoch 30 | Batch 2250/3125 | Loss: 0.0015

Epoch 30/30:  74%|███████▎  | 2300/3125 [04:54<02:08,  6.44it/s, loss=0.00382]

Epoch 30 | Batch 2300/3125 | Loss: 0.0038

Epoch 30/30:  75%|███████▌  | 2350/3125 [05:02<01:39,  7.77it/s, loss=0.00104]

Epoch 30 | Batch 2350/3125 | Loss: 0.0010

Epoch 30/30:  77%|███████▋  | 2400/3125 [05:08<01:31,  7.90it/s, loss=0.00286]

Epoch 30 | Batch 2400/3125 | Loss: 0.0029

Epoch 30/30:  78%|███████▊  | 2450/3125 [05:14<01:24,  8.00it/s, loss=0.00143]

Epoch 30 | Batch 2450/3125 | Loss: 0.0014

Epoch 30/30:  80%|████████  | 2502/3125 [05:21<01:14,  8.31it/s, loss=0.000952]

Epoch 30 | Batch 2500/3125 | Loss: 0.0016

Epoch 30/30:  82%|████████▏ | 2552/3125 [05:27<01:10,  8.16it/s, loss=0.00223]

Epoch 30 | Batch 2550/3125 | Loss: 0.0071

Epoch 30/30:  83%|████████▎ | 2602/3125 [05:33<01:08,  7.61it/s, loss=0.0027]

Epoch 30 | Batch 2600/3125 | Loss: 0.0053

Epoch 30/30:  85%|████████▍ | 2652/3125 [05:39<00:59,  7.99it/s, loss=0.0012]

Epoch 30 | Batch 2650/3125 | Loss: 0.0033

Epoch 30/30:  86%|████████▋ | 2701/3125 [05:46<00:53,  7.99it/s, loss=0.00214]

Epoch 30 | Batch 2700/3125 | Loss: 0.0012

Epoch 30/30:  88%|████████▊ | 2751/3125 [05:52<00:49,  7.59it/s, loss=0.00403]

Epoch 30 | Batch 2750/3125 | Loss: 0.0015

Epoch 30/30:  90%|████████▉ | 2802/3125 [05:59<00:40,  7.90it/s, loss=0.0158]

Epoch 30 | Batch 2800/3125 | Loss: 0.0013

Epoch 30/30:  91%|█████████ | 2850/3125 [06:06<00:42,  6.47it/s, loss=0.003]

Epoch 30 | Batch 2850/3125 | Loss: 0.0030

Epoch 30/30:  93%|█████████▎| 2902/3125 [06:14<00:30,  7.43it/s, loss=0.0038]

Epoch 30 | Batch 2900/3125 | Loss: 0.0025

Epoch 30/30:  94%|█████████▍| 2950/3125 [06:20<00:22,  7.91it/s, loss=0.0133]

Epoch 30 | Batch 2950/3125 | Loss: 0.0133

Epoch 30/30:  96%|█████████▌| 3000/3125 [06:26<00:16,  7.52it/s, loss=0.000702]

Epoch 30 | Batch 3000/3125 | Loss: 0.0007

Epoch 30/30:  98%|█████████▊| 3052/3125 [06:33<00:09,  7.73it/s, loss=0.00566]

Epoch 30 | Batch 3050/3125 | Loss: 0.0129

Epoch 30/30:  99%|█████████▉| 3102/3125 [06:39<00:02,  7.93it/s, loss=0.0021]

Epoch 30 | Batch 3100/3125 | Loss: 0.0026

Epoch 30/30: 100%|██████████| 3125/3125 [06:42<00:00,  7.76it/s, loss=0.00284]

Epoch [30/30] - Avg Loss: 0.0060

## 13. Evaluation Function

`evaluate()` measures **speaker verification accuracy** on any DataLoader:
- Computes **cosine similarity** between the two speaker embeddings
- Predicts *same speaker* if similarity > 0.5
- Displays running accuracy live via `tqdm`
- No gradients computed (`torch.no_grad()` mode)

In [26]:
from tqdm import tqdm
import torch.nn.functional as F

def evaluate(model, loader):
    model.eval()
    correct = 0
    total = 0

    progress_bar = tqdm(loader, desc="Evaluating")

    with torch.no_grad():
        for mel1, mel2, labels in progress_bar:

            mel1 = mel1.to(device)
            mel2 = mel2.to(device)
            labels = labels.to(device)

            emb1 = model(mel1)
            emb2 = model(mel2)

            cosine_sim = F.cosine_similarity(emb1, emb2)
            preds = (cosine_sim > 0.5).float()

            correct += (preds == labels).sum().item()
            total += labels.size(0)

            # 🔥 Live accuracy update
            progress_bar.set_postfix(acc=correct / total)

    final_acc = correct / total
    print("\nFinal Accuracy:", final_acc)

## 14. Evaluate on Training Data

Run the trained model on the training set to measure in-sample accuracy as a quick sanity check.

In [27]:
evaluate(model, dataloader)

Evaluating: 100%|██████████| 3125/3125 [06:24<00:00,  8.13it/s, acc=0.945]

Final Accuracy: 0.94458

## 15. Save the Trained Model

Persist the model weights, current epoch, and optimizer state to `checkpoint.pth` on disk. This allows the model to be reloaded later for inference or training resumption without retraining.

In [28]:
torch.save({
    "model_state": model.state_dict(),
    "epoch": epoch,
    "optimizer_state": optimizer.state_dict()
}, "checkpoint.pth")

## 16. Load Test Dataset

Load the separate held-out test CSV. This dataset was not seen during training and provides an unbiased measure of the model's speaker verification performance.

In [29]:
TEST_CSV_PATH = "/kaggle/input/datasets/tahmidulislamomi/ml-project-testing-dataset/test_pairs.csv"

test_df = pd.read_csv(TEST_CSV_PATH)

print("Test rows:", len(test_df))
display(test_df.head())

Test rows: 50000

,audio_path_1,audio_path_2,label
0,test-clean/2961/961/2961-961-0008.flac,test-clean/2961/961/2961-961-0015.flac,1
1,test-clean/8555/284449/8555-284449-0015.flac,test-clean/8555/284447/8555-284447-0024.flac,1
2,test-clean/5639/40744/5639-40744-0007.flac,test-clean/5639/40744/5639-40744-0033.flac,1
3,test-clean/5683/32866/5683-32866-0026.flac,test-clean/5683/32879/5683-32879-0005.flac,1
4,test-clean/8230/279154/8230-279154-0002.flac,test-clean/8230/279154/8230-279154-0001.flac,1

## 17. Resolve Test Audio Paths

Follows the same pattern used for training: `to_test_absolute_path()` joins the relative path from the CSV with the real Kaggle test dataset directory.

In [30]:
import os

TEST_BASE_AUDIO_DIR = "/kaggle/input/datasets/tahmidulislamomi/ml-project-testing-dataset"

def to_test_absolute_path(rel_path):
    # Remove the hardcoded fake path
    cleaned = rel_path.replace("/kaggle/input/your-librispeech-dataset/", "", 1)
    # Join with your actual Kaggle directory
    return os.path.join(TEST_BASE_AUDIO_DIR, cleaned)

In [31]:
test_df["path1_abs"] = test_df["audio_path_1"].apply(to_test_absolute_path)
test_df["path2_abs"] = test_df["audio_path_2"].apply(to_test_absolute_path)

# Verify it works
print("Sample cleaned path:\n", test_df["path1_abs"].iloc[0])

Sample cleaned path:
 /kaggle/input/datasets/tahmidulislamomi/ml-project-testing-dataset/test-clean/2961/961/2961-961-0008.flac

## 18. Create Test Dataset

Instantiate `SpeakerPairDataset` for the test set using the same transforms (`mel_transform`, `amplitude_to_db`) as training.

In [32]:
test_dataset = SpeakerPairDataset(
    test_df,
    mel_transform,
    amplitude_to_db
)

## 19. Create Test DataLoader

Wrap the test dataset in a `DataLoader`.
- `shuffle = False` — preserve original row order for consistent, reproducible evaluation results

In [33]:
from torch.utils.data import DataLoader

test_loader = DataLoader(
    test_dataset,
    batch_size=16,
    shuffle=False,   # IMPORTANT: no shuffle for evaluation
    num_workers=2,
    pin_memory=True
)

## 20. Final Evaluation on Test Set

Run `evaluate()` on the held-out test set to obtain the **final test accuracy** — the key metric for this speaker verification project.

In [34]:
evaluate(model, test_loader)

Evaluating:   0%|          | 0/3125 [00:00<?, ?it/s]

TypeError: an integer is required